import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

type LedgerEntry = { hash: string; signature?: string };
type Ledger = Record<string, LedgerEntry>;

// ---------- config: defaults + overrides ----------
function getArg(prefix: string) {
  const a = process.argv.find((x) => x.startsWith(prefix));
  return a ? a.slice(prefix.length) : undefined;
}
const SRC_ROOT_DEFAULT = 'supabase/src';

// Default to supabase/src, allow --root=... or SQLSRC_ROOT to override
const ROOT = path.resolve(
  process.cwd(),
  getArg('--root=') ?? process.env.SQLSRC_ROOT ?? SRC_ROOT_DEFAULT
);
// Put the ledger alongside supabase/src (i.e., supabase/.migration-hash.json)
const LEDGER_PATH = path.resolve(ROOT, '..', '.migration-hash.json');
// Supabase migrations live here
const MIG_DIR = path.resolve(process.cwd(), 'supabase/migrations');

const ORDER = [
  'schemas',
  'indexes',
  'views',
  'functions/_private',
  'functions',
  'policies',
  'triggers',
  'grants',
  'comments'
];

const BOOTSTRAP = process.argv.includes('--bootstrap');

// ---------- utils ----------
function sha(s: string) {
  return crypto.createHash('sha256').update(s).digest('hex');
}
function readFileSafe(p: string) {
  return fs.readFileSync(p, 'utf8');
}
function readLedger(): Ledger {
  try {
    return JSON.parse(fs.readFileSync(LEDGER_PATH, 'utf8'));
  } catch {
    return {};
  }
}
function writeLedger(ledger: Ledger) {
  fs.mkdirSync(path.dirname(LEDGER_PATH), { recursive: true });
  fs.writeFileSync(LEDGER_PATH, JSON.stringify(ledger, null, 2));
}
function rel(p: string) {
  return path.relative(ROOT, p).replaceAll('\\', '/');
}
function walkDir(dir: string, acc: string[] = []) {
  if (!fs.existsSync(dir)) return acc;
  const entries = fs
    .readdirSync(dir, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name));
  for (const e of entries) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walkDir(p, acc);
    else if (e.isFile() && e.name.endsWith('.sql')) acc.push(p);
  }
  return acc;
}
function collectFiles(): string[] {
  const files: string[] = [];
  for (const folder of ORDER) {
    const d = path.join(ROOT, folder);
    if (fs.existsSync(d)) walkDir(d, files);
  }
  return files;
}

/**
 * Extract an optional @signature header from SQL comments.
 *   -- @signature: public.lock_pick(uuid, text, public.weight_enum)
 * Falls back to parsing CREATE OR REPLACE FUNCTION if missing.
 */
function extractSignature(sql: string): string | undefined {
  const m = sql.match(/^\s*--\s*@signature:\s*([^\r\n]+)\s*$/im);
  if (m) return m[1].trim();
  const m2 = sql.match(/create\s+or\s+replace\s+function\s+([a-z0-9_."]+)\s*\(([\s\S]*?)\)/i);
  if (!m2) return undefined;
  const name = m2[1].replace(/\s+/g, '');
  const argsRaw = m2[2]
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) =>
      s
        .replace(/\b(in|out|inout)\b/gi, '')
        .trim()
        .replace(/^[a-z_][a-z0-9_]*\s+/i, '')
    )
    .join(', ');
  return `${name}(${argsRaw})`;
}

function nowStamp() {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`;
}

function migrationHeader() {
  return `-- generated by scripts/gen-func-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;
`;
}

// ---------- main ----------
function main() {
  const ledger = readLedger();
  const files = collectFiles();

  if (files.length === 0) {
    console.log(`[gen] No .sql files found.
[gen] ROOT=${ROOT}
[gen] Ensure you have folders like ${ORDER.map((f) => `'${f}'`).join(', ')} under that root.`);
    if (BOOTSTRAP) {
      writeLedger(ledger);
      console.log('Bootstrapped ledger with 0 entries. No migration written.');
    }
    return;
  }

  const changes: {
    key: string;
    content: string;
    hash: string;
    signature?: string;
    old?: LedgerEntry;
  }[] = [];

  for (const abs of files) {
    const content = readFileSafe(abs).trim() + '\n';
    const hash = sha(content);
    const sig = extractSignature(content);
    const key = rel(abs);

    const prev = ledger[key];
    const changed =
      !prev || prev.hash !== hash || (sig && prev.signature && sig !== prev.signature);

    if (BOOTSTRAP) {
      ledger[key] = { hash, signature: sig };
      continue;
    }

    if (changed) changes.push({ key, content, hash, signature: sig, old: prev });
  }

  if (BOOTSTRAP) {
    writeLedger(ledger);
    console.log(
      `Bootstrapped ledger with ${Object.keys(ledger).length} entries. No migration written.`
    );
    return;
  }

  if (changes.length === 0) {
    console.log('No function/trigger/policy changes detected.');
    return;
  }

  fs.mkdirSync(MIG_DIR, { recursive: true });
  const outPath = path.join(MIG_DIR, `${nowStamp()}_migrations_patch.sql`);

  const drops: string[] = [];
  for (const c of changes) {
    if (c.old?.signature && c.signature && c.old.signature !== c.signature) {
      drops.push(
        `-- drop for signature change: ${c.key}\ndrop function if exists ${c.old.signature};`
      );
    }
  }

  const body = [
    migrationHeader(),
    drops.length ? `-- signature-adjustment drops\n${drops.join('\n')}\n` : '',
    ...changes.map((c) => `-- file: ${c.key}\n${c.content}`)
  ].join('\n');

  fs.writeFileSync(outPath, body, 'utf8');

  for (const c of changes) ledger[c.key] = { hash: c.hash, signature: c.signature };
  writeLedger(ledger);

  console.log(`Wrote ${outPath} with ${changes.length} change(s).`);
}

main();
