project_id = "sunday-bets"

[db.seed]
enabled = true

[auth]
site_url="http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/auth/callback"]
email.template.magic_link.content_path = "./supabase/magic_link.html"

[db]
port = 54322

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000