project_id = "sunday-bets"

[db.seed]
enabled = true

[auth]
site_url="http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/auth/callback"]
email.template.magic_link.content_path = "./supabase/magic_link.html"

[api]
max_rows = 10000