-- Atomic upsert+prune for the player_ratings rebuild (issue #619, ADR-0032 §8 follow-up).
--
-- src/lib/server/rating/rebuild.ts previously ran the full-table upsert and the stale-row prune as
-- two separate, non-transactional PostgREST calls. #622 made the prune concurrency-SAFE (delete
-- where computed_at < T, never != T, so a peer's fresher rows can never be wiped), but the two
-- statements are still not ATOMIC: nothing stops them from interleaving with a concurrent rebuild's
-- own pair, and a crash/network failure between them leaves the table in an intermediate state until
-- the next grade self-heals it. This function closes that gap two ways:
--
--   1. A transaction-scoped advisory lock (`pg_advisory_xact_lock`, auto-released at commit/
--      rollback -- never needs an explicit unlock) serializes concurrent rebuilds completely: a
--      second caller blocks until the first's upsert+prune has fully committed, so no interleaving
--      is possible even in principle (stronger than #622's defense-in-depth `lt` prune, which
--      tolerates interleaving but only after production hit the empty-table race in practice).
--   2. The upsert and prune run inside ONE function invocation, i.e. one Postgres transaction, so a
--      failure partway rolls back the whole rebuild rather than leaving a partial write.
--
-- Rows are passed as jsonb (not a composite array) so a single, uniform payload shape works
-- unchanged whether rebuild.ts is called from the SvelteKit runtime, a plain node script
-- (scripts/rebuildRatings.ts), or vitest -- see rebuild.ts's own header for why it stays
-- environment-agnostic. p_computed_at is generated by the caller (not `now()` here) so the caller's
-- one timestamp both stamps every upserted row and bounds the prune, exactly like the pre-RPC code.
create or replace function public._rebuild_player_ratings(p_rows jsonb, p_computed_at timestamptz)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform pg_advisory_xact_lock(hashtext('player_ratings_rebuild'));

  if jsonb_array_length(p_rows) > 0 then
    insert into public.player_ratings (
      group_id, user_id, rating, decisions, decisions_to_qualify, season_delta, computed_at
    )
    select
      (r->>'group_id')::uuid,
      (r->>'user_id')::uuid,
      (r->>'rating')::int,
      (r->>'decisions')::int,
      (r->>'decisions_to_qualify')::int,
      (r->>'season_delta')::int,
      p_computed_at
    from jsonb_array_elements(p_rows) as r
    on conflict (group_id, user_id) do update set
      rating               = excluded.rating,
      decisions            = excluded.decisions,
      decisions_to_qualify = excluded.decisions_to_qualify,
      season_delta         = excluded.season_delta,
      computed_at           = excluded.computed_at;
  end if;

  -- Same `lt` (never `!=`) prune #622 established: a concurrent peer's rows always carry a stamp
  -- >= its own p_computed_at, so they are never < ours. With the advisory lock above there is no
  -- longer a concurrent peer mid-write at all, but the `lt` bound is kept as defense in depth.
  delete from public.player_ratings where computed_at < p_computed_at;
end;
$$;
