-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."weight_enum" AS ENUM('L', 'M', 'H', 'A');--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"display_name" text NOT NULL,
	"role" text DEFAULT 'player' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "seasons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"league" text DEFAULT 'NFL' NOT NULL,
	"year" integer NOT NULL,
	CONSTRAINT "ux_seasons_league_year" UNIQUE("league","year")
);
--> statement-breakpoint
CREATE TABLE "weeks" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"season_id" integer NOT NULL,
	"week_number" integer NOT NULL,
	"start_ts" timestamp with time zone NOT NULL,
	"end_ts" timestamp with time zone NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	CONSTRAINT "ux_weeks_season_week" UNIQUE("season_id","week_number")
);
--> statement-breakpoint
CREATE TABLE "games" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"week_id" integer NOT NULL,
	"external_game_id" text,
	"espn_event_id" text,
	"commence_time" timestamp with time zone NOT NULL,
	"home_team_id" integer NOT NULL,
	"away_team_id" integer NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"final_scores" jsonb,
	CONSTRAINT "games_external_game_id_key" UNIQUE("external_game_id"),
	CONSTRAINT "games_espn_event_id_key" UNIQUE("espn_event_id")
);
--> statement-breakpoint
ALTER TABLE "games" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "teams" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teams_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"league" text DEFAULT 'NFL' NOT NULL,
	"external_key" text,
	"name" text NOT NULL,
	"short_name" text NOT NULL,
	CONSTRAINT "teams_external_key_key" UNIQUE("external_key")
);
--> statement-breakpoint
CREATE TABLE "game_lines" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game_lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"game_id" uuid NOT NULL,
	"source" text DEFAULT 'fanduel' NOT NULL,
	"spread_team_id" integer NOT NULL,
	"spread_value" numeric NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_active_line" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "game_lines" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "results" (
	"game_id" uuid PRIMARY KEY NOT NULL,
	"winning_team_id" integer,
	"cover_result" text,
	"graded_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "results" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "settings" (
	"id" boolean PRIMARY KEY DEFAULT true NOT NULL,
	"odds_api_monthly_cap" integer DEFAULT 500 NOT NULL,
	"odds_api_calls_used_current_month" integer DEFAULT 0 NOT NULL,
	"reset_on" date
);
--> statement-breakpoint
ALTER TABLE "settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"actor" uuid,
	"action" text NOT NULL,
	"details" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "audit_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "totals" (
	"user_id" uuid NOT NULL,
	"week_id" integer NOT NULL,
	"points_delta" integer DEFAULT 0 NOT NULL,
	"season_total_cached" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "totals_pkey" PRIMARY KEY("user_id","week_id")
);
--> statement-breakpoint
ALTER TABLE "totals" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "picks" (
	"user_id" uuid NOT NULL,
	"game_id" uuid NOT NULL,
	"picked_team_id" integer NOT NULL,
	"weight" "weight_enum" NOT NULL,
	"initial_locked_at" timestamp with time zone,
	"final_locked_at" timestamp with time zone,
	"relock_used" boolean DEFAULT false NOT NULL,
	"initial_locked_line_id" integer,
	"initial_locked_spread_team_id" integer,
	"initial_locked_spread_value" numeric,
	"final_locked_line_id" integer,
	"final_locked_spread_team_id" integer,
	"final_locked_spread_value" numeric,
	"locked_by" uuid DEFAULT auth.uid() NOT NULL,
	CONSTRAINT "picks_pkey" PRIMARY KEY("user_id","game_id")
);
--> statement-breakpoint
ALTER TABLE "picks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "weeks" ADD CONSTRAINT "weeks_season_id_fkey" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "games" ADD CONSTRAINT "games_away_team_id_fkey" FOREIGN KEY ("away_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "games" ADD CONSTRAINT "games_home_team_id_fkey" FOREIGN KEY ("home_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "games" ADD CONSTRAINT "games_week_id_fkey" FOREIGN KEY ("week_id") REFERENCES "public"."weeks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game_lines" ADD CONSTRAINT "game_lines_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game_lines" ADD CONSTRAINT "game_lines_spread_team_id_fkey" FOREIGN KEY ("spread_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "results" ADD CONSTRAINT "results_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_actor_fkey" FOREIGN KEY ("actor") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "totals" ADD CONSTRAINT "totals_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "totals" ADD CONSTRAINT "totals_week_id_fkey" FOREIGN KEY ("week_id") REFERENCES "public"."weeks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "picks" ADD CONSTRAINT "picks_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "picks" ADD CONSTRAINT "picks_picked_team_id_fkey" FOREIGN KEY ("picked_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "picks" ADD CONSTRAINT "picks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ux_game_lines_active" ON "game_lines" USING btree ("game_id" uuid_ops) WHERE (is_active_line = true);--> statement-breakpoint
CREATE VIEW "public"."picks_view" AS (SELECT p.game_id, p.user_id, u.display_name, p.weight, CASE WHEN p.picked_team_id = g.home_team_id THEN 'home'::text WHEN p.picked_team_id = g.away_team_id THEN 'away'::text ELSE NULL::text END AS picked_side, t.short_name AS picked_team, p.final_locked_at FROM picks p JOIN users u ON u.id = p.user_id JOIN games g ON g.id = p.game_id JOIN teams t ON t.id = p.picked_team_id);--> statement-breakpoint
CREATE POLICY "sel_users" ON "users" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "upd_users_self" ON "users" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "sel_games" ON "games" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "sel_game_lines" ON "game_lines" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "sel_results" ON "results" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "admin_sel_settings" ON "settings" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_admin());--> statement-breakpoint
CREATE POLICY "admin_all_settings" ON "settings" AS PERMISSIVE FOR ALL TO "authenticated";--> statement-breakpoint
CREATE POLICY "admin_sel_audit" ON "audit_log" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_admin());--> statement-breakpoint
CREATE POLICY "admin_ins_audit" ON "audit_log" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "sel_totals" ON "totals" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "sel_picks_owner_or_started" ON "picks" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((user_id = auth.uid()) OR game_has_started(game_id)));--> statement-breakpoint
CREATE POLICY "ins_picks_own_pre" ON "picks" AS PERMISSIVE FOR INSERT TO "authenticated";--> statement-breakpoint
CREATE POLICY "upd_picks_once_pre" ON "picks" AS PERMISSIVE FOR UPDATE TO "authenticated";
*/