-- USERS (profile mirror of auth.users)
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'player', -- 'player' | 'admin'
  created_at timestamptz not null default now()
);

-- SEASONS & WEEKS
create table if not exists public.seasons (
  id integer generated by default as identity primary key,
  league text not null default 'NFL',
  year int not null
);

create table if not exists public.weeks (
  id integer generated by default as identity primary key,
  season_id integer not null references public.seasons(id) on delete cascade,
  week_number int not null,
  start_ts timestamptz not null,
  end_ts   timestamptz not null
);

-- TEAMS
create table if not exists public.teams (
  id integer generated by default as identity primary key,
  league text not null default 'NFL',
  external_key text unique, -- e.g., 'PHI'
  name text not null,
  short_name text not null
);

-- GAMES
create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  week_id integer not null references public.weeks(id) on delete cascade,
  external_game_id text unique,          -- Odds API game id (optional)
  commence_time timestamptz not null,
  home_team_id integer not null references public.teams(id),
  away_team_id integer not null references public.teams(id),
  status text not null default 'scheduled', -- scheduled | in_progress | final | postponed
  final_scores jsonb                      -- {home:int, away:int}
);

-- LINES (one active line per game)
create table if not exists public.game_lines (
  id integer generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  source text not null default 'fanduel',
  spread_team_id integer not null references public.teams(id), -- team giving/taking points
  spread_value numeric not null,                               -- negative = favorite
  fetched_at timestamptz not null default now(),
  is_active_line boolean not null default false
);

-- At most one active line per game
create unique index if not exists ux_game_lines_active
on public.game_lines (game_id)
where is_active_line = true;

create table if not exists public.picks (
  user_id uuid not null references public.users(id) on delete cascade,
  game_id uuid not null references public.games(id) on delete cascade,
  picked_team_id integer not null references public.teams(id),
  weight public.weight_enum not null,
  -- final frozen snapshot at the moment of the last pre-kickoff change
  locked_at timestamptz,
  locked_line_id integer,
  locked_spread_team_id integer,
  locked_spread_value numeric,
  locked_by uuid not null default auth.uid(),
  primary key (user_id, game_id)
);

-- RESULTS & TOTALS
create table if not exists public.results (
  game_id uuid primary key references public.games(id) on delete cascade,
  winning_team_id integer,
  cover_result text, -- 'home' | 'away' | 'push'
  graded_at timestamptz not null default now()
);

create table if not exists public.totals (
  user_id uuid not null references public.users(id) on delete cascade,
  week_id integer not null references public.weeks(id) on delete cascade,
  points_delta int not null default 0,
  season_total_cached int not null default 0,
  primary key (user_id, week_id)
);

-- SETTINGS & AUDIT
create table if not exists public.settings (
  id boolean primary key default true, -- single row table
  odds_api_monthly_cap int not null default 500,
  odds_api_calls_used_current_month int not null default 0,
  reset_on date
);

create table if not exists public.audit_log (
  id integer generated by default as identity primary key,
  actor uuid references public.users(id),
  action text not null,
  details jsonb,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- cron_run_log
-- ---------------------------------------------------------------------------
create table if not exists public.cron_run_log (
  id          bigint generated always as identity primary key,
  job         text not null,
  started_at  timestamptz not null default now(),
  finished_at timestamptz,
  ok          boolean,
  summary     jsonb,
  error       text
);
alter table public.cron_run_log enable row level security;
