-- SEASONS
create table if not exists public.seasons (
  id integer generated by default as identity primary key,
  league text not null default 'NFL',
  year int not null,
  -- Imported/pre-live seasons are frozen from grading (ADR-0024). Their settlements were
  -- loaded straight from the historical Google-Sheets truth (issue #94) with NO missed-pick
  -- penalties; a later grade run would re-apply the 2025-era missed penalty and recompute
  -- picks from backfilled finals, both of which diverge from the sheet. Live grading began
  -- in 2025, so earlier seasons are locked; new (live) seasons default false. Enforced in
  -- _grade_games_by_ids, the single choke point every grade path funnels through
  -- (grade_game/week/season, the grade cron, and the #433 reconcile sweep).
  grading_locked boolean not null default false
);

-- Additive column for existing DBs (this table predates the column).
alter table public.seasons
  add column if not exists grading_locked boolean not null default false;

-- One-time backfill: lock every imported pre-2025 season. Idempotent -- a no-op on a
-- from-empty apply (seasons is empty here) and on any DB whose pre-2025 seasons are
-- already locked. Live seasons (>= 2025) stay unlocked via the column default.
update public.seasons set grading_locked = true where year < 2025 and not grading_locked;
