-- WEEKS
create table if not exists public.weeks (
  id integer generated by default as identity primary key,
  season_id integer not null references public.seasons(id) on delete cascade,
  week_number int not null,
  start_ts timestamptz not null,
  end_ts   timestamptz not null
);
