-- LINES (one active line per game)
--
-- CANONICAL LINE CONVENTION (ADR-0007; enforced since #734):
--   spread_team_id  IS THE FAVORITE.
--   spread_value    is a NON-NEGATIVE MAGNITUDE (0 = pick'em).
-- public.set_active_line normalizes to this form on every write -- handed a negative value
-- it flips the team and takes abs() -- and the check constraint below makes the invariant
-- enforceable rather than merely conventional.
--
-- Derive favorite/underdog from spread_team_id's IDENTITY, never from the sign of
-- spread_value. This column's comment read "negative = favorite" until #734; two read models
-- (league_ats_base, stats_accuracy_by_line_side) believed it and tested `spread_value < 0`,
-- which -- against data that is never negative -- labelled the underdog as the favorite on
-- every row and inverted every fav/dog surface in the app.
create table if not exists public.game_lines (
  id integer generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  source text not null default 'fanduel',
  spread_team_id integer not null references public.teams(id), -- the FAVORITE (see above)
  spread_value numeric not null,                               -- non-negative magnitude; 0 = pick'em
  fetched_at timestamptz not null default now(),
  is_active_line boolean not null default false,
  -- Flagged write-once at first grade: the last pre-kickoff line per (game, source).
  is_closing_line boolean not null default false
);

-- At most one active line per game
create unique index if not exists ux_game_lines_active
on public.game_lines (game_id)
where is_active_line = true;

-- Additive column for existing DBs; the definition above handles fresh DBs.
alter table public.game_lines
  add column if not exists is_closing_line boolean not null default false;

-- At most one closing line per (game, source)
create unique index if not exists ux_game_lines_closing
on public.game_lines (game_id, source) where is_closing_line = true;

-- The check constraint enforcing the non-negative-magnitude convention documented above
-- lives in 0234_game_lines_spread_sign.sql (#734) -- the generator allows one primary object
-- per source file, so it cannot sit here.
