/**
 * verify-src-reproduces-migrations.ts
 *
 * Drift guard for the SQL-source → migration-ledger pipeline (ADR-0011/ADR-0012).
 *
 * `pnpm db:migration:check` only validates the hash LEDGER. It never checks the thing
 * that actually matters for the planned history squash: that applying `supabase/src/**`
 * FROM EMPTY reproduces the schema the committed migration chain (= production) produces.
 * That blind spot is exactly how `src/` silently drifted from prod (see the
 * `set_active_line` reconcile). This script closes it.
 *
 * What it does:
 *   1. Schema B — build a single from-empty baseline by concatenating every `src/**`
 *      file in the generator's emission order (reused from generate-migration.ts), apply
 *      it to the local stack ALONE, and dump the resulting `public` schema.
 *   2. Schema A — apply the real migration chain (`supabase db reset --local`) and dump
 *      `public`. (Run last so the local dev DB is left in its normal, all-migrations state.)
 *   3. Normalize both dumps (strip ACL / owner / `\restrict` / SET / comment noise — the
 *      local CLI grants tables a legacy `GRANT ALL` that prod's newer CLI does not, so ACLs
 *      MUST be ignored — and sort columns within each table to ignore harmless ordinal
 *      drift) and diff them.
 *
 * Exit codes:
 *   0  src-from-empty reproduces the migration schema (the green goal — promote to a
 *      required CI gate once this holds, post-squash).
 *   1  drift detected, OR the from-empty baseline does not apply yet. On `master` this is
 *      the EXPECTED, documented state: the baseline fails to apply because RLS policies are
 *      authored inline in schema-phase files but reference functions emitted in the later
 *      functions phase (the ordering issue the squash resolves). The job that runs this is
 *      intentionally non-blocking until then.
 *   2  the real migration chain itself failed to apply — a genuine breakage.
 *
 * Runs on the local Supabase stack; the stack must already be started (mirrors
 * ci-integration.yml, which runs `supabase start` before the test step).
 */
import { spawnSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync
} from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { collectSources } from './generate-migration';

const repoRoot = process.cwd();
const migrationsDir = path.join(repoRoot, 'supabase', 'migrations');
const backupDir = path.join(repoRoot, 'supabase', '.migrations-verify-backup');
const srcRoot = path.join(repoRoot, 'supabase', 'src');
const baselineName = '00000000000000_src_from_empty_baseline.sql';

type ShellResult = { ok: boolean; stdout: string; stderr: string };

function sh(command: string): ShellResult {
  const result = spawnSync(command, {
    shell: true,
    encoding: 'utf8',
    maxBuffer: 128 * 1024 * 1024
  });
  return { ok: result.status === 0, stdout: result.stdout ?? '', stderr: result.stderr ?? '' };
}

function tail(text: string, lines = 25): string {
  return text.split(/\r?\n/).filter(Boolean).slice(-lines).join('\n');
}

function resetLocal(): ShellResult {
  return sh('supabase db reset --local --yes');
}

function dumpPublic(outFile: string): string {
  const result = sh(`supabase db dump --local -s public -f "${outFile}"`);
  if (!result.ok) {
    throw new Error(`supabase db dump failed:\n${tail(result.stderr || result.stdout)}`);
  }
  return readFileSync(outFile, 'utf8');
}

/** Concatenate every src file in the generator's emission order into one baseline script. */
function buildBaseline(): string {
  const sources = collectSources(srcRoot);
  if (sources.length === 0) throw new Error(`No SQL sources found under ${srcRoot}`);
  const header =
    '-- src-from-empty baseline generated by verify-src-reproduces-migrations.ts\n' +
    'set check_function_bodies = off;\n' +
    'set client_min_messages = warning;\n';
  const body = sources.map((source) => `\n-- file: ${source.key}\n${source.content}`).join('\n');
  return `${header}${body}\n`;
}

/**
 * Strip everything that legitimately differs between a from-empty src apply and the
 * migration chain without being real schema drift: ACL grants/revokes (the local CLI's
 * legacy table GRANT ALL differs from prod), ownership, psql meta-commands, pg_dump SET
 * preamble, and comments. Then sort the column/constraint lines inside each CREATE TABLE
 * so column ordinal position (added via late ALTERs in prod) is ignored.
 */
function normalize(sql: string): string {
  const kept: string[] = [];
  for (const rawLine of sql.replace(/\r\n?/g, '\n').split('\n')) {
    const line = rawLine.replace(/\s+$/, '');
    const trimmed = line.trim();
    if (trimmed === '') continue;
    if (trimmed.startsWith('--')) continue; // comments (incl. "Owner:" annotations)
    if (trimmed.startsWith('\\')) continue; // psql meta: \restrict \unrestrict \connect
    if (/^SET\s/i.test(trimmed)) continue; // pg_dump preamble
    if (/^SELECT\s+pg_catalog\.set_config/i.test(trimmed)) continue;
    if (/^GRANT\s/i.test(trimmed)) continue;
    if (/^REVOKE\s/i.test(trimmed)) continue;
    if (/^ALTER\s+DEFAULT\s+PRIVILEGES/i.test(trimmed)) continue;
    if (/\bOWNER\s+TO\b/i.test(trimmed)) continue; // ALTER ... OWNER TO postgres;
    kept.push(line);
  }
  return sortCreateTableColumns(kept.join('\n'));
}

function sortCreateTableColumns(sql: string): string {
  const lines = sql.split('\n');
  const out: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    out.push(lines[i]);
    if (!/^CREATE TABLE\s/i.test(lines[i])) continue;

    const interior: string[] = [];
    let j = i + 1;
    for (; j < lines.length && lines[j].trim() !== ');'; j++) interior.push(lines[j]);

    // Drop trailing commas (a function of ordinal position) before sorting.
    const sorted = interior
      .map((line) => line.replace(/,\s*$/, '').trim())
      .sort((a, b) => a.localeCompare(b));
    out.push(...sorted);
    if (j < lines.length) out.push(lines[j]); // the ');'
    i = j;
  }
  return out.join('\n');
}

function restoreMigrations(): void {
  if (!existsSync(backupDir)) return;
  rmSync(migrationsDir, { recursive: true, force: true });
  renameSync(backupDir, migrationsDir);
}

function header(title: string): void {
  console.log(`\n${'='.repeat(72)}\n${title}\n${'='.repeat(72)}`);
}

function main(): void {
  // Recover from a previously interrupted run before we touch anything.
  if (existsSync(backupDir)) {
    console.log('Found leftover migrations backup from an interrupted run — restoring it.');
    restoreMigrations();
  }

  const tmp = mkdtempSync(path.join(os.tmpdir(), 'sb-verify-'));
  let schemaB: string | null = null;
  let baselineApplyError = '';

  header('Schema B — applying src/** from empty');
  try {
    const baseline = buildBaseline();
    renameSync(migrationsDir, backupDir);
    mkdirSync(migrationsDir, { recursive: true });
    writeFileSync(path.join(migrationsDir, baselineName), baseline, 'utf8');

    const reset = resetLocal();
    if (reset.ok) {
      schemaB = dumpPublic(path.join(tmp, 'schemaB.sql'));
      console.log('src-from-empty baseline applied cleanly.');
    } else {
      baselineApplyError = tail(reset.stdout + '\n' + reset.stderr, 30);
      console.log('src-from-empty baseline did NOT apply (see diagnostic below).');
    }
  } finally {
    restoreMigrations();
  }

  header('Schema A — applying the full migration chain');
  const resetA = resetLocal();
  if (!resetA.ok) {
    console.error('The committed migration chain failed to apply — this is a real breakage:');
    console.error(tail(resetA.stdout + '\n' + resetA.stderr, 30));
    process.exit(2);
  }
  const schemaA = dumpPublic(path.join(tmp, 'schemaA.sql'));
  console.log('Migration chain applied cleanly; local DB left in its normal state.');

  header('Result');
  if (schemaB === null) {
    console.error(
      'src/** does not yet apply from empty, so it cannot be compared to the migration\n' +
        'schema. On master this is the documented structural drift (inline RLS policies in\n' +
        'schema-phase files reference functions emitted in the later functions phase). The\n' +
        'deferred ADR-0012 squash resolves it; this guard is non-blocking until then.\n\n' +
        'Baseline apply diagnostic (tail):\n' +
        baselineApplyError
    );
    process.exit(1);
  }

  const normalizedA = normalize(schemaA);
  const normalizedB = normalize(schemaB);
  if (normalizedA === normalizedB) {
    console.log(
      '✓ src/** applied from empty reproduces the migration schema (ACL/owner/\n' +
        'column-order noise ignored). Safe to promote this guard to a required CI gate.'
    );
    return;
  }

  const fileA = path.join(tmp, 'normalizedA.sql');
  const fileB = path.join(tmp, 'normalizedB.sql');
  writeFileSync(fileA, normalizedA, 'utf8');
  writeFileSync(fileB, normalizedB, 'utf8');
  console.error('✗ Drift: src-from-empty schema differs from the migration schema.');
  console.error('  (A = migration chain, B = src-from-empty; ACL/owner/column-order ignored)\n');
  const diff = sh(`git --no-pager diff --no-index --no-color "${fileA}" "${fileB}"`);
  console.error(tail(diff.stdout || diff.stderr, 200));
  process.exit(1);
}

try {
  main();
} catch (error) {
  // Never leave the real migrations directory swapped out.
  restoreMigrations();
  console.error(error instanceof Error ? error.message : error);
  process.exit(2);
}
