// Historical kickoff-time backfill — SQL generator.
//
// The 2022-2024 seasons were loaded by import-historical/generate.ts, which had
// no real kickoff times in the source spreadsheets and therefore SYNTHESIZED
// commence_time as a fake Sunday 18:00 UTC (= 2:00pm ET) for EVERY game in a week
// (see import-historical/generate.ts weekWindow()). As a result the /league
// primetime module (league_ats_primetime.sql), which classifies TNF/SNF/MNF/day
// purely from commence_time in America/New_York, buckets ALL imported games as
// 'day' — those seasons show zero primetime games, which is wrong, not just sparse.
//
// This script fetches the real kickoff time for each 2022-2024 regular-season game
// from the same ESPN scoreboard endpoint the live schedule sync uses (fetchEspnWeek,
// which #430's finals backfill already proved works for exactly these seasons), and
// emits ONE self-contained, one-off `backfill_game_times.sql` that UPDATEs
// public.games.commence_time (and, as a free re-sync attribute, schedule_game_id).
//
// It matches ESPN events to our rows on the durable game identity — week +
// unordered team pair (the uq_games_matchup key) — so a home/away disagreement
// between providers cannot cause a mismatch. It touches nothing but those two
// columns on already-final historical games: week membership is by week_id FK
// (not time), and settled picks carry their own stored locked_at, so moving
// commence_time reshuffles nothing.
//
// Usage:
//   pnpm db:backfill-game-times:generate [--out path.sql]
//
// The output is data-only and safe to re-run (idempotent UPDATE). Run it once
// against staging, verify the final report block, then production.

import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fetchEspnWeek, NFL_REGULAR_SEASON_WEEKS } from '../../../src/lib/server/schedule.ts';

const SEASONS = [2022, 2023, 2024] as const;

type KickoffRow = {
  year: number;
  week: number;
  awayKey: string; // teams.external_key (ESPN abbr, normalized by fetchEspnWeek)
  homeKey: string;
  scheduleGameId: string; // ESPN event id
  kickoff: string; // ISO 8601 UTC timestamp from ESPN event.date
};

function q(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function valuesBlock(rows: string[]): string {
  const out: string[] = [];
  const SIZE = 500;
  for (let i = 0; i < rows.length; i += SIZE) {
    out.push(rows.slice(i, i + SIZE).join(',\n'));
  }
  return out.join(',\n');
}

function buildSql(rows: KickoffRow[]): string {
  const values = valuesBlock(
    rows.map(
      (r) =>
        `  (${r.year}, ${r.week}, ${q(r.awayKey)}, ${q(r.homeKey)}, ${q(r.scheduleGameId)}, ${q(r.kickoff)}::timestamptz)`
    )
  );

  return `-- Historical kickoff-time backfill (NFL 2022-2024) -- GENERATED by
-- supabase/scripts/backfill-game-times/generate.ts. Do not edit by hand.
--
-- One-off, data-only patch. Fills the real ESPN kickoff time (and ESPN event id)
-- onto imported historical games whose commence_time was synthesized as a flat
-- Sunday 2pm ET at import time, so the /league primetime split has real
-- TNF/SNF/MNF data for these seasons. Idempotent: safe to re-run.
--
-- Run once against staging, verify the report block, then production.
--
-- ESPN games fetched: ${rows.length}

begin;

create temp table _kt (
  year int,
  week int,
  away_key text,
  home_key text,
  schedule_game_id text,
  kickoff timestamptz
) on commit drop;

insert into _kt (year, week, away_key, home_key, schedule_game_id, kickoff) values
${values};

-- Match on the durable game identity: week + unordered team pair (uq_games_matchup),
-- so provider home/away orientation is irrelevant.
update public.games gm
set commence_time = k.kickoff,
    schedule_game_id = k.schedule_game_id
from _kt k
join public.seasons s on s.league = 'NFL' and s.year = k.year
join public.weeks w on w.season_id = s.id and w.week_number = k.week
join public.teams ta on ta.external_key = k.away_key
join public.teams th on th.external_key = k.home_key
where gm.week_id = w.id
  and least(gm.home_team_id, gm.away_team_id) = least(ta.id, th.id)
  and greatest(gm.home_team_id, gm.away_team_id) = greatest(ta.id, th.id);

-- ---- Report (review before this transaction commits) ----------------------
do $$
declare
  unmatched int;
  still_synthetic int;
begin
  -- Every ESPN row that did NOT resolve to a matched game (expect 0 for a clean run).
  -- The NOT EXISTS wraps the whole season/week/team/game resolution so a team-key or
  -- missing-week failure is counted too, not silently dropped by an inner join.
  select count(*) into unmatched
  from _kt k
  where not exists (
    select 1
    from public.seasons s
    join public.weeks w on w.season_id = s.id and w.week_number = k.week
    join public.teams ta on ta.external_key = k.away_key
    join public.teams th on th.external_key = k.home_key
    join public.games gm on gm.week_id = w.id
      and least(gm.home_team_id, gm.away_team_id) = least(ta.id, th.id)
      and greatest(gm.home_team_id, gm.away_team_id) = greatest(ta.id, th.id)
    where s.league = 'NFL' and s.year = k.year
  );

  -- Our 2022-2024 games still carrying the synthetic flat time
  -- (Sunday 18:00:00 UTC exactly) after the update — i.e. rows ESPN did not cover:
  select count(*) into still_synthetic
  from public.games gm
  join public.weeks w on w.id = gm.week_id
  join public.seasons s on s.id = w.season_id and s.league = 'NFL' and s.year in (2022, 2023, 2024)
  where gm.schedule_game_id is null
    and extract(dow from gm.commence_time at time zone 'UTC') = 0
    and gm.commence_time::time = time '18:00:00';

  raise notice 'ESPN rows unmatched to a game: %', unmatched;
  raise notice 'Historical games still on synthetic time (uncovered): %', still_synthetic;
end $$;

commit;

-- Rebuild league_ats_base (and the sibling stats matviews) so the /league primetime
-- split reflects the corrected kickoff times. Runs AFTER commit and on its own: the
-- function refreshes CONCURRENTLY, which cannot execute inside a transaction block.
select public.refresh_leaderboard_stats();
`;
}

async function main() {
  const argv = process.argv.slice(2);
  const outIdx = argv.findIndex((a) => a === '--out' || a.startsWith('--out='));
  let outPath = path.join('supabase', 'scripts', 'backfill-game-times', 'backfill_game_times.sql');
  if (outIdx !== -1) {
    const a = argv[outIdx];
    outPath = a.includes('=') ? a.slice(a.indexOf('=') + 1) : argv[outIdx + 1];
  }

  const rows: KickoffRow[] = [];
  const perYear = new Map<number, number>();

  for (const year of SEASONS) {
    for (let week = 1; week <= NFL_REGULAR_SEASON_WEEKS; week++) {
      const result = await fetchEspnWeek(year, week);
      for (const g of result.games) {
        rows.push({
          year,
          week,
          awayKey: g.awayTeamAbbr,
          homeKey: g.homeTeamAbbr,
          scheduleGameId: g.scheduleGameId,
          kickoff: new Date(g.date).toISOString()
        });
      }
      perYear.set(year, (perYear.get(year) ?? 0) + result.games.length);
    }
  }

  const sql = buildSql(rows);
  writeFileSync(path.resolve(outPath), sql, 'utf8');

  console.log(`\n=== Game-time backfill generated -> ${outPath} ===`);
  console.log(`ESPN games: ${rows.length}`);
  for (const year of SEASONS) {
    console.log(`  ${year}: ${perYear.get(year) ?? 0}  (expect 272 for a full regular season)`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
