-- generated by scripts/gen-func-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;

-- signature-adjustment drops
-- drop for signature change: functions/_private/ats_margin_at_lock.sql
drop function if exists public.ats_margin_at_lock(int, int, int, int, int, numeric);

-- file: functions/_private/ats_margin_at_lock.sql
create or replace function public.ats_margin_at_lock(
  home_pts int,
  away_pts int,
  home_id  int,
  away_id  int,
  spread_team_id int,  -- the favorite
  spread_value numeric -- positive magnitude of the line (e.g. 2.5)
) returns numeric
language sql
immutable
as $$
  -- Positive result means HOME covered ATS; negative means AWAY covered; 0 = push
  select (home_pts - away_pts)
       + case
           when spread_team_id = home_id then -spread_value  -- home favorite: subtract handicap
           when spread_team_id = away_id then  spread_value  -- away favorite: give home the points
           else 0
         end
$$;

-- file: functions/grade/grade_pick.sql
create or replace function public.grade_pick(
  home_pts int,
  away_pts int,
  home_id int,
  away_id int,
  picked_team_id int,
  spread_team_id int,
  spread_value numeric,
  weight text
) returns table(points_delta int, outcome public.pick_outcome)
language sql immutable
as $$
  with m as (
    select public.ats_margin_at_lock(home_pts, away_pts, home_id, away_id, spread_team_id, spread_value) as margin,
           public.weight_points(weight) as points_value
  )
  select
    case
      when margin = 0 then 0
      when (margin > 0 and picked_team_id = home_id)
        or (margin < 0 and picked_team_id = away_id)
        then points_value
      else -points_value
    end as points_delta,
    case
      when margin = 0 then 'push'::public.pick_outcome
      when (margin > 0 and picked_team_id = home_id)
        or (margin < 0 and picked_team_id = away_id)
        then 'win'::public.pick_outcome
      else 'loss'::public.pick_outcome
    end as outcome
  from m;
$$;

-- file: functions/odds/set_active_line.sql
create or replace function public.set_active_line(
  p_game_id        uuid,
  p_spread_team_id int,
  p_spread_value   numeric,
  p_source         text default 'fanduel'
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  with deact as (
    -- Turn off any existing active line for this (game, source)
    update public.game_lines
       set is_active_line = false
     where game_id = p_game_id
       and source  = p_source
       and is_active_line = true
    returning 1
  ),
  upsert as (
    insert into public.game_lines (game_id, source, spread_team_id, spread_value, is_active_line, fetched_at)
    values (p_game_id, p_source, p_spread_team_id, p_spread_value, true, now())
    on conflict (game_id, source) where is_active_line = true
    do update set
      spread_team_id = excluded.spread_team_id,
      spread_value   = excluded.spread_value,
      fetched_at     = excluded.fetched_at,
      is_active_line = true
    returning *
  )
  select jsonb_build_object(
    'ok',          true,
    'deactivated', coalesce((select count(*) from deact), 0),
    'line',        to_jsonb(upsert.*)
  )
  from upsert;
$$;

grant execute on function public.set_active_line(uuid, int, numeric, text)
  to authenticated, service_role;
