-- generated by scripts/gen-func-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: functions/odds/set_active_line.sql
-- supabase/functions/set_active_line.sql
create or replace function public.set_active_line(
  p_game_id        uuid,
  p_spread_team_id int,
  p_spread_value   numeric,
  p_source         text default 'fanduel'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_home int;
  v_away int;
  v_fav  int;
  v_val  numeric;
begin
  -- home/away
  select home_team_id, away_team_id into v_home, v_away
  from public.games
  where id = p_game_id;

  -- normalize to (favorite, positive) form
  if p_spread_value < 0 then
    v_val := abs(p_spread_value);
    if p_spread_team_id = v_home then
      v_fav := v_away;
    else
      v_fav := v_home;
    end if;
  else
    v_val := p_spread_value;
    v_fav := p_spread_team_id;
  end if;

  -- deactivate any existing active row for this game
  update public.game_lines
     set is_active_line = false
   where game_id = p_game_id
     and is_active_line = true;

  -- insert canonical line for this game
  insert into public.game_lines (game_id, source, spread_team_id, spread_value, is_active_line, fetched_at)
  values (p_game_id, p_source, v_fav, v_val, true, now())
  return jsonb_build_object('ok', true);
end
$$;
