-- generated by scripts/gen-func-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0402_fix_active_line_uq.sql
DROP INDEX IF EXISTS ux_active_line_per_game;

-- file: functions/games/upsert_game_by_external_id.sql
create or replace function public.upsert_game_by_external_id(
  p_external_game_id text,
  p_week_id          int,
  p_commence         timestamptz,
  p_home_team_id     int,
  p_away_team_id     int
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  insert into public.games (
    week_id, external_game_id, commence_time, home_team_id, away_team_id, status
  )
  values (
    p_week_id, p_external_game_id, p_commence, p_home_team_id, p_away_team_id, 'scheduled'
  )
  on conflict on constraint uq_games_external
  do update set
    week_id       = excluded.week_id,
    commence_time = excluded.commence_time,
    home_team_id  = excluded.home_team_id,
    away_team_id  = excluded.away_team_id
  returning id into v_id;

  return v_id;
end
$$;

grant execute on function public.upsert_game_by_external_id(text,int,timestamptz,int,int)
  to authenticated, service_role;

-- file: functions/odds/set_active_line.sql
create or replace function public.set_active_line(
  p_game_id        uuid,
  p_spread_team_id int,
  p_spread_value   numeric,
  p_source         text default 'fanduel'
)
returns jsonb
language sql
security definer
as $$
  with deact as (
    -- Turn off any existing active line for this (game, source)
    update public.game_lines
       set is_active_line = false
     where game_id = p_game_id
       and source  = p_source
       and is_active_line = true
    returning 1
  ),
  upsert as (
    insert into public.game_lines (
      game_id, source, spread_team_id, spread_value, is_active_line, fetched_at
    )
    values (p_game_id, p_source, p_spread_team_id, p_spread_value, true, now())
    on conflict on constraint ux_game_lines_active_per_source
    do update set
      spread_team_id = excluded.spread_team_id,
      spread_value   = excluded.spread_value,
      fetched_at     = excluded.fetched_at,
      is_active_line = true
    returning *
  )
  select jsonb_build_object(
    'ok',          true,
    'deactivated', coalesce((select count(*) from deact), 0),
    'line',        to_jsonb(upsert.*)
  )
  from upsert;
$$;

grant execute on function public.set_active_line(uuid, int, numeric, text)
  to authenticated, service_role;
