-- generated by scripts/gen-func-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: grants/admin_grants.sql
-- =========================
-- ADMIN (JWT claim role=admin)
-- =========================
-- No separate DB role for "admin"; it's a claim checked by RLS/functions.
-- Admin-only behavior is enforced by:
--   - RLS USING/WITH CHECK (is_admin())
--   - Admin RPCs that call is_admin() and raise on non-admins

-- =========================
-- SERVICE ROLE (server-side key; bypasses RLS)
-- =========================
-- Full, explicit privileges for backend tasks and admin RPC execution.

grant usage on schema public to service_role;

grant select, insert, update, delete, truncate, references, trigger
  on all tables in schema public to service_role;

grant usage, select on all sequences in schema public to service_role;
grant execute on all functions in schema public to service_role;

-- Keep future objects service-ready
alter default privileges in schema public
  grant select, insert, update, delete, truncate, references, trigger on tables to service_role;

alter default privileges in schema public
  grant usage, select on sequences to service_role;

alter default privileges in schema public
  grant execute on functions to service_role;

-- Optional: if you prefer admin RPCs callable ONLY by backend,
-- don't grant EXECUTE to 'authenticated' for those RPCs at all.
-- Call them from your API route with the service key.

-- file: grants/anon_grants.sql
-- =========================
-- ANON (not signed in)
-- =========================

-- Schema resolve only; no data by default
grant usage on schema public to anon;

-- Don’t let anon call any RPCs by default
revoke execute on all functions in schema public from anon;
alter default privileges in schema public revoke execute on functions from anon;

-- Enums: anon doesn't need to pass these into RPCs
revoke usage on type public.weight_enum from anon;
revoke usage on type public.side_enum  from anon;

-- If you later add anon-safe read RPCs, grant EXECUTE in those function files.
-- If you add an anon RLS policy to read games/lines directly, you’ll also need:
--   grant select on public.games, public.game_lines to anon;
-- but with current RLS (authenticated-only), that grant would have no effect.

-- file: grants/player_grants.sql
-- =========================
-- PLAYER (authenticated, non-admin)
-- =========================

-- Basic resolution
grant usage on schema public to authenticated;

-- Start from zero function access for users
revoke execute on all functions in schema public from authenticated;
alter default privileges in schema public revoke execute on functions from authenticated;

-- Enums used by player RPCs
grant usage on type public.weight_enum to authenticated;
grant usage on type public.side_enum  to authenticated;

-- Base table privileges (RLS still enforces row/column rules)
grant select on public.games,
               public.game_lines,
               public.results,
               public.totals,
               public.users,
               public.weeks,
               public.seasons,
               public.teams
to authenticated;

-- Picks CRUD the player needs; RLS gates who/when
grant select, insert, update on public.picks to authenticated;

-- Settings & audit:
-- Grant SELECT so admins (who are also 'authenticated') can read via RLS (is_admin()).
-- Do NOT grant write widely; writes happen via SECURITY DEFINER admin RPCs.
grant select on public.settings, public.audit_log to authenticated;

-- NOTE: Do not grant EXECUTE here. Each RPC file should append its own:
--   - public get-only RPCs (e.g., get_active_week_games): GRANT to anon, authenticated
--   - player RPCs (lock_pick, unlock_pick): GRANT to authenticated
--   - admin RPCs: handled via service_role or guarded is_admin() (see admin_grants.sql)
