-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;

-- file: functions/grade/advance_week_if_complete.sql
create or replace function public.advance_week_if_complete()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_week       record;
  v_total_games  int;
  v_final_games  int;
  v_total_picks  int;
  v_settled_picks int;
begin
  select id, week_number into v_week
  from public.weeks
  where end_ts < now()
  order by end_ts desc
  limit 1;

  if v_week is null then
    return jsonb_build_object('ok', true, 'reason', 'no_concluded_week');
  end if;

  select
    count(*) filter (where status != 'postponed'),
    count(*) filter (where status != 'postponed' and (final_scores->>'home') is not null)
  into v_total_games, v_final_games
  from public.games
  where week_id = v_week.id;

  select count(*) into v_total_picks
  from public.picks p
  join public.games g on g.id = p.game_id
  where g.week_id = v_week.id
    and g.status != 'postponed';

  select count(*) into v_settled_picks
  from public.pick_settlement ps
  join public.games g on g.id = ps.game_id
  where g.week_id = v_week.id
    and g.status != 'postponed';

  return jsonb_build_object(
    'ok',             v_final_games = v_total_games and v_settled_picks = v_total_picks,
    'week_id',        v_week.id,
    'week_number',    v_week.week_number,
    'total_games',    v_total_games,
    'final_games',    v_final_games,
    'total_picks',    v_total_picks,
    'settled_picks',  v_settled_picks
  );
end;
$$;
