-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: views/stats_accuracy_by_team.sql
create or replace view public.stats_accuracy_by_team
with (security_invoker = on) as
select
  ps.user_id,
  u.display_name,
  s.year as season_year,
  p.picked_team_id as team_id,
  t.name as team_name,
  t.short_name as team_short_name,
  count(*)::int as decisions,
  count(*) filter (where ps.outcome = 'win')::int as wins,
  count(*) filter (where ps.outcome = 'loss')::int as losses,
  count(*) filter (where ps.outcome = 'push')::int as pushes,
  sum(ps.points_delta)::int as points,
  round(
    count(*) filter (where ps.outcome = 'win')::numeric
      / nullif(count(*) filter (where ps.outcome in ('win', 'loss')), 0),
    4
  ) as accuracy
from public.pick_settlement ps
join public.picks p on p.id = ps.pick_id
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
join public.teams t on t.id = p.picked_team_id
group by ps.user_id, u.display_name, s.year, p.picked_team_id, t.name, t.short_name;

revoke all on public.stats_accuracy_by_team from public, anon, authenticated;
grant select on public.stats_accuracy_by_team to service_role;

-- file: views/stats_accuracy_by_weight.sql
create or replace view public.stats_accuracy_by_weight
with (security_invoker = on) as
select
  ps.user_id,
  u.display_name,
  s.year as season_year,
  p.weight,
  count(*)::int as decisions,
  count(*) filter (where ps.outcome = 'win')::int as wins,
  count(*) filter (where ps.outcome = 'loss')::int as losses,
  count(*) filter (where ps.outcome = 'push')::int as pushes,
  sum(ps.points_delta)::int as points,
  round(
    count(*) filter (where ps.outcome = 'win')::numeric
      / nullif(count(*) filter (where ps.outcome in ('win', 'loss')), 0),
    4
  ) as accuracy
from public.pick_settlement ps
join public.picks p on p.id = ps.pick_id
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
group by ps.user_id, u.display_name, s.year, p.weight;

revoke all on public.stats_accuracy_by_weight from public, anon, authenticated;
grant select on public.stats_accuracy_by_weight to service_role;

-- file: views/stats_head_to_head.sql
-- One directional row per player pair and season, comparing shared-game points.
create or replace view public.stats_head_to_head
with (security_invoker = on) as
select
  left_ps.user_id,
  left_user.display_name,
  right_ps.user_id as opponent_user_id,
  right_user.display_name as opponent_display_name,
  s.year as season_year,
  count(*)::int as games_compared,
  count(*) filter (where left_ps.points_delta > right_ps.points_delta)::int as wins,
  count(*) filter (where left_ps.points_delta < right_ps.points_delta)::int as losses,
  count(*) filter (where left_ps.points_delta = right_ps.points_delta)::int as pushes,
  sum(left_ps.points_delta)::int as points,
  sum(right_ps.points_delta)::int as opponent_points
from public.pick_settlement left_ps
join public.pick_settlement right_ps
  on right_ps.game_id = left_ps.game_id
 and right_ps.user_id > left_ps.user_id
join public.games g on g.id = left_ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users left_user on left_user.id = left_ps.user_id
join public.users right_user on right_user.id = right_ps.user_id
group by
  left_ps.user_id,
  left_user.display_name,
  right_ps.user_id,
  right_user.display_name,
  s.year;

revoke all on public.stats_head_to_head from public, anon, authenticated;
grant select on public.stats_head_to_head to service_role;

-- file: views/stats_season_trend.sql
-- Weekly and cumulative season scoring, shaped for WeeklyCumulativeEntry.
create or replace view public.stats_season_trend
with (security_invoker = on) as
with week_rows as (
  select
    ps.user_id,
    u.display_name,
    s.year as season_year,
    w.week_number,
    sum(ps.points_delta)::int as week_points,
    count(*) filter (where ps.outcome = 'win')::int as week_wins,
    count(*) filter (where ps.outcome = 'loss')::int as week_losses,
    count(*) filter (where ps.outcome = 'push')::int as week_pushes,
    count(*) filter (where ps.outcome = 'missed')::int as week_missed
  from public.pick_settlement ps
  join public.games g on g.id = ps.game_id
  join public.weeks w on w.id = g.week_id
  join public.seasons s on s.id = w.season_id
  join public.users u on u.id = ps.user_id
  group by ps.user_id, u.display_name, s.year, w.week_number
), cumulative as (
  select
    week_rows.*,
    sum(week_points) over (
      partition by user_id, season_year
      order by week_number
      rows between unbounded preceding and current row
    )::int as cumulative_points
  from week_rows
)
select
  cumulative.*,
  sum(week_points) over (
    partition by user_id, season_year
  )::int as season_total,
  dense_rank() over (
    partition by season_year, week_number
    order by cumulative_points desc
  ) as cumulative_rank_this_week
from cumulative;

revoke all on public.stats_season_trend from public, anon, authenticated;
grant select on public.stats_season_trend to service_role;
