-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0220_reactions_repoint_comments.sql
-- Repoint reactions from games to comments (#689). #688 retired the game-level
-- reaction bar; reactions now attach to a specific comment (iMessage-style
-- tapbacks), making comments the social surface. The app is not in active use, so
-- this is a clean cutover — existing game-scoped reactions are truncated (no
-- backfill) rather than migrated. Base table: 0216_reactions.sql.

-- Clear game-scoped reactions before the column swap (no backfill). Truncating
-- first also lets us add comment_id NOT NULL without a default on an empty table.
truncate table public.reactions;

-- The reactions read policy references game_id, so it must be dropped before the
-- column can go. 41_policies_comments_reactions.sql recreates it against
-- comment_id in the policies phase of this same migration.
drop policy if exists sel_reactions_member_post_kickoff on public.reactions;

-- Drop the game_id target and its unique constraint / lookup index.
alter table public.reactions drop constraint if exists reactions_unique_user_game_emoji;
drop index if exists public.idx_reactions_group_game;
alter table public.reactions drop column if exists game_id;

-- Add the comment_id target: a reaction now hangs off a comment and cascades away
-- when that comment is hard-deleted.
alter table public.reactions
  add column if not exists comment_id uuid not null
    references public.comments(id) on delete cascade;

-- One reaction per emoji per user per comment per group (replaces the per-game key).
alter table public.reactions drop constraint if exists reactions_unique_user_comment_emoji;
alter table public.reactions
  add constraint reactions_unique_user_comment_emoji
    unique (group_id, user_id, comment_id, emoji);

create index if not exists idx_reactions_group_comment
  on public.reactions (group_id, comment_id);

-- file: policies/41_policies_comments_reactions.sql
-- Comments: members may post anytime; reads are gated to post-kickoff to avoid
-- revealing pick context before the game locks (mirrors the picks read gate in
-- 40_policies_picks.sql).

drop policy if exists sel_comments_member_post_kickoff on public.comments;
create policy sel_comments_member_post_kickoff
  on public.comments for select
  to authenticated
  using (
    public.is_member(group_id)
    and public.game_has_started(game_id)
    and deleted_at is null
  );

drop policy if exists ins_comments_own_member on public.comments;
create policy ins_comments_own_member
  on public.comments for insert
  to authenticated
  with check (
    public.is_member(group_id)
    and user_id = (select auth.uid())
  );

drop policy if exists del_comments_own on public.comments;
create policy del_comments_own
  on public.comments for delete
  to authenticated
  using (
    public.is_member(group_id)
    and user_id = (select auth.uid())
  );

-- Reactions (#689): a reaction now hangs off a comment, not a game. The read gate
-- mirrors the comments gate transitively — a reaction is visible only when its
-- comment is (member + post-kickoff + not soft-deleted). Toggle (insert + delete)
-- is allowed for members; insert additionally requires the target comment to live
-- in the same group, so a member cannot tag a reaction (stamped with their own
-- group_id) onto another group's comment.

drop policy if exists sel_reactions_member_post_kickoff on public.reactions;
create policy sel_reactions_member_post_kickoff
  on public.reactions for select
  to authenticated
  using (
    public.is_member(group_id)
    and exists (
      select 1
      from public.comments c
      where c.id = reactions.comment_id
        and public.game_has_started(c.game_id)
        and c.deleted_at is null
    )
  );

drop policy if exists ins_reactions_own_member on public.reactions;
create policy ins_reactions_own_member
  on public.reactions for insert
  to authenticated
  with check (
    public.is_member(group_id)
    and user_id = (select auth.uid())
    and exists (
      select 1
      from public.comments c
      where c.id = reactions.comment_id
        and c.group_id = reactions.group_id
    )
  );

drop policy if exists del_reactions_own on public.reactions;
create policy del_reactions_own
  on public.reactions for delete
  to authenticated
  using (
    public.is_member(group_id)
    and user_id = (select auth.uid())
  );
