-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0216_settings_final_week_allin.sql
alter table public.settings
  add column if not exists final_week_unlimited_allin boolean not null default true;

-- file: functions/picks/lock_pick.sql
-- file: supabase/functions/lock_pick.sql
create or replace function public.lock_pick(
  p_game_id  uuid,
  p_side     public.side_enum,
  p_weight   public.weight_enum,
  p_source   text default 'fanduel'
)
returns table (
  ok boolean,
  user_id uuid,
  game_id uuid,
  picked_side public.side_enum,
  weight public.weight_enum,
  locked_at timestamptz
)
language plpgsql
security invoker
set search_path = public
as $$
#variable_conflict use_column
declare
  v_uid     uuid := auth.uid();
  v_game    public.games%rowtype;
  v_team_id int;
  v_weeknum int;
  v_season  int;
  v_lastwk  int;
  v_final_week_allin boolean;
  v_line_id int;
  v_spread_team_id int;
  v_spread_value numeric;
  v_now     timestamptz := now();
  v_row     public.picks%rowtype;
  v_group_id uuid;
begin
  if v_uid is null then
    raise exception 'unauthorized' using errcode = 'P0001';
  end if;

  select gm.group_id into v_group_id
  from public.group_memberships gm
  where gm.user_id = v_uid
  order by gm.joined_at, gm.group_id
  limit 1;

  if v_group_id is null then
    raise exception 'group membership not found' using errcode = 'P0001';
  end if;

  if p_side not in ('home','away') then
    raise exception 'invalid side' using errcode = 'P0001';
  end if;

  -- fetch game (no FOR UPDATE to avoid RLS "not found")
  select * into v_game
  from public.games
  where id = p_game_id;

  if not found then
    raise exception 'game not found' using errcode = 'P0001';
  end if;

  -- no edits after kickoff
  if v_now >= v_game.commence_time then
    raise exception 'edits are not allowed after kickoff' using errcode = 'P0001';
  end if;

  v_team_id := case when p_side = 'home' then v_game.home_team_id else v_game.away_team_id end;

  -- All-In (A) enforcement: once per week, unless the final-week exception is enabled
  select w.week_number, w.season_id into v_weeknum, v_season
  from public.weeks w
  where w.id = v_game.week_id;

  select max(week_number) into v_lastwk
  from public.weeks
  where season_id = v_season;

  select coalesce(s.final_week_unlimited_allin, true)
    into v_final_week_allin
  from public.settings s
  where s.id = true;
  -- coalesce handles missing settings row; default preserves existing behavior
  v_final_week_allin := coalesce(v_final_week_allin, true);

  if p_weight = 'A' and not (v_weeknum = v_lastwk and v_final_week_allin) then
    if exists (
      select 1
      from public.picks p
      join public.games g2 on g2.id = p.game_id
      where p.group_id = v_group_id
        and p.user_id = v_uid
        and g2.week_id = v_game.week_id
        and p.weight = 'A'
        and p.game_id <> p_game_id
    ) then
      raise exception 'all in already used this week' using errcode = 'P0001';
    end if;
  end if;

  -- active line snapshot (required)
  select gl.id, gl.spread_team_id, gl.spread_value
    into v_line_id, v_spread_team_id, v_spread_value
  from public.game_lines gl
  where gl.game_id = v_game.id
    and gl.source  = p_source
    and gl.is_active_line = true
  order by gl.fetched_at desc, gl.id desc
  limit 1;

  if not found then
    raise exception 'no active line for game % (source=%)', p_game_id, p_source using errcode = 'P0001';
  end if;

  -- upsert with snapshot stamped atomically
  with upsert as (
    insert into public.picks (
      group_id, user_id, game_id, picked_team_id, weight,
      locked_at, locked_by, locked_line_id, locked_spread_team_id, locked_spread_value
    )
    values (
      v_group_id, v_uid, v_game.id, v_team_id, p_weight,
      v_now, v_uid, v_line_id, v_spread_team_id, v_spread_value
    )
    on conflict (group_id, user_id, game_id) do update
      set picked_team_id         = excluded.picked_team_id,
          weight                 = excluded.weight,
          locked_at              = excluded.locked_at,
          locked_by              = excluded.locked_by,
          locked_line_id         = excluded.locked_line_id,
          locked_spread_team_id  = excluded.locked_spread_team_id,
          locked_spread_value    = excluded.locked_spread_value
    returning *
  )
  select * into v_row from upsert;

  return query
  select
    true as ok,
    v_row.user_id,
    v_row.game_id,
    p_side as picked_side,
    v_row.weight,
    v_row.locked_at;
end
$$;

-- make sure the signature matches exactly (schema-qualify enums)
grant execute on function public.lock_pick(uuid, public.side_enum, public.weight_enum, text)
  to authenticated, service_role;
