-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;



-- file: functions/_private/settlement_owed.sql
-- _settlement_owed: does grading owe ANY pick_settlement row for this game?
--
-- The negative space of the participation boundary (ADR-0037, #724). The completeness
-- surfaces -- find_unsettled_weeks() (#433) and advance_week_if_complete() (#658) -- both
-- define "unsettled" as "this game is final but has ZERO pick_settlement rows". That
-- predicate silently assumed grading always owes at least one row per game, which was true
-- before ADR-0037 bounded the missed-pass in time: every active member of every league was
-- penalizable for every game, so any final game acquired rows.
--
-- With the boundary in force a game can legitimately owe NOTHING: a league created in week
-- 10, or a league whose only members joined later, has no eligible (member, game) pair for
-- the earlier weeks. _grade_games_by_ids correctly writes no row for such a game -- so the
-- zero-row test flags it forever. The reconcile sweep would re-fire on every tick against a
-- week it can never heal, and advance_week_if_complete would never report that week complete
-- (which in turn keeps the grade cron's #744 settled-prior-week gate from ever releasing it).
--
-- So both callers gain this predicate: a final game is only "unsettled" if a row is actually
-- owed. Owed means either
--   (a) some ACTIVE membership anywhere is eligible for it -- the missed-pass population,
--       gated by the same public._participation_start the grading choke point uses; or
--   (b) a real pick exists on it -- pass (1) of _grade_games_by_ids grades real picks with
--       no boundary gate (ADR-0037 ruling 2), so a pick from a since-removed member still
--       produces a row and must still be swept for.
--
-- Deliberately group-agnostic: both callers are global (cross-league) and only ask whether
-- the GAME is stranded, not which league stranded it.
--
-- SECURITY DEFINER for the same reason as _participation_start: the answer is a grading fact
-- and must not vary with the caller's RLS view of group_memberships/picks. Born closed to
-- anon/authenticated by the _close_new_fn_acl event trigger (ADR-0011); internal helper,
-- never a client RPC.
create or replace function public._settlement_owed(p_game_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    exists (
      select 1
      from public.games g
      cross join public.group_memberships gm
      where g.id = p_game_id
        and gm.status = 'active'
        and g.commence_time >= public._participation_start(gm.group_id, gm.user_id)
    )
    or exists (
      select 1
      from public.picks p
      where p.game_id = p_game_id
    );
$$;

comment on function public._settlement_owed(uuid) is
  'ADR-0037 / #724: true when grading owes at least one pick_settlement row for this game -- some active membership is eligible under _participation_start, or a real pick exists. The completeness surfaces (find_unsettled_weeks, advance_week_if_complete) use it so a game no league was participating in is not flagged as permanently unsettled.';

-- file: functions/grade/advance_week_if_complete.sql
create or replace function public.advance_week_if_complete()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_week                  record;
  v_total_games            int;
  v_final_games            int;
  v_unsettled_final_games  int;
begin
  select id, week_number into v_week
  from public.weeks
  where end_ts < now()
  order by end_ts desc
  limit 1;

  if v_week is null then
    return jsonb_build_object('ok', true, 'reason', 'no_concluded_week');
  end if;

  select
    count(*) filter (where status != 'postponed'),
    count(*) filter (where status != 'postponed' and (final_scores->>'home') is not null)
  into v_total_games, v_final_games
  from public.games
  where week_id = v_week.id;

  -- Completeness = every final game has been graded, i.e. has at least one
  -- pick_settlement row. Mirrors find_unsettled_weeks' predicate. Deliberately
  -- NOT a count comparison against public.picks: pick_settlement also carries
  -- synthetic "missed" rows for every active member who didn't pick a game (see
  -- _grade_games_by_ids), so settled rows almost always outnumber real picks
  -- and a raw count-equality check can never be satisfied once anyone misses.
  --
  -- _settlement_owed() carries the boundary half of that mirror (ADR-0037, #724): under the
  -- participation boundary a game can legitimately owe zero rows (a league created after it
  -- was played), and without this guard such a week could never report complete -- which
  -- would strand the grade cron's #744 settled-prior-week gate on it forever.
  select count(*) into v_unsettled_final_games
  from public.games g
  where g.week_id = v_week.id
    and g.status != 'postponed'
    and (g.final_scores->>'home') is not null
    and public._settlement_owed(g.id)
    and not exists (
      select 1 from public.pick_settlement ps where ps.game_id = g.id
    );

  return jsonb_build_object(
    'ok',                     v_final_games = v_total_games and v_unsettled_final_games = 0,
    'week_id',                v_week.id,
    'week_number',            v_week.week_number,
    'total_games',            v_total_games,
    'final_games',            v_final_games,
    'unsettled_final_games',  v_unsettled_final_games
  );
end;
$$;

-- file: functions/grade/find_unsettled_weeks.sql
-- Reconcile sweep (#433): find weeks that have final scores but were never settled.
--
-- The grade cron normally only processes the active + most-recently-concluded week
-- (findRecentGradableWeeks), so a week missed during that window is stranded forever
-- even once its finals are present. This function is the predicate the cron uses to
-- self-heal those weeks: it returns every week that has at least one game with a final
-- score for which NO pick_settlement row exists yet.
--
-- The predicate is deliberately "finals-present-but-unsettled", not merely
-- "finals-present": once a week is graded, every one of its final games has settlement
-- rows (real picks + membership-scoped missed penalties, see _grade_games_by_ids), so a
-- healthy already-settled week is NOT returned. That makes the sweep a true no-op on
-- every tick after the week heals, instead of re-firing on every graded week.
--
-- Frozen (grading_locked, ADR-0024) seasons are excluded: their settlements come from
-- the sheet import and are never re-derived, and _grade_games_by_ids is a no-op on them,
-- so a locked-season game with finals-but-no-settlement (e.g. a canceled game) could
-- never be healed and would re-fire forever. Excluding them here keeps the sweep
-- idempotent.
--
-- Games nobody is participating in are excluded for exactly the same "can never be healed"
-- reason (ADR-0037, #724). The participation boundary means a game that starts before every
-- league's competition start / every member's join legitimately owes ZERO settlement rows,
-- so the finals-present-but-unsettled test above would flag it on every tick forever.
-- _settlement_owed() is the guard: it asks whether grading owes a row at all, using the
-- same public._participation_start the grading choke point does, so the sweep and grading
-- can never disagree about what is still outstanding.
--
-- SECURITY DEFINER + service-role-only (like the grade_* functions): this reads across
-- all groups' pick_settlement rows and is only ever called by the grade cron.
create or replace function public.find_unsettled_weeks()
returns table(id int)
language sql
security definer
stable
set search_path = public
as $$
  select distinct w.id
  from public.weeks w
  join public.seasons s on s.id = w.season_id
  join public.games g on g.week_id = w.id
  where not s.grading_locked
    and (g.final_scores->>'home') is not null
    and public._settlement_owed(g.id)
    and not exists (
      select 1
      from public.pick_settlement ps
      where ps.game_id = g.id
    );
$$;

-- file: functions/picks/picks_status_board.sql
-- file: supabase/functions/picks_status_board.sql
--
-- ADR-0019 Decision point 6 (counts-only status carve-out): the group-visible
-- "who's picked" status board.
--
-- Returns, per ACTIVE member of one group for one week, how many games that member
-- has locked a pick on versus how many games the week has (e.g. 9/13) plus a
-- completion flag -- COUNTS ONLY. No game identity, side, team, or weight is exposed,
-- so nothing about *what* anyone picked is derivable pre-kickoff. This is metadata
-- about *whether* someone picked, which ADR-0019 explicitly carves out of the
-- sealed-envelope reveal.
--
-- Why a SECURITY DEFINER function and not a security_invoker view: base-table picks
-- RLS (sel_picks_owner_or_started) hides a co-member's picks until each game starts,
-- so under the caller's own RLS every co-member's pre-kickoff count would read as
-- zero -- the opposite of this board's purpose. This function instead bypasses
-- base-table RLS to count, then re-imposes an is_member() membership gate and exposes
-- no pick-level column. It grants no ability to read any *pick* the caller couldn't
-- already read -- only the aggregate count. Same mechanism and safety argument as
-- all_in_declarations (ADR-0023); the sel_picks_owner_or_started guarantee for pick
-- content stays structurally intact.
--
-- is_member(p_group_id) keys off auth.uid() (unaffected by SECURITY DEFINER), so a
-- non-member caller receives zero rows.
--
-- REMAINING-ONLY denominator: games_available counts only games still open to pick
-- (now() < commence_time), and picks_made counts each member's locks on those same
-- still-open games. A game that has kicked off drops out of both sides whether it was
-- picked or missed, so the board reads as "of the games still open, how many you've
-- locked" — it never leaves a member stuck at 12/13 for a game they missed. Once every
-- game has started the slate is 0/0 and everyone is trivially complete (nothing left to
-- wait on).
--
-- PER-MEMBER denominator (ADR-0037, #724): the slate is scoped to each member's
-- participation boundary, public._participation_start(group, member), so a member is never
-- shown as owing a game that starts before their participation begins. This is the read-side
-- twin of the boundary the grading choke point carries — the board enumerates membership x
-- games itself rather than reading pick_settlement, so it does not inherit that correctness.
-- The still-open filter already neutralises the joined_at term (a member cannot join after a
-- game that has not kicked off yet), so in practice the binding term here is the league's
-- competition_starts_at: a league that starts next week must not read as 0/13 behind on this
-- week's slate. Calling the shared helper rather than re-deriving greatest(...) keeps this
-- board and grading from ever disagreeing about who owed a pick.
create or replace function public.picks_status_board(
  p_group_id uuid,
  p_week_id  integer
)
returns table (
  group_id uuid,
  user_id uuid,
  display_name text,
  avatar_key text,
  picks_made integer,
  games_available integer,
  is_complete boolean
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with members as (
    select
      gm.user_id,
      u.display_name,
      u.avatar_key,
      public._participation_start(p_group_id, gm.user_id) as participation_start
    from public.group_memberships gm
    join public.users u on u.id = gm.user_id
    where gm.group_id = p_group_id
      and gm.status = 'active'
  ),
  open_games as (
    select g.id, g.commence_time
    from public.games g
    where g.week_id = p_week_id
      and now() < g.commence_time
  ),
  member_slate as (
    select m.user_id, count(og.id)::integer as games_available
    from members m
    left join open_games og on og.commence_time >= m.participation_start
    group by m.user_id
  ),
  member_counts as (
    select p.user_id, count(*)::integer as picks_made
    from public.picks p
    join open_games og on og.id = p.game_id
    join members m on m.user_id = p.user_id
    where p.group_id = p_group_id
      and og.commence_time >= m.participation_start
    group by p.user_id
  )
  select
    p_group_id as group_id,
    m.user_id,
    m.display_name,
    m.avatar_key,
    coalesce(mc.picks_made, 0) as picks_made,
    ms.games_available,
    (coalesce(mc.picks_made, 0) >= ms.games_available) as is_complete
  from members m
  join member_slate ms on ms.user_id = m.user_id
  left join member_counts mc on mc.user_id = m.user_id
  where public.is_member(p_group_id);
$$;

comment on function public.picks_status_board(uuid, integer) is
  'ADR-0019 counts-only status board: per active group member for a week, picks_made / games_available / is_complete over games STILL OPEN to pick (now() < commence_time) — remaining picks, not missed or already-started games. The slate is PER MEMBER, scoped by _participation_start (ADR-0037): a member never owes a game that starts before their participation begins. Counts only, no side/team/weight/game. SECURITY DEFINER + is_member() gate; base-table picks RLS is untouched so no pick content is revealed pre-kickoff. See docs/adr/0019-pick-reveal-timing-model.md.';

-- Closed-by-default (ADR-0011): the baseline revokes EXECUTE from PUBLIC; this
-- read-only RPC self-grants in its own source file, per house convention
-- (cf. all_in_declarations.sql, unlock_pick.sql, set_active_line.sql).
revoke all on function public.picks_status_board(uuid, integer) from public, anon;
grant execute on function public.picks_status_board(uuid, integer) to authenticated, service_role;
