-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: views/leaderboard_season_totals.sql
-- One row per user per (group, season) with totals + ranks
create or replace view public.leaderboard_season_totals as
with season_rows as (
select
ps.user_id,
u.display_name,
s.year as season_year,
ps.points_delta,
ps.outcome,
ps.group_id
from public.pick_settlement ps
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
)
, totals as (
select
user_id,
display_name,
season_year,
sum(points_delta)::int as total_points,
count(*)::int as decisions,
count(*) filter (where outcome = 'win')::int as wins,
count(*) filter (where outcome = 'loss')::int as losses,
count(*) filter (where outcome = 'push')::int as pushes,
count(*) filter (where outcome = 'missed')::int as missed,
group_id
from season_rows
group by user_id, display_name, season_year, group_id
)
select
t.user_id,
t.display_name,
t.season_year,
t.total_points,
t.decisions,
t.wins,
t.losses,
t.pushes,
t.missed,
dense_rank() over (
partition by group_id, season_year
order by total_points desc, wins desc, pushes desc
) as rank,
t.group_id
from totals t;

-- file: views/leaderboard_weekly_cumulative.sql
-- One row per user per (group, season, week) with week points and running total
create or replace view public.leaderboard_weekly_cumulative as
with week_rows as (
  select
    ps.user_id,
    u.display_name,
    s.year as season_year,
    w.week_number,
    sum(ps.points_delta)::int as week_points,
    count(*) filter (where ps.outcome = 'win')::int   as week_wins,
    count(*) filter (where ps.outcome = 'loss')::int  as week_losses,
    count(*) filter (where ps.outcome = 'push')::int  as week_pushes,
    count(*) filter (where ps.outcome = 'missed')::int as week_missed,
    ps.group_id
  from public.pick_settlement ps
  join public.games   g on g.id = ps.game_id
  join public.weeks   w on w.id = g.week_id
  join public.seasons s on s.id = w.season_id
  join public.users   u on u.id = ps.user_id
  group by ps.user_id, u.display_name, s.year, w.week_number, ps.group_id
),
cum as (
  select
    user_id,
    display_name,
    season_year,
    week_number,
    week_points,
    week_wins,
    week_losses,
    week_pushes,
    week_missed,
    -- running total per (group, user, season) ordered by week
    sum(week_points) over (
      partition by group_id, user_id, season_year
      order by week_number
      rows between unbounded preceding and current row
    )::int as cumulative_points,
    group_id
  from week_rows
)
select
  cum.user_id,
  cum.display_name,
  cum.season_year,
  cum.week_number,
  cum.week_points,
  cum.week_wins,
  cum.week_losses,
  cum.week_pushes,
  cum.week_missed,
  cum.cumulative_points,
  -- season total per (group, user, season)
  sum(cum.week_points) over (
    partition by cum.group_id, cum.user_id, cum.season_year
  )::int as season_total,
  dense_rank() over (
    partition by cum.group_id, cum.season_year, cum.week_number
    order by cum.cumulative_points desc
  ) as cumulative_rank_this_week,
  cum.group_id
from cum;

-- file: views/picks_status_view_admin.sql
create or replace view public.picks_status_view_admin
with (security_invoker = on) as
select
  p.game_id,
  g.week_id,
  p.user_id,
  u.display_name as user_display_name,
  p.weight,
  (case
     when p.picked_team_id = g.home_team_id then 'home'
     when p.picked_team_id = g.away_team_id then 'away'
   end)::public.side_enum as picked_side,
  p.picked_team_id,
  t.short_name as picked_team_short,
  p.locked_spread_value as locked_spread_value,
  p.locked_spread_team_id as locked_spread_team_id,
  p.locked_at,
  g.commence_time,
  (g.commence_time <= now()) as game_started,
  p.group_id
from public.picks p
join public.users u  on u.id = p.user_id
join public.games g  on g.id = p.game_id
join public.teams t  on t.id = p.picked_team_id;

revoke all on public.picks_status_view_admin from public;
grant select on public.picks_status_view_admin to service_role;

-- file: views/picks_status_view_user.sql
create or replace view public.picks_status_view_user
with (security_invoker = on) as
select
  p.game_id,
  g.week_id,
  p.user_id,
  p.weight,
  (case
     when p.picked_team_id = g.home_team_id then 'home'
     when p.picked_team_id = g.away_team_id then 'away'
   end)::public.side_enum as picked_side,
  p.picked_team_id,
  t.short_name as picked_team_short,
  p.locked_spread_value as locked_spread_value,
  p.locked_spread_team_id,
  p.locked_at,
  g.commence_time,
  (g.commence_time <= now()) as game_started,
  p.group_id
from public.picks p
join public.games g on g.id = p.game_id
join public.teams t on t.id = p.picked_team_id
where p.user_id = auth.uid();

revoke all on public.picks_status_view_user from public, anon;
grant select on public.picks_status_view_user to authenticated;

-- file: views/stats_accuracy_by_team.sql
create or replace view public.stats_accuracy_by_team
with (security_invoker = on) as
select
  ps.user_id,
  u.display_name,
  s.year as season_year,
  p.picked_team_id as team_id,
  t.name as team_name,
  t.short_name as team_short_name,
  count(*)::int as decisions,
  count(*) filter (where ps.outcome = 'win')::int as wins,
  count(*) filter (where ps.outcome = 'loss')::int as losses,
  count(*) filter (where ps.outcome = 'push')::int as pushes,
  sum(ps.points_delta)::int as points,
  round(
    count(*) filter (where ps.outcome = 'win')::numeric
      / nullif(count(*) filter (where ps.outcome in ('win', 'loss')), 0),
    4
  ) as accuracy,
  ps.group_id
from public.pick_settlement ps
join public.picks p on p.id = ps.pick_id
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
join public.teams t on t.id = p.picked_team_id
group by ps.user_id, u.display_name, s.year, p.picked_team_id, t.name, t.short_name, ps.group_id;

revoke all on public.stats_accuracy_by_team from public, anon, authenticated;
grant select on public.stats_accuracy_by_team to service_role;

-- file: views/stats_accuracy_by_weight.sql
create or replace view public.stats_accuracy_by_weight
with (security_invoker = on) as
select
  ps.user_id,
  u.display_name,
  s.year as season_year,
  p.weight,
  count(*)::int as decisions,
  count(*) filter (where ps.outcome = 'win')::int as wins,
  count(*) filter (where ps.outcome = 'loss')::int as losses,
  count(*) filter (where ps.outcome = 'push')::int as pushes,
  sum(ps.points_delta)::int as points,
  round(
    count(*) filter (where ps.outcome = 'win')::numeric
      / nullif(count(*) filter (where ps.outcome in ('win', 'loss')), 0),
    4
  ) as accuracy,
  ps.group_id
from public.pick_settlement ps
join public.picks p on p.id = ps.pick_id
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
group by ps.user_id, u.display_name, s.year, p.weight, ps.group_id;

revoke all on public.stats_accuracy_by_weight from public, anon, authenticated;
grant select on public.stats_accuracy_by_weight to service_role;

-- file: views/stats_head_to_head.sql
-- One directional row per player pair per (group, season), comparing shared-game points.
create or replace view public.stats_head_to_head
with (security_invoker = on) as
select
  left_ps.user_id,
  left_user.display_name,
  right_ps.user_id as opponent_user_id,
  right_user.display_name as opponent_display_name,
  s.year as season_year,
  count(*)::int as games_compared,
  count(*) filter (where left_ps.points_delta > right_ps.points_delta)::int as wins,
  count(*) filter (where left_ps.points_delta < right_ps.points_delta)::int as losses,
  count(*) filter (where left_ps.points_delta = right_ps.points_delta)::int as pushes,
  sum(left_ps.points_delta)::int as points,
  sum(right_ps.points_delta)::int as opponent_points,
  left_ps.group_id
from public.pick_settlement left_ps
join public.pick_settlement right_ps
  on right_ps.game_id = left_ps.game_id
 and right_ps.group_id = left_ps.group_id
 and right_ps.user_id > left_ps.user_id
join public.games g on g.id = left_ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users left_user on left_user.id = left_ps.user_id
join public.users right_user on right_user.id = right_ps.user_id
group by
  left_ps.user_id,
  left_user.display_name,
  right_ps.user_id,
  right_user.display_name,
  s.year,
  left_ps.group_id;

revoke all on public.stats_head_to_head from public, anon, authenticated;
grant select on public.stats_head_to_head to service_role;

-- file: views/stats_season_trend.sql
-- Weekly and cumulative season scoring per group, shaped for WeeklyCumulativeEntry.
create or replace view public.stats_season_trend
with (security_invoker = on) as
with week_rows as (
  select
    ps.user_id,
    u.display_name,
    s.year as season_year,
    w.week_number,
    sum(ps.points_delta)::int as week_points,
    count(*) filter (where ps.outcome = 'win')::int as week_wins,
    count(*) filter (where ps.outcome = 'loss')::int as week_losses,
    count(*) filter (where ps.outcome = 'push')::int as week_pushes,
    count(*) filter (where ps.outcome = 'missed')::int as week_missed,
    ps.group_id
  from public.pick_settlement ps
  join public.games g on g.id = ps.game_id
  join public.weeks w on w.id = g.week_id
  join public.seasons s on s.id = w.season_id
  join public.users u on u.id = ps.user_id
  group by ps.user_id, u.display_name, s.year, w.week_number, ps.group_id
), cumulative as (
  select
    user_id,
    display_name,
    season_year,
    week_number,
    week_points,
    week_wins,
    week_losses,
    week_pushes,
    week_missed,
    sum(week_points) over (
      partition by group_id, user_id, season_year
      order by week_number
      rows between unbounded preceding and current row
    )::int as cumulative_points,
    group_id
  from week_rows
)
select
  cumulative.user_id,
  cumulative.display_name,
  cumulative.season_year,
  cumulative.week_number,
  cumulative.week_points,
  cumulative.week_wins,
  cumulative.week_losses,
  cumulative.week_pushes,
  cumulative.week_missed,
  cumulative.cumulative_points,
  sum(cumulative.week_points) over (
    partition by cumulative.group_id, cumulative.user_id, cumulative.season_year
  )::int as season_total,
  dense_rank() over (
    partition by cumulative.group_id, cumulative.season_year, cumulative.week_number
    order by cumulative.cumulative_points desc
  ) as cumulative_rank_this_week,
  cumulative.group_id
from cumulative;

revoke all on public.stats_season_trend from public, anon, authenticated;
grant select on public.stats_season_trend to service_role;
