-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: views/league_ats_base.sql
-- League-wide, spreads-only NFL team ATS facts at the atomic (game, team-perspective)
-- grain: exactly two rows per qualifying game (one for the home team, one for the away
-- team). Every /league aggregate view and the pick-card ATS nugget (issue #406) derive
-- from THIS matview, so the tab and the nugget can never compute cover math two different
-- ways. League-wide and identical for every user: no group_id, no per-user data.
--
-- Line used = the game's closing line where one exists (is_closing_line, written once at
-- first grade by _capture_closing_line), falling back to the current active line
-- (is_active_line). Historical 2022-24 imports were settled directly and never went
-- through the grading path, so they carry only a single active-line snapshot and no
-- closing flag -- the fallback is what lets those seasons appear at all. 'fanduel' (the
-- default line_source used by grading's coalesce(cfg.line_source,'fanduel')) is preferred
-- when a game has lines from more than one book, so the whole surface reads one book.
--
-- Cover math reuses public.ats_margin_at_lock (the same formula grade_pick uses): margin
-- is home-relative (>0 home covered, <0 away covered, =0 push), so each perspective row
-- flips the sign. is_favorite is read off the sign of the closing spread (NULL for a
-- pick'em, spread_value = 0). Only is_scoring weeks (ADR-0016) with BOTH final scores and
-- a usable line are included; games missing a score or a line are dropped (the "~17%
-- missing scores" in older imports render as thinner samples, surfaced via the n= caveat
-- in the UI). ats_margin_at_lock predates this file in supabase/src and always exists in
-- the DB before this view is created (baseline migration), so the view resolves it even
-- though functions emit after views.
--
-- Materialized (ADR-0013): refreshed by public.refresh_leaderboard_stats() at the end of a
-- grading run; the unique index below lets that refresh run CONCURRENTLY. Matviews cannot
-- carry RLS, so all reads are service-role-only (the server reads via the service key; the
-- data is league-wide public context with no cross-group/-user dimension to isolate).
-- DROP ... CASCADE (not DROP VIEW): #406 made this a matview, and the three league_ats_*
-- aggregate views select from it (a hard pg_depend edge), so re-emitting this file drops
-- them too -- every migration that re-emits this file must also re-touch
-- league_ats_team.sql / league_ats_fav_dog.sql / league_ats_home_away.sql so the generator
-- bundles their recreates into the same migration (same rule as league_completed_standings).
drop materialized view if exists public.league_ats_base cascade;

create materialized view public.league_ats_base as
with scored as (
  select
    s.year as season_year,
    w.week_number,
    g.id as game_id,
    g.home_team_id,
    g.away_team_id,
    (g.final_scores ->> 'home')::int as home_pts,
    (g.final_scores ->> 'away')::int as away_pts,
    cl.spread_team_id,
    cl.spread_value,
    public.ats_margin_at_lock(
      (g.final_scores ->> 'home')::int,
      (g.final_scores ->> 'away')::int,
      g.home_team_id,
      g.away_team_id,
      cl.spread_team_id,
      cl.spread_value
    ) as margin
  from public.games g
  join public.weeks w on w.id = g.week_id
  join public.seasons s on s.id = w.season_id
  -- One line per game: closing where present, else the active snapshot; fanduel-first.
  -- CROSS JOIN LATERAL drops games with no usable line, satisfying "no line -> excluded".
  cross join lateral (
    select gl.spread_team_id, gl.spread_value
    from public.game_lines gl
    where gl.game_id = g.id
      and (gl.is_closing_line or gl.is_active_line)
    order by (gl.source = 'fanduel') desc, gl.is_closing_line desc, gl.fetched_at desc
    limit 1
  ) cl
  where w.is_scoring
    and (g.final_scores ->> 'home') is not null
    and (g.final_scores ->> 'away') is not null
)
select
  sc.season_year,
  sc.week_number,
  sc.game_id,
  persp.team_id,
  persp.is_home,
  -- Favored per the closing spread: spread_value < 0 favors spread_team_id, so this team
  -- is favored when it IS the spread team on a negative line, or the OTHER team on a
  -- positive line. NULL on a pick'em (spread_value = 0) so it is excluded from fav/dog
  -- splits but still counted in overall and home/away splits.
  case
    when sc.spread_value = 0 then null
    when persp.team_id = sc.spread_team_id then sc.spread_value < 0
    else sc.spread_value > 0
  end as is_favorite,
  -- Did THIS team cover? margin is home-relative, so the away perspective flips the sign.
  case
    when sc.margin = 0 then 'push'
    when (persp.is_home and sc.margin > 0) or (not persp.is_home and sc.margin < 0) then 'win'
    else 'loss'
  end as ats_result,
  -- Straight-up (moneyline) result for this team. NFL ties count as a push.
  case
    when sc.home_pts = sc.away_pts then 'push'
    when (persp.is_home and sc.home_pts > sc.away_pts)
      or (not persp.is_home and sc.away_pts > sc.home_pts) then 'win'
    else 'loss'
  end as su_result
from scored sc
cross join lateral (
  values
    (sc.home_team_id, true),
    (sc.away_team_id, false)
) as persp(team_id, is_home);

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the (season_year, team_id)
-- read filters used by the /league aggregates and the per-game nugget lookup.
create unique index if not exists uq_league_ats_base
  on public.league_ats_base (game_id, team_id);

-- Season/team read filters (the aggregate views group by these; PostgREST filters on them).
create index if not exists ix_league_ats_base_season_team
  on public.league_ats_base (season_year, team_id);

revoke all on public.league_ats_base from public, anon, authenticated;
grant select on public.league_ats_base to service_role;

-- file: views/league_ats_fav_dog.sql
-- Favorite vs. underdog ATS cover counts for the /league fav/dog module (issue #406), at
-- (season_year, week_number) grain so the UI can show both a per-week breakdown and a
-- season aggregate (summed in the read model). Restricted to the favorite-perspective row
-- of each game (is_favorite = true), which is exactly one row per game that has a favorite,
-- so favorite_covers + underdog_covers + pushes = games. Pick'em games (spread_value = 0,
-- is_favorite NULL) have no favorite and are excluded. Cover percentages are derived in the
-- read model (favorite_covers / (favorite_covers + underdog_covers), pushes excluded).
--
-- A plain view over the league_ats_base matview (no duplicated aggregation). Service-role
-- only, matching the base grant; carries no RLS. Selecting from a matview is a hard
-- pg_depend dependency, so `drop materialized view league_ats_base cascade` also drops this
-- view -- re-touch this file in every migration that re-emits league_ats_base.sql (same
-- rule as league_completed_standings).
create or replace view public.league_ats_fav_dog as
select
  b.season_year,
  b.week_number,
  count(*)::int as games,
  count(*) filter (where b.ats_result = 'win')::int as favorite_covers,
  count(*) filter (where b.ats_result = 'loss')::int as underdog_covers,
  count(*) filter (where b.ats_result = 'push')::int as pushes
from public.league_ats_base b
where b.is_favorite = true
group by b.season_year, b.week_number;

revoke all on public.league_ats_fav_dog from public, anon, authenticated;
grant select on public.league_ats_fav_dog to service_role;

-- file: views/league_ats_home_away.sql
-- League-wide home vs. away ATS and straight-up (SU) cover counts for the /league
-- home/away module (issue #406), one row per season_year. Home and away rows are mirror
-- images (each game contributes one of each), so home_games = away_games and home ATS
-- covers are the complement of away ATS covers (pushes aside) -- both sides are surfaced
-- because the module compares them directly. Cover percentages are derived in the read
-- model from these raw counts (covers / (covers + losses), pushes excluded).
--
-- A plain view over the league_ats_base matview (no duplicated aggregation). Service-role
-- only, matching the base grant; carries no RLS. Selecting from a matview is a hard
-- pg_depend dependency, so `drop materialized view league_ats_base cascade` also drops this
-- view -- re-touch this file in every migration that re-emits league_ats_base.sql (same
-- rule as league_completed_standings).
create or replace view public.league_ats_home_away as
select
  b.season_year,
  count(*) filter (where b.is_home)::int as home_games,
  count(*) filter (where b.is_home and b.ats_result = 'win')::int as home_ats_covers,
  count(*) filter (where b.is_home and b.ats_result = 'loss')::int as home_ats_losses,
  count(*) filter (where b.is_home and b.ats_result = 'push')::int as home_ats_pushes,
  count(*) filter (where b.is_home and b.su_result = 'win')::int as home_su_wins,
  count(*) filter (where b.is_home and b.su_result = 'loss')::int as home_su_losses,
  count(*) filter (where b.is_home and b.su_result = 'push')::int as home_su_pushes,
  count(*) filter (where not b.is_home)::int as away_games,
  count(*) filter (where not b.is_home and b.ats_result = 'win')::int as away_ats_covers,
  count(*) filter (where not b.is_home and b.ats_result = 'loss')::int as away_ats_losses,
  count(*) filter (where not b.is_home and b.ats_result = 'push')::int as away_ats_pushes,
  count(*) filter (where not b.is_home and b.su_result = 'win')::int as away_su_wins,
  count(*) filter (where not b.is_home and b.su_result = 'loss')::int as away_su_losses,
  count(*) filter (where not b.is_home and b.su_result = 'push')::int as away_su_pushes
from public.league_ats_base b
group by b.season_year;

revoke all on public.league_ats_home_away from public, anon, authenticated;
grant select on public.league_ats_home_away to service_role;

-- file: views/league_ats_team.sql
-- Per-team, per-season ATS record for the /league per-team table (issue #406): one row
-- per (season_year, team_id) with the overall ATS and straight-up (SU) record plus
-- home/away and favorite/underdog ATS splits. Cover percentages are computed in the read
-- model from these raw counts (wins / (wins + losses), pushes excluded) so the rounding
-- rule lives in one place.
--
-- A plain view over the league_ats_base matview (no aggregation logic is duplicated across
-- the /league surfaces -- they all read base). Reads a service_role-only matview, so it
-- matches that grant and carries no RLS. A plain view selecting from a matview is a hard
-- pg_depend dependency: `drop materialized view league_ats_base cascade` (see that file)
-- also drops THIS view, so this file must be re-touched in every migration that re-emits
-- league_ats_base.sql -- otherwise the CASCADE drop has no recreate to pair with (same
-- rule as league_completed_standings over leaderboard_season_totals).
create or replace view public.league_ats_team as
select
  b.season_year,
  b.team_id,
  t.name as team_name,
  t.short_name as team_short_name,
  count(*)::int as games,
  count(*) filter (where b.ats_result = 'win')::int as ats_wins,
  count(*) filter (where b.ats_result = 'loss')::int as ats_losses,
  count(*) filter (where b.ats_result = 'push')::int as ats_pushes,
  count(*) filter (where b.su_result = 'win')::int as su_wins,
  count(*) filter (where b.su_result = 'loss')::int as su_losses,
  count(*) filter (where b.su_result = 'push')::int as su_pushes,
  count(*) filter (where b.is_home and b.ats_result = 'win')::int as home_ats_wins,
  count(*) filter (where b.is_home and b.ats_result = 'loss')::int as home_ats_losses,
  count(*) filter (where b.is_home and b.ats_result = 'push')::int as home_ats_pushes,
  count(*) filter (where not b.is_home and b.ats_result = 'win')::int as away_ats_wins,
  count(*) filter (where not b.is_home and b.ats_result = 'loss')::int as away_ats_losses,
  count(*) filter (where not b.is_home and b.ats_result = 'push')::int as away_ats_pushes,
  count(*) filter (where b.is_favorite and b.ats_result = 'win')::int as fav_ats_wins,
  count(*) filter (where b.is_favorite and b.ats_result = 'loss')::int as fav_ats_losses,
  count(*) filter (where b.is_favorite and b.ats_result = 'push')::int as fav_ats_pushes,
  count(*) filter (where b.is_favorite = false and b.ats_result = 'win')::int as dog_ats_wins,
  count(*) filter (where b.is_favorite = false and b.ats_result = 'loss')::int as dog_ats_losses,
  count(*) filter (where b.is_favorite = false and b.ats_result = 'push')::int as dog_ats_pushes
from public.league_ats_base b
join public.teams t on t.id = b.team_id
group by b.season_year, b.team_id, t.name, t.short_name;

revoke all on public.league_ats_team from public, anon, authenticated;
grant select on public.league_ats_team to service_role;

-- file: functions/stats/refresh_leaderboard_stats.sql
-- Refresh the materialized leaderboard/stats views after a grading run (issue #191).
--
-- SECURITY DEFINER so it executes as the matview owner (postgres) -- REFRESH MATERIALIZED
-- VIEW requires ownership, and the calling service_role is not the owner. search_path is
-- pinned empty with every object schema-qualified.
--
-- CONCURRENTLY keeps each view readable by in-flight requests during the refresh and is
-- transaction-safe inside this function (unlike CREATE INDEX CONCURRENTLY, REFRESH ...
-- CONCURRENTLY does not self-manage transactions); it requires the unique index each
-- matview declares in supabase/src/views/.
--
-- Called by the server grading helpers (src/lib/server/grading.ts) after grade_game /
-- grade_week / grade_season succeed. A refresh failure is logged there but does NOT fail
-- the grade: the settlement write already committed and a stale matview self-heals on the
-- next grade. EXECUTE is granted to service_role by grants/admin_grants.sql (blanket
-- grant on all functions); the closed-by-default ACL guard strips only the PUBLIC grant.
create or replace function public.refresh_leaderboard_stats()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  refresh materialized view concurrently public.leaderboard_season_totals;
  refresh materialized view concurrently public.stats_season_trend;
  refresh materialized view concurrently public.stats_accuracy_by_team;
  refresh materialized view concurrently public.stats_accuracy_by_weight;
  refresh materialized view concurrently public.stats_head_to_head;
  refresh materialized view concurrently public.stats_head_to_head_alltime;
  refresh materialized view concurrently public.stats_alltime_totals;
  refresh materialized view concurrently public.stats_accuracy_by_team_alltime;
  refresh materialized view concurrently public.stats_accuracy_by_weight_alltime;
  refresh materialized view concurrently public.group_pick_consensus;
  refresh materialized view concurrently public.stats_accuracy_by_line_side;
  refresh materialized view concurrently public.stats_pick_streaks;
  -- League-wide team ATS facts (#406). Group-independent and driven by games/game_lines
  -- rather than pick_settlement, but the same grading run that settles picks is also when
  -- games go final + closing lines are captured, so this is the correct invalidation point.
  refresh materialized view concurrently public.league_ats_base;
end;
$$;

comment on function public.refresh_leaderboard_stats() is
  'Refreshes the 13 leaderboard/stats materialized views CONCURRENTLY (issues #191/#280/#294/#296/#317/#406). '
  'Called after each grading run by src/lib/server/grading.ts.';
