-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0230_feedback.sql
-- ---------------------------------------------------------------------------
-- feedback
-- In-app feedback / bug reports (issue #500, ADR-0028). Store-first: a submission
-- writes exactly one row here; filing to GitHub is a separate, admin-gated step
-- (delivered in the admin-queue follow-up). User-scoped, NOT group-scoped — a
-- deliberate departure from ADR-0002: a row is owned by its submitter and visible
-- to that submitter plus the global admin (the triage inbox).
-- RLS: owner INSERT/SELECT own; admin SELECT all + UPDATE (triage). Hot-path inserts
-- run through the service role (POST /api/feedback), which bypasses RLS.
-- ---------------------------------------------------------------------------
create table if not exists public.feedback (
  id               uuid primary key default gen_random_uuid(),
  -- SET NULL (not CASCADE) on user delete: keep a report that may already be filed
  -- to GitHub while dropping attribution (ADR-0028).
  user_id          uuid references public.users (id) on delete set null,
  kind             text not null default 'idea'
    check (kind in ('bug', 'idea', 'confused', 'love')),
  body             text not null
    check (char_length(body) between 1 and 4000),
  -- App-agnostic capture blob (route, build id, viewport, UA, Sentry event id,
  -- season, active group, …). Kept as jsonb so the shape can evolve and the RN app
  -- can POST the same endpoint later without a schema change (ADR-0028).
  context          jsonb not null default '{}'::jsonb,
  status           text not null default 'new'
    check (status in ('new', 'triaged', 'filed', 'dismissed')),
  github_issue_url text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists idx_feedback_user on public.feedback (user_id);
-- The admin triage queue lists newest-first, filtered by status.
create index if not exists idx_feedback_status_created
  on public.feedback (status, created_at desc);

alter table public.feedback enable row level security;

-- file: policies/46_policies_feedback.sql
-- feedback (issue #500, ADR-0028): owner-scoped, with admin read-all + triage.

-- Owners may insert only rows attributed to themselves.
drop policy if exists ins_own_feedback on public.feedback;
create policy ins_own_feedback
  on public.feedback for insert
  to authenticated
  with check (user_id = auth.uid());

-- Owners read their own rows; admins read everyone's (the triage queue).
drop policy if exists sel_own_or_admin_feedback on public.feedback;
create policy sel_own_or_admin_feedback
  on public.feedback for select
  to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- Only admins update (status transitions + github_issue_url). Owners cannot edit
-- after submit; the hot-path insert runs as the service role, which bypasses RLS.
drop policy if exists admin_upd_feedback on public.feedback;
create policy admin_upd_feedback
  on public.feedback for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- file: grants/player_grants.sql
-- =========================
-- PLAYER (authenticated, non-admin)
-- =========================

-- Basic resolution (also granted by the closed-by-default baseline; restated here so
-- this file reads on its own).
grant usage on schema public to authenticated;

-- NOTE: function access starts closed in schemas/0001_role_baseline.sql, which revokes
-- EXECUTE from PUBLIC (the implicit grant authenticated actually rode) and sets the
-- born-closed default for future functions. There is intentionally no blanket
-- `revoke execute ... from authenticated` here: it never closed the real door (PUBLIC
-- did), and -- because this file is emitted in the grants phase, after the functions
-- phase -- it would strip the explicit per-function grants made in the function source
-- files (the closure helpers, get-only RPCs, etc.). Each function re-opens itself.

-- Enums used by player RPCs
grant usage on type public.weight_enum to authenticated;
grant usage on type public.side_enum  to authenticated;

-- Defense in depth: strip Supabase's default anon/PUBLIC ACL on every table that has
-- no anon RLS policy. Supabase auto-grants ALL on new public tables to anon/PUBLIC;
-- RLS already blocks rows, but revoking the grant closes Data API reachability too
-- (the same revoke-before-grant pattern already applied to cron_run_log /
-- push_subscriptions / notification_log below and the group-owned tables). Runs before
-- the explicit `authenticated` grants below, which survive (revoke targets only
-- anon/PUBLIC); service_role keeps access via admin_grants.sql.
revoke all on
  public.games, public.game_lines, public.results, public.totals,
  public.users, public.weeks, public.seasons, public.teams,
  public.picks, public.pick_settlement, public.settings, public.audit_log
from public, anon;

-- Base table privileges (RLS still enforces row/column rules)
grant select on public.games,
               public.game_lines,
               public.results,
               public.totals,
               public.users,
               public.weeks,
               public.seasons,
               public.teams
to authenticated;

-- Picks CRUD the player needs; RLS gates who/when
grant select, insert, update on public.picks to authenticated;
grant select on public.pick_settlement to authenticated;

-- Settings & audit:
-- Grant SELECT so admins (who are also 'authenticated') can read via RLS (is_admin()).
-- Do NOT grant write widely; writes happen via SECURITY DEFINER admin RPCs.
grant select on public.settings, public.audit_log to authenticated;

-- cron_run_log: admin-only reads via RLS (is_admin()); writes come from service role.
-- Supabase's default ACL auto-grants ALL on new public tables to anon/authenticated,
-- so strip anon (and PUBLIC) first -- defense in depth alongside RLS, mirroring the
-- revoke/grant pattern on public.picks_status_view_user. authenticated keeps SELECT,
-- gated to admins by the admin_sel_cron_run_log policy.
revoke all on public.cron_run_log from public, anon;
grant select on public.cron_run_log to authenticated;

-- odds_api_responses: admin-only reads via RLS (is_admin()); writes come from
-- service role. Same defense-in-depth revoke/grant shape as cron_run_log.
revoke all on public.odds_api_responses from public, anon;
grant select on public.odds_api_responses to authenticated;

-- espn_api_responses: ESPN sibling of odds_api_responses (issue #450). Admin-only
-- reads via RLS (is_admin()); writes come from service role. Same shape.
revoke all on public.espn_api_responses from public, anon;
grant select on public.espn_api_responses to authenticated;

-- push_subscriptions: owners manage their own rows; RLS gates which rows.
-- Strip the default anon/PUBLIC ACL first (defense in depth alongside RLS).
revoke all on public.push_subscriptions from public, anon;
grant select, insert, update, delete on public.push_subscriptions to authenticated;

-- notification_log: owners read their own rows via RLS; writes come from service role.
revoke all on public.notification_log from public, anon;
grant select on public.notification_log to authenticated;

-- feedback (#500): owners insert + read their own rows; admins read all + update
-- (triage), all gated by RLS. Strip the default anon/PUBLIC ACL first (defense in
-- depth alongside RLS). Hot-path inserts run as the service role.
revoke all on public.feedback from public, anon;
grant select, insert, update on public.feedback to authenticated;

-- Player-facing RPCs whose source files do not append their own grant. The baseline
-- revokes EXECUTE from PUBLIC, so these explicit grants are the sole path for
-- authenticated. lock_pick/unlock_pick/is_member live here (rather than self-granting in
-- their function files) by long-standing convention; keep them co-located.
grant execute on function public.lock_pick(uuid, public.side_enum, public.weight_enum, text)
  to authenticated, service_role;
grant execute on function public.unlock_pick(uuid)
  to authenticated, service_role;
grant execute on function public.is_member(uuid)
  to authenticated, service_role;

-- NOTE: The remaining RPCs follow the convention of appending their own EXECUTE
-- grants in their own source files:
--   - public get-only RPCs (e.g., get_active_week_games): GRANT to anon, authenticated
--   - admin RPCs: handled via service_role or guarded is_admin() (see admin_grants.sql)
