-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0201_picks.sql
-- file: schemas/0201_picks.sql

-- Ensure UUID generator is available
create extension if not exists pgcrypto;

-- 1) Add the surrogate id column used by server code and settlement FKs.
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'picks'
      and column_name = 'id'
  ) then
    alter table public.picks add column id uuid;
  end if;
end$$;

-- 2) Backfill existing ids.
update public.picks
set id = gen_random_uuid()
where id is null;

-- 3) Enforce NOT NULL + default for future inserts.
alter table public.picks
  alter column id set not null;

alter table public.picks
  alter column id set default gen_random_uuid();

-- 4) Add the group tenancy column.
alter table public.picks
  add column if not exists group_id uuid;

-- 5) Keep the surrogate id usable as an FK target after the PK moves.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.picks'::regclass
      and conname = 'picks_id_key'
  ) then
    alter table public.picks
      add constraint picks_id_key unique (id);
  end if;
end$$;

-- file: schemas/0202_pick_settlement.sql
alter table public.settings add column if not exists missed_pick_penalty int default -1;

create table if not exists public.pick_settlement (
  group_id     uuid not null,
  user_id      uuid not null,
  game_id      uuid not null references public.games(id) on delete cascade,
  pick_id      uuid references public.picks(id) on delete cascade,
  points_delta int,
  outcome      public.pick_outcome,
  graded_at    timestamptz not null default now(),
  constraint pick_settlement_pkey primary key (group_id, user_id, game_id)
);

alter table public.pick_settlement
  add column if not exists group_id uuid;

-- keep unique link when a real pick exists
create unique index if not exists uq_pick_settlement_pick_id
  on public.pick_settlement(pick_id)
  where pick_id is not null;

-- more flexible constraint to allow configurable penalties (e.g., -2)
alter table public.pick_settlement
  drop constraint if exists pick_settlement_points_range;

alter table public.pick_settlement
  add constraint pick_settlement_points_range
  check (points_delta between -20 and 10);

-- helpful index for joins by game
create index if not exists idx_pick_settlement_game on public.pick_settlement(game_id);
create index if not exists idx_pick_settlement_group_game_user
  on public.pick_settlement(group_id, game_id, user_id);

-- RLS: readable, but no client writes
alter table public.pick_settlement enable row level security;

-- (A) Let authenticated users read settlements for their groups.
do $$
begin
  drop policy if exists "read settlements" on public.pick_settlement;
exception when undefined_object then null; end$$;

create policy "read settlements"
  on public.pick_settlement
  for select
  to authenticated
  using (public.is_member(group_id));

-- (B) Block all client writes; grading functions (SECURITY DEFINER) or service role will write
do $$
begin
  drop policy if exists "no client writes (insert)" on public.pick_settlement;
  drop policy if exists "no client writes (update)" on public.pick_settlement;
  drop policy if exists "no client writes (delete)" on public.pick_settlement;
exception when undefined_object then null; end$$;

create policy "no client writes (insert)"
  on public.pick_settlement
  for insert
  to authenticated
  with check (public.is_member(group_id) and false);

create policy "no client writes (update)"
  on public.pick_settlement
  for update
  to authenticated
  using (public.is_member(group_id) and false)
  with check (public.is_member(group_id) and false);

create policy "no client writes (delete)"
  on public.pick_settlement
  for delete
  to authenticated
  using (public.is_member(group_id) and false);

-- file: schemas/0210_pick_group_foreign_keys.sql
-- Stable original group for the invisible v1.7 tenancy migration.
insert into public.groups (id, name)
values ('00000000-0000-4000-8000-000000000017', 'Sunday Bets')
on conflict (id) do nothing;

insert into public.group_memberships (group_id, user_id, role)
select
  '00000000-0000-4000-8000-000000000017'::uuid,
  u.id,
  case
    when u.role = 'admin' then 'commissioner'::public.group_membership_role
    else 'member'::public.group_membership_role
  end
from public.users u
on conflict (group_id, user_id) do nothing;

update public.picks
set group_id = '00000000-0000-4000-8000-000000000017'
where group_id is null;

update public.pick_settlement ps
set group_id = coalesce(
  (
    select p.group_id
    from public.picks p
    where p.id = ps.pick_id
  ),
  '00000000-0000-4000-8000-000000000017'::uuid
)
where ps.group_id is null;

alter table public.picks
  alter column group_id set not null;

alter table public.pick_settlement
  alter column group_id set not null;

alter table public.pick_settlement
  drop constraint if exists pick_settlement_pick_id_fkey;

do $$
declare
  pk_name text;
begin
  select conname into pk_name
  from pg_constraint
  where conrelid = 'public.picks'::regclass
    and contype = 'p'
  limit 1;

  if pk_name is not null then
    execute format('alter table public.picks drop constraint %I', pk_name);
  end if;
end$$;

alter table public.picks
  drop constraint if exists picks_user_game_unique;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.picks'::regclass
      and conname = 'picks_pkey'
  ) then
    alter table public.picks
      add constraint picks_pkey primary key (group_id, user_id, game_id);
  end if;
end$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.picks'::regclass
      and conname = 'picks_group_user_game_unique'
  ) then
    alter table public.picks
      add constraint picks_group_user_game_unique unique (group_id, user_id, game_id);
  end if;
end$$;

create index if not exists idx_picks_group_game_user
  on public.picks(group_id, game_id, user_id);

alter table public.pick_settlement
  add constraint pick_settlement_pick_id_fkey
  foreign key (pick_id)
  references public.picks(id)
  on delete cascade;

alter table public.pick_settlement
  drop constraint if exists pick_settlement_pkey;

alter table public.pick_settlement
  add constraint pick_settlement_pkey primary key (group_id, user_id, game_id);

alter table public.picks
  drop constraint if exists picks_group_id_fkey;

alter table public.picks
  add constraint picks_group_id_fkey
  foreign key (group_id)
  references public.groups(id)
  on delete cascade;

alter table public.pick_settlement
  drop constraint if exists pick_settlement_group_id_fkey;

alter table public.pick_settlement
  add constraint pick_settlement_group_id_fkey
  foreign key (group_id)
  references public.groups(id)
  on delete cascade;

-- file: schemas/0300_rls.sql
-- Enable RLS everywhere (deny by default)
alter table public.picks      enable row level security;
alter table if exists public.pick_settlement enable row level security;
alter table public.games      enable row level security;
alter table public.game_lines enable row level security;
alter table public.results    enable row level security;
alter table public.totals     enable row level security;
alter table public.users      enable row level security;
alter table public.settings   enable row level security;
alter table public.audit_log  enable row level security;
alter table public.weeks      enable row level security;
alter table public.seasons    enable row level security;
alter table public.teams      enable row level security;

-- GAMES & LINES & RESULTS & TOTALS: readable to all authenticated
drop policy if exists sel_games on public.games;
create policy sel_games on public.games for select to authenticated using (true);

drop policy if exists sel_game_lines on public.game_lines;
create policy sel_game_lines on public.game_lines for select to authenticated using (true);

drop policy if exists sel_results on public.results;
create policy sel_results on public.results for select to authenticated using (true);

drop policy if exists sel_totals on public.totals;
create policy sel_totals  on public.totals  for select to authenticated using (true);

-- Teams/Weeks/Seasons readable to authenticated
drop policy if exists sel_weeks on public.weeks;
create policy sel_weeks on public.weeks for select to authenticated using (true);

drop policy if exists sel_seasons on public.seasons;
create policy sel_seasons on public.seasons for select to authenticated using (true);

drop policy if exists sel_teams on public.teams;
create policy sel_teams on public.teams for select to authenticated using (true);

-- USERS: everyone can read; self can update display_name
drop policy if exists sel_users on public.users;
create policy sel_users on public.users for select to authenticated using (true);

drop policy if exists upd_users_self on public.users;
create policy upd_users_self on public.users for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- PICKS: owner-only before kickoff for writes; reveal after kickoff
drop policy if exists sel_picks_owner_or_started on public.picks;
create policy sel_picks_owner_or_started
on public.picks for select to authenticated
using (
  public.is_member(group_id)
  and (user_id = (select auth.uid()) or public.game_has_started(game_id))
);

drop policy if exists ins_picks_own_pre on public.picks;
create policy ins_picks_own_pre
on public.picks for insert to authenticated
with check (
  public.is_member(group_id)
  and user_id = (select auth.uid())
  and not public.game_has_started(game_id)
);

drop policy if exists upd_picks_pre on public.picks;
create policy upd_picks_pre
on public.picks for update to authenticated
using (
  public.is_member(group_id)
  and user_id = (select auth.uid())
  and not public.game_has_started(game_id)
)
with check (
  public.is_member(group_id)
  and user_id = (select auth.uid())
  and not public.game_has_started(game_id)
);

-- SETTINGS & AUDIT: admin-only
drop policy if exists admin_sel_settings on public.settings;
create policy admin_sel_settings on public.settings for select to authenticated using (public.is_admin());

drop policy if exists admin_all_settings on public.settings;
create policy admin_all_settings on public.settings for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists admin_sel_audit on public.audit_log;
create policy admin_sel_audit on public.audit_log for select to authenticated using (public.is_admin());

drop policy if exists admin_ins_audit on public.audit_log;
create policy admin_ins_audit on public.audit_log for insert to authenticated with check (public.is_admin());

-- file: policies/10_rls_enable.sql
-- Enable RLS everywhere (deny by default)
alter table if exists public.picks       enable row level security;
alter table if exists public.pick_settlement enable row level security;
alter table if exists public.games       enable row level security;
alter table if exists public.game_lines  enable row level security;
alter table if exists public.results     enable row level security;
alter table if exists public.totals      enable row level security;
alter table if exists public.users       enable row level security;
alter table if exists public.settings    enable row level security;
alter table if exists public.audit_log   enable row level security;
alter table if exists public.weeks       enable row level security;
alter table if exists public.seasons     enable row level security;
alter table if exists public.teams       enable row level security;
alter table if exists public.groups      enable row level security;
alter table if exists public.group_memberships enable row level security;

-- file: policies/40_policies_picks.sql
-- Picks: owner-only before kickoff for writes; reveal after kickoff for reads
-- Requires helper functions: public.game_has_started(uuid)

drop policy if exists sel_picks_owner_or_started on public.picks;
create policy sel_picks_owner_or_started
  on public.picks for select
  to authenticated
  using (
    public.is_member(group_id)
    and (user_id = (select auth.uid()) or public.game_has_started(game_id))
  );

drop policy if exists ins_picks_own_pre on public.picks;
create policy ins_picks_own_pre
  on public.picks for insert
  to authenticated
  with check (
    public.is_member(group_id)
    and user_id = (select auth.uid())
    and not public.game_has_started(game_id)
  );

drop policy if exists upd_picks_pre on public.picks;
create policy upd_picks_pre
  on public.picks for update
  to authenticated
  using (
    public.is_member(group_id)
    and user_id = (select auth.uid())
    and not public.game_has_started(game_id)
  )
  with check (
    public.is_member(group_id)
    and user_id = (select auth.uid())
    and not public.game_has_started(game_id)
  );
