-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0219_settings_group_creation_mode.sql
-- Global group-creation mode for the hybrid growth model (ADR-0006, decision 3).
--   'gated': only users with public.users.can_create_group may create a group.
--   'open' : any authenticated user may create.
-- Flipping this value is a configuration change, not a schema migration, so the
-- product can open up creation on a business decision. Operational settings stay
-- on the existing single-row settings object per ADR-0002.
alter table public.settings
  add column if not exists group_creation_mode text not null default 'gated';

alter table public.settings
  drop constraint if exists settings_group_creation_mode_check;
alter table public.settings
  add constraint settings_group_creation_mode_check
  check (group_creation_mode in ('gated', 'open'));

-- file: schemas/0220_users_can_create_group.sql
-- Per-user capability for the gated create-group flow (ADR-0006, decision 3).
-- In 'gated' mode only users with this capability may create a group; in 'open'
-- mode it is ignored. Orthogonal to public.users.role (the global admin tier):
-- granting create rights never grants admin, and admin does not imply it.
alter table public.users
  add column if not exists can_create_group boolean not null default false;

-- file: schemas/0221_groups_name_length.sql
-- Bound group names from above; the table already rejects blank names
-- (groups_name_not_blank in 0208_groups.sql). Defense in depth: public.create_group
-- validates the same bound and is currently the only insert path, but the cap
-- belongs with the data so any future write path inherits it.
alter table public.groups
  drop constraint if exists groups_name_max_len;
alter table public.groups
  add constraint groups_name_max_len check (length(btrim(name)) <= 60);

-- file: functions/groups/create_group.sql
-- create_group: gated, atomic group creation (ADR-0006, decision 3).
--
-- The whole function runs in a single transaction, so a failure at any step
-- (gate rejection, constraint violation) leaves no orphan group, config, or
-- membership. SECURITY DEFINER lets it write groups / group_config /
-- group_memberships even though those tables block direct client writes; the
-- trust check is the gate below, keyed on the caller's auth.uid().
--
-- Error codes (surfaced to the caller as PostgrestError.code):
--   P0001  not authenticated
--   P0010  group name is required
--   P0011  group name too long
--   P0012  group creation not enabled for this account (gated mode)
create or replace function public.create_group(p_name text)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id  uuid;
  v_name     text;
  v_mode     text;
  v_capable  boolean;
  v_group_id uuid;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'not authenticated' using errcode = 'P0001';
  end if;

  -- Validate name: non-empty, length-bounded (mirrors groups_name_max_len).
  v_name := btrim(coalesce(p_name, ''));
  if length(v_name) = 0 then
    raise exception 'group name is required' using errcode = 'P0010';
  end if;
  if length(v_name) > 60 then
    raise exception 'group name too long' using errcode = 'P0011';
  end if;

  -- Gate: global mode, then per-user capability when gated.
  select group_creation_mode into v_mode
  from public.settings
  where id = true
  limit 1;
  v_mode := coalesce(v_mode, 'gated');

  if v_mode <> 'open' then
    select can_create_group into v_capable
    from public.users
    where id = v_user_id;

    if not coalesce(v_capable, false) then
      raise exception 'group creation is not enabled for this account'
        using errcode = 'P0012';
    end if;
  end if;

  -- Atomic create: group, then its seeded config, then the creator as commissioner.
  insert into public.groups (name)
  values (v_name)
  returning id into v_group_id;

  -- Seed group_config from global settings, reusing the shape established by
  -- 0213_seed_original_group_config.sql so every group starts consistently.
  insert into public.group_config (group_id, line_source, scoring_rules)
  values (
    v_group_id,
    'fanduel',
    jsonb_build_object(
      'missed_pick_penalty',
      coalesce((select missed_pick_penalty from public.settings where id = true limit 1), -1)
    )
  );

  insert into public.group_memberships (group_id, user_id, role, status)
  values (v_group_id, v_user_id, 'commissioner', 'active');

  return v_group_id;
end;
$$;

revoke execute on function public.create_group(text) from public, anon;

-- file: grants/zz_group_grants.sql
-- groups / group_memberships: authenticated access is gated by RLS.
-- Strip default public/anon ACLs first so anon has no Data API access.
revoke all on public.groups from public, anon;
revoke all on public.group_memberships from public, anon;

grant select on public.groups to authenticated;
grant select, insert on public.group_memberships to authenticated;

grant execute on function public.is_member(uuid) to authenticated, service_role;

-- create_group is the only insert path into groups (RLS blocks direct client
-- inserts). It is SECURITY DEFINER and enforces the create-gate internally.
grant execute on function public.create_group(text) to authenticated, service_role;

-- group_config / group_week_overrides: authenticated read gated by RLS.
-- Client writes are blocked by policy; all writes go through service_role.
revoke all on public.group_config from public, anon;
revoke all on public.group_week_overrides from public, anon;

grant select on public.group_config to authenticated;
grant select on public.group_week_overrides to authenticated;

-- group_invites: commissioners manage invites, gated by RLS; no anon access.
revoke all on public.group_invites from public, anon;

grant select, insert, update on public.group_invites to authenticated;

grant execute on function public.is_commissioner(uuid) to authenticated, service_role;
grant execute on function public.redeem_invite(text) to authenticated, service_role;

-- comments / reactions: members read+write their group's rows, gated by RLS.
-- Strip default anon/public ACLs first (defense in depth alongside RLS).
revoke all on public.comments  from public, anon;
revoke all on public.reactions from public, anon;

grant select, insert, delete on public.comments  to authenticated;
grant select, insert, delete on public.reactions to authenticated;
