-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0209_group_memberships.sql
create table if not exists public.group_memberships (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  role public.group_membership_role not null default 'member',
  status public.group_membership_status not null default 'active',
  joined_at timestamptz not null default now(),
  -- Per-player AI recap opt-out (ADR-0008, dec. 4). Default false = opted-in.
  -- When true the player appears only as neutral facts in generated recaps.
  ai_recap_opt_out boolean not null default false,
  primary key (group_id, user_id)
);

-- file: schemas/0211_group_config.sql
-- GROUP_CONFIG: one row per group, holds group-owned gameplay settings.
-- Operational settings (odds-quota caps, penalties) remain on the global settings table.
create table if not exists public.group_config (
  group_id    uuid primary key references public.groups(id) on delete cascade,
  -- Which odds source this group uses for its active line
  line_source text not null default 'fanduel',
  -- Which grading preset: 'house' grades all members on the closing line (fair);
  -- 'gamer' grades each member on their own pick-time line (legacy).
  grading_preset text not null default 'house'
    check (grading_preset in ('gamer', 'house')),
  -- Flexible JSONB bag for gameplay rule knobs (drop-worst-week, multipliers, etc.)
  -- Future rule features (issue #107) write their settings here.
  scoring_rules jsonb not null default '{}',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Additive column for existing DBs; the definition above handles fresh DBs.
alter table public.group_config
  add column if not exists grading_preset text not null default 'house'
    check (grading_preset in ('gamer', 'house'));

-- AI recap tone (ADR-0008, dec. 4): mild | medium | spicy. Default medium.
alter table public.group_config
  add column if not exists spice text not null default 'medium'
    check (spice in ('mild', 'medium', 'spicy'));

-- Whether the grade-cron AI recap runs for this group (ADR-0008, dec. 4).
alter table public.group_config
  add column if not exists ai_recaps_enabled boolean not null default true;

-- file: schemas/0224_ai_recaps.sql
-- AI_RECAPS: one row per group per graded week. Stores the AI-generated prose and
-- the deterministic facts packet that produced it (ADR-0008 boundary 5).
-- RLS: group members read their own group's recaps; all writes via service role.
create table if not exists public.ai_recaps (
  id             uuid primary key default gen_random_uuid(),
  group_id       uuid not null references public.groups(id) on delete cascade,
  season_year    integer not null,
  week_number    integer not null,
  prose          text not null,
  facts          jsonb not null,
  is_fallback    boolean not null default false,
  model          text,
  prompt_tokens  integer,
  completion_tokens integer,
  created_at     timestamptz not null default now(),
  unique (group_id, season_year, week_number)
);

-- file: policies/10_rls_enable.sql
-- Enable RLS everywhere (deny by default)
alter table if exists public.picks       enable row level security;
alter table if exists public.pick_settlement enable row level security;
alter table if exists public.games       enable row level security;
alter table if exists public.game_lines  enable row level security;
alter table if exists public.results     enable row level security;
alter table if exists public.totals      enable row level security;
alter table if exists public.users       enable row level security;
alter table if exists public.settings    enable row level security;
alter table if exists public.audit_log   enable row level security;
alter table if exists public.weeks       enable row level security;
alter table if exists public.seasons     enable row level security;
alter table if exists public.teams       enable row level security;
alter table if exists public.groups      enable row level security;
alter table if exists public.group_memberships enable row level security;
alter table if exists public.group_config enable row level security;
alter table if exists public.group_week_overrides enable row level security;
alter table if exists public.comments  enable row level security;
alter table if exists public.reactions enable row level security;
alter table if exists public.ai_recaps enable row level security;

-- file: policies/48_policies_ai_recaps.sql
-- ai_recaps: group members read their own group's rows; no client writes (service role only).
-- ADR-0002 (group tenancy boundary) + ADR-0008 (AI output is group-scoped).

drop policy if exists sel_ai_recaps_member on public.ai_recaps;
create policy sel_ai_recaps_member
  on public.ai_recaps for select
  to authenticated
  using (public.is_member(group_id));

drop policy if exists ins_ai_recaps_no_client on public.ai_recaps;
create policy ins_ai_recaps_no_client
  on public.ai_recaps for insert
  to authenticated
  with check (false);

drop policy if exists upd_ai_recaps_no_client on public.ai_recaps;
create policy upd_ai_recaps_no_client
  on public.ai_recaps for update
  to authenticated
  using (false)
  with check (false);

-- file: grants/group_grants.sql
-- groups / group_memberships: authenticated access is gated by RLS.
-- Strip default public/anon ACLs first so anon has no Data API access.
revoke all on public.groups from public, anon;
revoke all on public.group_memberships from public, anon;

grant select on public.groups to authenticated;
-- SELECT only: all membership writes go through SECURITY DEFINER RPCs / service role.
-- Direct client INSERT is blocked by the no-client-write policy (25_policies_groups.sql).
grant select on public.group_memberships to authenticated;

grant execute on function public.is_member(uuid) to authenticated, service_role;

-- create_group is the only insert path into groups (RLS blocks direct client
-- inserts). It is SECURITY DEFINER and enforces the create-gate internally.
grant execute on function public.create_group(text) to authenticated, service_role;

-- Commissioner management RPCs (ADR-0006, dec. 4 + 5): SECURITY DEFINER, caller-trust
-- verified internally; no direct client writes to groups.name or group_memberships.role.
grant execute on function public.rename_group(uuid, text)  to authenticated, service_role;
grant execute on function public.remove_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.promote_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.leave_group(uuid)         to authenticated, service_role;
grant execute on function public.mint_invite(uuid, integer, timestamptz) to authenticated, service_role;

-- update_group_config (issue #154): commissioner edits per-group league rules
-- (grading_preset, scoring_rules.drop_worst_week). SECURITY DEFINER; commissioner
-- check + ADR-0007 season-freeze enforced internally. No direct client writes to
-- group_config (upd_group_config_no_client policy stays intact). group_active_season_settled
-- is the shared freeze helper, also called by the group page load to lock the UI selector.
grant execute on function public.update_group_config(uuid, text, boolean) to authenticated, service_role;
grant execute on function public.group_active_season_settled(uuid)        to authenticated, service_role;

-- group_config / group_week_overrides: authenticated read gated by RLS.
-- Client writes are blocked by policy; all writes go through service_role.
revoke all on public.group_config from public, anon;
revoke all on public.group_week_overrides from public, anon;

grant select on public.group_config to authenticated;
grant select on public.group_week_overrides to authenticated;

-- group_invites: commissioners manage invites, gated by RLS; no anon access.
revoke all on public.group_invites from public, anon;

grant select, insert, update on public.group_invites to authenticated;

grant execute on function public.is_commissioner(uuid) to authenticated, service_role;
grant execute on function public.redeem_invite(text) to authenticated, service_role;
-- preview_invite: read-only display state for /join/[code]; SECURITY DEFINER so
-- invitees can preview an invite the commissioner-only RLS would otherwise hide.
grant execute on function public.preview_invite(text) to authenticated, service_role;

-- comments / reactions: members read+write their group's rows, gated by RLS.
-- Strip default anon/public ACLs first (defense in depth alongside RLS).
revoke all on public.comments  from public, anon;
revoke all on public.reactions from public, anon;

grant select, insert, delete on public.comments  to authenticated;
grant select, insert, delete on public.reactions to authenticated;

-- ai_recaps: members read their group's rows; no client writes (service role only).
-- ADR-0008 (AI output is group-scoped, writes via service role batch lane).
revoke all on public.ai_recaps from public, anon;
grant select on public.ai_recaps to authenticated;
