-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;

-- signature-adjustment drops
-- drop for signature change: functions/groups/update_group_config.sql
drop function if exists public.update_group_config(uuid, text, boolean);

-- file: views/leaderboard_season_totals.sql
-- One row per user per (group, season) with totals + ranks.
-- Drop-worst-week (ADR-0018, superseding ADR-0005): when a group enables
-- group_config.scoring_rules.drop_worst_week AND sets a
-- drop_worst_week_start_year, a player's single lowest-scoring week is omitted
-- from total_points for that season and every later one, once they have 2+
-- settled weeks. Requiring a start year makes the rule non-retroactive by
-- construction -- seasons before it are always raw, matching the historical
-- sheets exactly. The drop forgives points only -- the W/L/push record and
-- tie-breakers still count the dropped week.
-- The "is drop active for this (group, season_year)" predicate is inlined here
-- (and in stats_alltime_totals.sql / stats_season_trend.sql) rather than pulled
-- into a shared SQL function, to avoid adding another CASCADE dependency edge to
-- the matview re-emission described below (ADR-0018). Keep all three copies
-- textually identical.
-- Materialized (issue #191): season standings are recomputed only at the end of a
-- grading run via public.refresh_leaderboard_stats(), not on every page load. The
-- query body below is unchanged from the prior regular view.
-- DROP MATERIALIZED VIEW (not DROP VIEW): once #191 converted this to a matview, any
-- later re-emission of this file (e.g. issue #152's keyset index below, or #274's
-- is_scoring filter) runs against a DB where it is already a matview, and `drop view`
-- errors on a matview. IF EXISTS keeps the from-empty baseline a clean no-op.
-- CASCADE: two objects hard-depend on this matview and get dropped with it, so both
-- must be touched (re-emitted) in any migration that re-emits this file, or the
-- CASCADE drop has no recreate to pair with:
--   * leaderboard_season_page() is `returns setof` this matview (a hard type
--     dependency); recreated by functions/stats/leaderboard_season_page.sql (emitted
--     after views), with its grant restored by the ADR-0011 ACL guard + service_role
--     default privileges.
--   * league_completed_standings is a plain view selecting from this matview (a
--     regular pg_depend dependency); recreated by
--     views/league_completed_standings.sql (emitted after this file, alphabetically).
drop materialized view if exists public.leaderboard_season_totals cascade;

create materialized view public.leaderboard_season_totals as
with season_rows as (
select
ps.user_id,
u.display_name,
u.avatar_key,
s.year as season_year,
w.id as week_id,
ps.points_delta,
ps.outcome,
ps.group_id
from public.pick_settlement ps
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
-- Non-scoring rounds (ADR-0016) never count toward standings.
where w.is_scoring
)
-- Decision-level season aggregates: raw points and the W/L/push record.
-- Record counts intentionally include every week, even one later dropped
-- (ADR-0005: drop-worst-week forgives points, not record).
, totals as (
select
user_id,
display_name,
avatar_key,
season_year,
group_id,
sum(points_delta)::int as raw_total,
count(*)::int as decisions,
count(*) filter (where outcome = 'win')::int as wins,
count(*) filter (where outcome = 'loss')::int as losses,
count(*) filter (where outcome = 'push')::int as pushes,
count(*) filter (where outcome = 'missed')::int as missed
from season_rows
group by user_id, display_name, avatar_key, season_year, group_id
)
-- Week-level points per player, used to find the single lowest week.
, week_points as (
select
user_id,
season_year,
group_id,
week_id,
sum(points_delta)::int as wk_points
from season_rows
group by user_id, season_year, group_id, week_id
)
-- Per player: count of settled weeks and the lowest week's points.
, week_summary as (
select
user_id,
season_year,
group_id,
count(*)::int as weeks_played,
min(wk_points)::int as lowest_week_points
from week_points
group by user_id, season_year, group_id
)
-- Resolved drop-worst-week config per group (defaults: off, no start year).
, group_drop as (
select
g.id as group_id,
coalesce((gc.scoring_rules ->> 'drop_worst_week')::boolean, false) as drop_worst_week,
(gc.scoring_rules ->> 'drop_worst_week_start_year')::int as drop_worst_week_start_year
from public.groups g
left join public.group_config gc on gc.group_id = g.id
)
, adjusted as (
select
t.user_id,
t.display_name,
t.avatar_key,
t.season_year,
t.group_id,
t.decisions,
t.wins,
t.losses,
t.pushes,
t.missed,
-- Drop the single lowest week's points only when the group enables it, a
-- start year is set and this season is at or after it (non-retroactive by
-- construction, ADR-0018), AND the player has 2+ settled weeks. Otherwise the
-- raw total stands -- this is also what keeps every season before the start
-- year byte-identical to the historical sheets.
case
when gd.drop_worst_week
 and gd.drop_worst_week_start_year is not null
 and t.season_year >= gd.drop_worst_week_start_year
 and ws.weeks_played >= 2
then t.raw_total - ws.lowest_week_points
else t.raw_total
end::int as total_points
from totals t
join week_summary ws
on ws.user_id = t.user_id
and ws.season_year = t.season_year
and ws.group_id = t.group_id
join group_drop gd on gd.group_id = t.group_id
)
select
a.user_id,
a.display_name,
a.season_year,
a.total_points,
a.decisions,
a.wins,
a.losses,
a.pushes,
a.missed,
dense_rank() over (
partition by a.group_id, a.season_year
order by a.total_points desc, a.wins desc, a.pushes desc
) as rank,
a.group_id,
a.avatar_key
from adjusted a;

-- Unique natural key. Required for REFRESH MATERIALIZED VIEW CONCURRENTLY and also
-- serves the (group_id, season_year) read filter in getSeasonLeaderboard.
create unique index if not exists uq_leaderboard_season_totals
  on public.leaderboard_season_totals (group_id, user_id, season_year);

-- Keyset-pagination index (issue #152, ADR-0002 query discipline). Matches the
-- (group_id, season_year) equality filter plus the exact display ordering used by
-- public.leaderboard_season_page: total_points/wins/pushes descending, with user_id
-- as the unique descending tie-breaker so the keyset cursor is total. Column order
-- and direction mirror that ORDER BY so the keyset row-value comparison and the page
-- limit are both served by a single index range scan (EXPLAIN: Index Scan, no Sort).
create index if not exists idx_leaderboard_season_totals_keyset
  on public.leaderboard_season_totals
  (group_id, season_year, total_points desc, wins desc, pushes desc, user_id desc);

-- Materialized views are NOT covered by the schema-wide `grant select on all tables`
-- (that grant excludes matviews), so service_role is granted explicitly. MVs cannot
-- carry RLS; every read goes through the service-role client, which filters by group_id.
revoke all on public.leaderboard_season_totals from public, anon, authenticated;
grant select on public.leaderboard_season_totals to service_role;

-- file: views/league_completed_standings.sql
-- League honors read-model (#279, ADR-0013): a plain view over the
-- leaderboard_season_totals matview, filtered to seasons whose scoring-week games have
-- all finished. Reads the already-materialized standings (no refresh of its own). Source
-- for the reigning champion (rank 1 of the most-recently-completed season), the trophy
-- case (rank 1 of every completed season), and the wooden spoon (max rank of the
-- most-recently-completed season).
-- A plain view selecting from a matview is a hard pg_depend dependency, so
-- `drop materialized view leaderboard_season_totals cascade` (see that file) also drops
-- THIS object. Touch this file (even with no functional change) in every migration that
-- re-emits leaderboard_season_totals.sql, so the generator bundles both in the same
-- migration -- otherwise the CASCADE drop has no recreate to pair with (ADR-0018/#357).
create or replace view public.league_completed_standings as
with completed_seasons as (
  -- "Completed" = every scoreable (non-postponed/cancelled) game in the season's scoring
  -- weeks is done per either signal: final_scores populated (graded live) OR status='final'
  -- (imported/backfilled seasons whose status was set correctly but whose final_scores may not
  -- have been populated if the row already existed on conflict). Either is sufficient: a season
  -- with stale 'scheduled' status but final_scores passes; one with status='final' but no
  -- final_scores (historical import with on-conflict-do-nothing) passes too. A game blocks
  -- completion only if both signals are absent. postponed/cancelled are excluded so one
  -- unplayable game never blocks completion. Keyed by year to match
  -- leaderboard_season_totals.season_year (NFL-only league today).
  select s.year as season_year
  from public.seasons s
  join public.weeks w on w.season_id = s.id and w.is_scoring
  join public.games g on g.week_id = w.id
  where g.status not in ('postponed', 'cancelled')
  group by s.year
  having count(*) > 0
     and count(*) filter (where (g.final_scores->>'home') is null and g.status <> 'final') = 0
)
select t.*
from public.leaderboard_season_totals t
join completed_seasons cs on cs.season_year = t.season_year;

-- Reads a service_role-only matview; the SvelteKit server fetches via the service key and
-- filters by group_id (views/matviews carry no RLS). Match the matview's grant.
revoke all on public.league_completed_standings from public, anon, authenticated;
grant select on public.league_completed_standings to service_role;

-- file: views/stats_alltime_totals.sql
-- One row per user per group with all-time totals.
-- total_points (ADR-0018, superseding ADR-0005) is the SUM of each season's
-- drop-aware standings total -- i.e. exactly what leaderboard_season_totals would
-- show for each of that player's seasons, added up. This is what makes career ==
-- Sigma(per-season standings cards) true by construction, regardless of whether
-- drop_worst_week is on, off, or scoped to only some seasons via
-- drop_worst_week_start_year. wins/losses/pushes/missed/decisions stay raw sums
-- across every settled pick -- the drop never touches record (ADR-0005's
-- forgive-points-not-record principle).
-- The "is drop active for this (group, season_year)" predicate is inlined here
-- (and in leaderboard_season_totals.sql / stats_season_trend.sql) rather than
-- pulled into a shared SQL function, to avoid adding another CASCADE dependency
-- edge to the matview re-emission described below (ADR-0018). Keep all three
-- copies textually identical.
-- Materialized (issue #191): refreshed by public.refresh_leaderboard_stats() at the end
-- of a grading run. Matviews don't support security_invoker; all reads are service-role.
-- DROP MATERIALIZED VIEW (not DROP VIEW): #191 made this a matview, so re-emission of this
-- file runs against an existing matview, and `drop view` errors on a matview.
drop materialized view if exists public.stats_alltime_totals;

create materialized view public.stats_alltime_totals as
with season_rows as (
select
ps.user_id,
ps.group_id,
s.year as season_year,
w.id as week_id,
ps.points_delta,
ps.outcome
from public.pick_settlement ps
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
-- Non-scoring rounds (ADR-0016) never count toward standings.
where w.is_scoring
)
-- Raw record: every settled decision counts, regardless of any later drop.
, alltime_records as (
select
user_id,
group_id,
count(*)::int as decisions,
count(*) filter (where outcome = 'win')::int as wins,
count(*) filter (where outcome = 'loss')::int as losses,
count(*) filter (where outcome = 'push')::int as pushes,
count(*) filter (where outcome = 'missed')::int as missed
from season_rows
group by user_id, group_id
)
-- Per-season raw points, mirroring leaderboard_season_totals' "totals" CTE.
, season_totals as (
select
user_id,
group_id,
season_year,
sum(points_delta)::int as raw_total
from season_rows
group by user_id, group_id, season_year
)
-- Week-level points per player/season, used to find each season's lowest week.
, week_points as (
select
user_id,
group_id,
season_year,
week_id,
sum(points_delta)::int as wk_points
from season_rows
group by user_id, group_id, season_year, week_id
)
, week_summary as (
select
user_id,
group_id,
season_year,
count(*)::int as weeks_played,
min(wk_points)::int as lowest_week_points
from week_points
group by user_id, group_id, season_year
)
-- Resolved drop-worst-week config per group (defaults: off, no start year).
, group_drop as (
select
g.id as group_id,
coalesce((gc.scoring_rules ->> 'drop_worst_week')::boolean, false) as drop_worst_week,
(gc.scoring_rules ->> 'drop_worst_week_start_year')::int as drop_worst_week_start_year
from public.groups g
left join public.group_config gc on gc.group_id = g.id
)
-- Per-season drop-adjusted total -- identical predicate and arithmetic to
-- leaderboard_season_totals, so each term here equals that season's card.
, season_adjusted as (
select
st.user_id,
st.group_id,
case
when gd.drop_worst_week
 and gd.drop_worst_week_start_year is not null
 and st.season_year >= gd.drop_worst_week_start_year
 and ws.weeks_played >= 2
then st.raw_total - ws.lowest_week_points
else st.raw_total
end::int as season_total_points
from season_totals st
join week_summary ws
on ws.user_id = st.user_id
and ws.season_year = st.season_year
and ws.group_id = st.group_id
join group_drop gd on gd.group_id = st.group_id
)
, alltime_points as (
select
user_id,
group_id,
sum(season_total_points)::int as total_points
from season_adjusted
group by user_id, group_id
)
select
  ap.user_id,
  u.display_name,
  ap.total_points,
  ar.decisions,
  ar.wins,
  ar.losses,
  ar.pushes,
  ar.missed,
  ap.group_id
from alltime_points ap
join alltime_records ar on ar.user_id = ap.user_id and ar.group_id = ap.group_id
join public.users u on u.id = ap.user_id;

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the group_id read filter.
create unique index if not exists uq_stats_alltime_totals
  on public.stats_alltime_totals (group_id, user_id);

revoke all on public.stats_alltime_totals from public, anon, authenticated;
grant select on public.stats_alltime_totals to service_role;

-- file: views/stats_season_trend.sql
-- Weekly and cumulative season scoring per group, shaped for WeeklyCumulativeEntry.
-- is_dropped_week (ADR-0018, superseding ADR-0005): true for exactly the single
-- lowest-scoring week (ties broken by earliest week_number) of a player's season,
-- but ONLY when the group's drop-worst-week rule is active for that
-- (group, season_year) -- enabled, a drop_worst_week_start_year is set, this season
-- is at or after it -- AND the player has 2+ settled weeks. This view stays an
-- analytics surface, not a second standings total: week_points/cumulative_points/
-- season_total are always raw, so once the rule is active for a season, the trend's
-- final value intentionally diverges from that season's (adjusted) standings card by
-- exactly the dropped week's points. is_dropped_week exists so the UI can annotate
-- which week caused that gap (Leaderboard-owns-standings / Stats-owns-analytics
-- split, ADR-0018) instead of silently disagreeing with no explanation.
-- The "is drop active for this (group, season_year)" predicate is inlined here (and in
-- leaderboard_season_totals.sql / stats_alltime_totals.sql) rather than pulled into a
-- shared SQL function, to avoid adding another CASCADE dependency edge to the matview
-- re-emission described below (ADR-0018). Keep all three copies textually identical.
-- Materialized (issue #191): refreshed by public.refresh_leaderboard_stats() at the end
-- of a grading run. Matviews don't support security_invoker; all reads are service-role.
-- DROP MATERIALIZED VIEW (not DROP VIEW): #191 made this a matview, so re-emission of this
-- file runs against an existing matview, and `drop view` errors on a matview.
drop materialized view if exists public.stats_season_trend;

create materialized view public.stats_season_trend as
with week_rows as (
  select
    ps.user_id,
    u.display_name,
    s.year as season_year,
    w.week_number,
    sum(ps.points_delta)::int as week_points,
    count(*) filter (where ps.outcome = 'win')::int as week_wins,
    count(*) filter (where ps.outcome = 'loss')::int as week_losses,
    count(*) filter (where ps.outcome = 'push')::int as week_pushes,
    count(*) filter (where ps.outcome = 'missed')::int as week_missed,
    ps.group_id
  from public.pick_settlement ps
  join public.games g on g.id = ps.game_id
  join public.weeks w on w.id = g.week_id
  join public.seasons s on s.id = w.season_id
  join public.users u on u.id = ps.user_id
  -- Non-scoring rounds (ADR-0016) never count toward the trend.
  where w.is_scoring
  group by ps.user_id, u.display_name, s.year, w.week_number, ps.group_id
)
-- Per player/season: count of settled weeks (ADR-0018 eligibility gate, mirrors
-- leaderboard_season_totals' week_summary.weeks_played).
, week_summary as (
  select
    user_id,
    season_year,
    group_id,
    count(*)::int as weeks_played
  from week_rows
  group by user_id, season_year, group_id
)
-- Resolved drop-worst-week config per group (defaults: off, no start year).
, group_drop as (
  select
    g.id as group_id,
    coalesce((gc.scoring_rules ->> 'drop_worst_week')::boolean, false) as drop_worst_week,
    (gc.scoring_rules ->> 'drop_worst_week_start_year')::int as drop_worst_week_start_year
  from public.groups g
  left join public.group_config gc on gc.group_id = g.id
)
-- Rank each player's weeks by points ascending (ties broken by earliest week_number)
-- to identify the single droppable week -- the same tie rule as
-- leaderboard_season_totals' min(wk_points), made deterministic here since this view
-- has to single out one row rather than just subtract a minimum.
, ranked as (
  select
    wr.*,
    row_number() over (
      partition by wr.group_id, wr.user_id, wr.season_year
      order by wr.week_points asc, wr.week_number asc
    ) as lowest_rank
  from week_rows wr
), cumulative as (
  select
    ranked.user_id,
    ranked.display_name,
    ranked.season_year,
    ranked.week_number,
    ranked.week_points,
    ranked.week_wins,
    ranked.week_losses,
    ranked.week_pushes,
    ranked.week_missed,
    (
      ranked.lowest_rank = 1
      and gd.drop_worst_week
      and gd.drop_worst_week_start_year is not null
      and ranked.season_year >= gd.drop_worst_week_start_year
      and ws.weeks_played >= 2
    ) as is_dropped_week,
    sum(ranked.week_points) over (
      partition by ranked.group_id, ranked.user_id, ranked.season_year
      order by ranked.week_number
      rows between unbounded preceding and current row
    )::int as cumulative_points,
    ranked.group_id
  from ranked
  join week_summary ws
    on ws.user_id = ranked.user_id
   and ws.season_year = ranked.season_year
   and ws.group_id = ranked.group_id
  join group_drop gd on gd.group_id = ranked.group_id
)
select
  cumulative.user_id,
  cumulative.display_name,
  cumulative.season_year,
  cumulative.week_number,
  cumulative.week_points,
  cumulative.week_wins,
  cumulative.week_losses,
  cumulative.week_pushes,
  cumulative.week_missed,
  cumulative.is_dropped_week,
  cumulative.cumulative_points,
  sum(cumulative.week_points) over (
    partition by cumulative.group_id, cumulative.user_id, cumulative.season_year
  )::int as season_total,
  dense_rank() over (
    partition by cumulative.group_id, cumulative.season_year, cumulative.week_number
    order by cumulative.cumulative_points desc
  ) as cumulative_rank_this_week,
  cumulative.group_id
from cumulative;

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the (group_id,
-- season_year) read filter in getWeeklyCumulative.
create unique index if not exists uq_stats_season_trend
  on public.stats_season_trend (group_id, user_id, season_year, week_number);

revoke all on public.stats_season_trend from public, anon, authenticated;
grant select on public.stats_season_trend to service_role;

-- file: functions/groups/update_group_config.sql
-- update_group_config: commissioner edits per-group league rules (issue #154).
--
-- Dials, all on group_config:
--   * grading_preset ('house' | 'gamer') — fairness. Frozen per season (ADR-0007):
--     changeable only while the active season has no settled games for this group.
--   * scoring_rules.drop_worst_week (boolean) — forgiveness. Freely editable.
--   * scoring_rules.drop_worst_week_start_year (int) — forgiveness scope (ADR-0018,
--     superseding ADR-0005): the first season the drop applies to. Freely editable,
--     same as the boolean; required alongside it for the rule to have any effect
--     (see leaderboard_season_totals.sql), which is what makes the rule
--     non-retroactive by construction. No UI sets this yet (commissioner control is
--     a follow-up issue) — service-role/SQL only for now.
--
-- Runs as SECURITY DEFINER so it can bypass the no-client-update RLS policy on
-- group_config (upd_group_config_no_client); the is_commissioner check is the
-- trust boundary. Nullable params mean "leave unchanged"; the UI sends the full
-- desired state of the fields it owns (grading_preset, drop_worst_week).
--
-- Error codes:
--   P0001  not authenticated
--   P0020  caller is not a commissioner of the group
--   P0030  grading preset is frozen (active season already has settled games)
create or replace function public.update_group_config(
  p_group_id uuid,
  p_grading_preset text default null,
  p_drop_worst_week boolean default null,
  p_drop_worst_week_start_year int default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_caller uuid;
begin
  v_caller := auth.uid();
  if v_caller is null then
    raise exception 'not authenticated' using errcode = 'P0001';
  end if;

  if not public.is_commissioner(p_group_id) then
    raise exception 'caller is not a commissioner of this group' using errcode = 'P0020';
  end if;

  -- ADR-0007: grading_preset is frozen once the active season has settled games,
  -- but only block a *real* change. A no-op re-submit of the same preset is always
  -- allowed (the UI sends both fields every save).
  if p_grading_preset is not null
     and p_grading_preset is distinct from
         (select grading_preset from public.group_config where group_id = p_group_id)
     and public.group_active_season_settled(p_group_id) then
    raise exception 'grading preset cannot change after the season has started'
      using errcode = 'P0030';
  end if;

  update public.group_config
  set grading_preset = coalesce(p_grading_preset, grading_preset),
      scoring_rules  = case
                         when p_drop_worst_week is not null
                           then scoring_rules || jsonb_build_object('drop_worst_week', p_drop_worst_week)
                         else scoring_rules
                       end
                       || case
                            when p_drop_worst_week_start_year is not null
                              then jsonb_build_object(
                                     'drop_worst_week_start_year', p_drop_worst_week_start_year
                                   )
                            else '{}'::jsonb
                          end,
      updated_at     = now()
  where group_id = p_group_id;
end;
$$;

revoke execute on function public.update_group_config(uuid, text, boolean, int) from public, anon;

-- file: functions/stats/leaderboard_season_page.sql
-- leaderboard_season_page: one bounded, keyset-paginated page of a group's season
-- standings (issue #152). Reads the leaderboard_season_totals materialized view
-- (#191) and returns rows in display order -- total_points/wins/pushes descending,
-- with user_id as the unique descending tie-breaker so the cursor is a total order
-- and pages are stable under inserts. Served by idx_leaderboard_season_totals_keyset.
--
-- Keyset cursor: pass the last row of the previous page as
-- (p_after_total_points, p_after_wins, p_after_pushes, p_after_user_id). All four are
-- NULL for the first page. The row-value comparison `(...) < (...)` works because the
-- ORDER BY is descending on every cursor column, so "after the cursor" == "tuple is
-- lexicographically less than the cursor tuple".
--
-- SECURITY INVOKER by design. The source matview is granted to service_role ONLY
-- (#191) -- it holds every group's rows and carries no RLS -- so this function is
-- reachable only by the service-role server client, which is the group_id trust
-- boundary (it passes the caller's own group from the session). It is intentionally
-- NOT granted to authenticated: that would let any signed-in user read other groups'
-- standings by passing an arbitrary p_group_id, violating ADR-0002 cross-group denial.
-- service_role EXECUTE comes from the blanket grant in grants/admin_grants.sql; the
-- closed-by-default ACL guard strips the implicit PUBLIC grant.
--
-- Re-emitted with #274 and #357/ADR-0018: this function `returns setof`
-- leaderboard_season_totals, so any re-emission of that matview must CASCADE-drop this
-- function (see the view source) and recreate it here afterward. The ACL guard +
-- default privileges re-close/grant on recreate. Touch this file (even with no
-- functional change) in every migration that re-emits leaderboard_season_totals.sql,
-- so the generator bundles both in the same migration -- otherwise the CASCADE drop
-- has no recreate to pair with.
create or replace function public.leaderboard_season_page(
  p_group_id uuid,
  p_season_year int,
  p_limit int default 50,
  p_after_total_points int default null,
  p_after_wins int default null,
  p_after_pushes int default null,
  p_after_user_id uuid default null
)
returns setof public.leaderboard_season_totals
language sql
stable
as $$
  select *
  from public.leaderboard_season_totals
  where group_id = p_group_id
    and season_year = p_season_year
    and (
      p_after_user_id is null
      or (total_points, wins, pushes, user_id)
         < (p_after_total_points, p_after_wins, p_after_pushes, p_after_user_id)
    )
  order by total_points desc, wins desc, pushes desc, user_id desc
  limit least(greatest(coalesce(p_limit, 50), 1), 200);
$$;

comment on function public.leaderboard_season_page(uuid, int, int, int, int, int, uuid) is
  'Keyset-paginated page of a group''s season standings (issue #152). service_role-only; '
  'the server passes the caller''s own group_id as the trust boundary (ADR-0002).';

-- file: grants/group_grants.sql
-- groups / group_memberships: authenticated access is gated by RLS.
-- Strip default public/anon ACLs first so anon has no Data API access.
revoke all on public.groups from public, anon;
revoke all on public.group_memberships from public, anon;

grant select on public.groups to authenticated;
-- SELECT only: all membership writes go through SECURITY DEFINER RPCs / service role.
-- Direct client INSERT is blocked by the no-client-write policy (25_policies_groups.sql).
grant select on public.group_memberships to authenticated;

grant execute on function public.is_member(uuid) to authenticated, service_role;

-- create_group is the only insert path into groups (RLS blocks direct client
-- inserts). It is SECURITY DEFINER and enforces the create-gate internally.
grant execute on function public.create_group(text) to authenticated, service_role;

-- Commissioner management RPCs (ADR-0006, dec. 4 + 5): SECURITY DEFINER, caller-trust
-- verified internally; no direct client writes to groups.name or group_memberships.role.
grant execute on function public.rename_group(uuid, text)  to authenticated, service_role;
grant execute on function public.remove_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.promote_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.leave_group(uuid)         to authenticated, service_role;
grant execute on function public.mint_invite(uuid, integer, timestamptz) to authenticated, service_role;

-- update_group_config (issue #154): commissioner edits per-group league rules
-- (grading_preset, scoring_rules.drop_worst_week / drop_worst_week_start_year,
-- ADR-0018). SECURITY DEFINER; commissioner check + ADR-0007 season-freeze
-- enforced internally. No direct client writes to group_config
-- (upd_group_config_no_client policy stays intact). group_active_season_settled
-- is the shared freeze helper, also called by the group page load to lock the UI selector.
grant execute on function public.update_group_config(uuid, text, boolean, int) to authenticated, service_role;
grant execute on function public.group_active_season_settled(uuid)        to authenticated, service_role;

-- group_config / group_week_overrides: authenticated read gated by RLS.
-- Client writes are blocked by policy; all writes go through service_role.
revoke all on public.group_config from public, anon;
revoke all on public.group_week_overrides from public, anon;

grant select on public.group_config to authenticated;
grant select on public.group_week_overrides to authenticated;

-- group_invites: commissioners manage invites, gated by RLS; no anon access.
revoke all on public.group_invites from public, anon;

grant select, insert, update on public.group_invites to authenticated;

grant execute on function public.is_commissioner(uuid) to authenticated, service_role;
grant execute on function public.redeem_invite(text) to authenticated, service_role;
-- preview_invite: read-only display state for /join/[code]; SECURITY DEFINER so
-- invitees can preview an invite the commissioner-only RLS would otherwise hide.
grant execute on function public.preview_invite(text) to authenticated, service_role;

-- comments / reactions: members read+write their group's rows, gated by RLS.
-- Strip default anon/public ACLs first (defense in depth alongside RLS).
revoke all on public.comments  from public, anon;
revoke all on public.reactions from public, anon;

grant select, insert, delete on public.comments  to authenticated;
grant select, insert, delete on public.reactions to authenticated;

-- ai_recaps: members read their group's rows; no client writes (service role only).
-- ADR-0008 (AI output is group-scoped, writes via service role batch lane).
revoke all on public.ai_recaps from public, anon;
grant select on public.ai_recaps to authenticated;

-- season_wrapped: members read their group's rows; no client writes (service role only).
-- ADR-0008 (AI output is group-scoped, writes via service role batch lane).
revoke all on public.season_wrapped from public, anon;
grant select on public.season_wrapped to authenticated;

-- update_group_recap_settings (issue #301): commissioner sets AI recap tone (spice)
-- and enable/disable. SECURITY DEFINER; commissioner check enforced internally.
-- No direct client writes to group_config (upd_group_config_no_client stays intact).
grant execute on function public.update_group_recap_settings(uuid, text, boolean) to authenticated, service_role;

-- update_recap_opt_out (issue #301): any member toggles their own AI recap opt-out.
-- SECURITY DEFINER (bypasses the group_memberships with_check role = 'member' guard
-- so commissioners can also opt out). user_id = auth.uid() is the trust boundary.
grant execute on function public.update_recap_opt_out(uuid, boolean) to authenticated, service_role;
