-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: views/stats_accuracy_by_line_side.sql
-- Per-user favorite-vs-underdog pick mix for the Chalk Eater / Dog Lover identity
-- badges (issue #317). One row per (group_id, user_id, season_year) summarising how
-- often a player backs the spread favorite versus the underdog.
--
-- Favorite/underdog is read off the LINE AT PICK TIME (picks.locked_spread_value,
-- negative = the locked_spread_team is favored), so it never re-derives from the
-- closing line and needs no re-grade. For the team the player actually picked:
--   picked_spread < 0  -> they backed the favorite  (chalk)
--   picked_spread > 0  -> they backed the underdog  (dog)
--   picked_spread = 0  -> pick'em; neither, but still counted in `decisions`
-- so chalk_picks + dog_picks <= decisions and each ratio is a share of all picks.
--
-- Matviews don't support RLS; all reads are service-role-only (ADR-0013).
-- Non-scoring rounds excluded per ADR-0016 (WHERE w.is_scoring).
-- group_id leads the unique index per ADR-0002.

drop materialized view if exists public.stats_accuracy_by_line_side;

create materialized view public.stats_accuracy_by_line_side as
select
  ps.user_id,
  u.display_name,
  s.year as season_year,
  count(*)::int as decisions,
  count(*) filter (
    where case
            when p.picked_team_id = p.locked_spread_team_id then p.locked_spread_value
            else -p.locked_spread_value
          end < 0
  )::int as chalk_picks,
  count(*) filter (
    where case
            when p.picked_team_id = p.locked_spread_team_id then p.locked_spread_value
            else -p.locked_spread_value
          end > 0
  )::int as dog_picks,
  ps.group_id
from public.pick_settlement ps
join public.picks p on p.id = ps.pick_id
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
-- Non-scoring rounds (ADR-0016) never count toward stats.
where w.is_scoring
  and ps.pick_id is not null
group by ps.user_id, u.display_name, s.year, ps.group_id;

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the (group_id,
-- season_year) read filter in getStatsForSeason.
create unique index if not exists uq_stats_accuracy_by_line_side
  on public.stats_accuracy_by_line_side (group_id, user_id, season_year);

revoke all on public.stats_accuracy_by_line_side from public, anon, authenticated;
grant select on public.stats_accuracy_by_line_side to service_role;

-- file: functions/stats/refresh_leaderboard_stats.sql
-- Refresh the materialized leaderboard/stats views after a grading run (issue #191).
--
-- SECURITY DEFINER so it executes as the matview owner (postgres) -- REFRESH MATERIALIZED
-- VIEW requires ownership, and the calling service_role is not the owner. search_path is
-- pinned empty with every object schema-qualified.
--
-- CONCURRENTLY keeps each view readable by in-flight requests during the refresh and is
-- transaction-safe inside this function (unlike CREATE INDEX CONCURRENTLY, REFRESH ...
-- CONCURRENTLY does not self-manage transactions); it requires the unique index each
-- matview declares in supabase/src/views/.
--
-- Called by the server grading helpers (src/lib/server/grading.ts) after grade_game /
-- grade_week / grade_season succeed. A refresh failure is logged there but does NOT fail
-- the grade: the settlement write already committed and a stale matview self-heals on the
-- next grade. EXECUTE is granted to service_role by grants/admin_grants.sql (blanket
-- grant on all functions); the closed-by-default ACL guard strips only the PUBLIC grant.
create or replace function public.refresh_leaderboard_stats()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  refresh materialized view concurrently public.leaderboard_season_totals;
  refresh materialized view concurrently public.stats_season_trend;
  refresh materialized view concurrently public.stats_accuracy_by_team;
  refresh materialized view concurrently public.stats_accuracy_by_weight;
  refresh materialized view concurrently public.stats_head_to_head;
  refresh materialized view concurrently public.stats_head_to_head_alltime;
  refresh materialized view concurrently public.stats_alltime_totals;
  refresh materialized view concurrently public.stats_accuracy_by_team_alltime;
  refresh materialized view concurrently public.stats_accuracy_by_weight_alltime;
  refresh materialized view concurrently public.group_pick_consensus;
  refresh materialized view concurrently public.stats_accuracy_by_line_side;
end;
$$;

comment on function public.refresh_leaderboard_stats() is
  'Refreshes the 11 leaderboard/stats materialized views CONCURRENTLY (issues #191/#280/#294/#317). '
  'Called after each grading run by src/lib/server/grading.ts.';
