-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0200_05_game_lines.sql
-- LINES (one active line per game)
create table if not exists public.game_lines (
  id integer generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  source text not null default 'fanduel',
  spread_team_id integer not null references public.teams(id), -- team giving/taking points
  spread_value numeric not null,                               -- negative = favorite
  fetched_at timestamptz not null default now(),
  is_active_line boolean not null default false,
  -- Flagged write-once at first grade: the last pre-kickoff line per (game, source).
  is_closing_line boolean not null default false
);

-- At most one active line per game
create unique index if not exists ux_game_lines_active
on public.game_lines (game_id)
where is_active_line = true;

-- Additive column for existing DBs; the definition above handles fresh DBs.
alter table public.game_lines
  add column if not exists is_closing_line boolean not null default false;

-- At most one closing line per (game, source)
create unique index if not exists ux_game_lines_closing
on public.game_lines (game_id, source) where is_closing_line = true;

-- file: schemas/0202_pick_settlement.sql
alter table public.settings add column if not exists missed_pick_penalty int default -1;

create table if not exists public.pick_settlement (
  group_id     uuid not null,
  user_id      uuid not null,
  game_id      uuid not null references public.games(id) on delete cascade,
  pick_id      uuid references public.picks(id) on delete cascade,
  points_delta int,
  outcome      public.pick_outcome,
  graded_at    timestamptz not null default now(),
  constraint pick_settlement_pkey primary key (group_id, user_id, game_id)
);

alter table public.pick_settlement
  add column if not exists group_id uuid;

-- keep unique link when a real pick exists
create unique index if not exists uq_pick_settlement_pick_id
  on public.pick_settlement(pick_id)
  where pick_id is not null;

-- more flexible constraint to allow configurable penalties (e.g., -2)
alter table public.pick_settlement
  drop constraint if exists pick_settlement_points_range;

alter table public.pick_settlement
  add constraint pick_settlement_points_range
  check (points_delta between -20 and 10);

-- Preset frozen at first grade so re-grades never flip already-settled weeks.
-- Backfilled to 'gamer' for all existing settlements (they were graded on locked lines).
alter table public.pick_settlement
  add column if not exists graded_preset text;
update public.pick_settlement set graded_preset = 'gamer' where graded_preset is null;

-- helpful index for joins by game
create index if not exists idx_pick_settlement_game on public.pick_settlement(game_id);
create index if not exists idx_pick_settlement_group_game_user
  on public.pick_settlement(group_id, game_id, user_id);

-- RLS: readable, but no client writes
alter table public.pick_settlement enable row level security;

-- (A) Let authenticated users read settlements for their groups.
do $$
begin
  drop policy if exists "read settlements" on public.pick_settlement;
exception when undefined_object then null; end$$;

create policy "read settlements"
  on public.pick_settlement
  for select
  to authenticated
  using (public.is_member(group_id));

-- (B) Block all client writes; grading functions (SECURITY DEFINER) or service role will write
do $$
begin
  drop policy if exists "no client writes (insert)" on public.pick_settlement;
  drop policy if exists "no client writes (update)" on public.pick_settlement;
  drop policy if exists "no client writes (delete)" on public.pick_settlement;
exception when undefined_object then null; end$$;

create policy "no client writes (insert)"
  on public.pick_settlement
  for insert
  to authenticated
  with check (public.is_member(group_id) and false);

create policy "no client writes (update)"
  on public.pick_settlement
  for update
  to authenticated
  using (public.is_member(group_id) and false)
  with check (public.is_member(group_id) and false);

create policy "no client writes (delete)"
  on public.pick_settlement
  for delete
  to authenticated
  using (public.is_member(group_id) and false);

-- file: schemas/0211_group_config.sql
-- GROUP_CONFIG: one row per group, holds group-owned gameplay settings.
-- Operational settings (odds-quota caps, penalties) remain on the global settings table.
create table if not exists public.group_config (
  group_id    uuid primary key references public.groups(id) on delete cascade,
  -- Which odds source this group uses for its active line
  line_source text not null default 'fanduel',
  -- Which grading preset: 'house' grades all members on the closing line (fair);
  -- 'gamer' grades each member on their own pick-time line (legacy).
  grading_preset text not null default 'house'
    check (grading_preset in ('gamer', 'house')),
  -- Flexible JSONB bag for gameplay rule knobs (drop-worst-week, multipliers, etc.)
  -- Future rule features (issue #107) write their settings here.
  scoring_rules jsonb not null default '{}',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Additive column for existing DBs; the definition above handles fresh DBs.
alter table public.group_config
  add column if not exists grading_preset text not null default 'house'
    check (grading_preset in ('gamer', 'house'));

-- file: functions/_private/capture_closing_line.sql
-- Flags the closing line (latest pre-kickoff row per game+source) write-once.
-- Called at the start of _grade_games_by_ids; skips any (game, source) already flagged.
create or replace function public._capture_closing_line(p_game_ids uuid[])
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.game_lines gl set is_closing_line = true
  from (
    select distinct on (l.game_id, l.source) l.id
    from public.game_lines l
    join public.games g on g.id = l.game_id
    where l.game_id = any(p_game_ids)
      and l.fetched_at <= g.commence_time
      and not exists (
        select 1 from public.game_lines c
        where c.game_id = l.game_id and c.source = l.source and c.is_closing_line
      )
    order by l.game_id, l.source, l.fetched_at desc, l.id desc
  ) winner
  where gl.id = winner.id;
end;
$$;

-- file: functions/_private/grade_games_by_ids.sql
-- This is a new internal helper function. Note the leading underscore.
create or replace function public._grade_games_by_ids(p_game_ids uuid[])
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Capture the closing line for each game before grading (write-once).
  perform public._capture_closing_line(p_game_ids);

  -- (1) Upsert settlements for users who DID make a pick on the given games.
  -- Effective preset = coalesce(prior graded_preset, group config, 'gamer'), frozen at
  -- first grade so re-grades never flip an already-settled week to a different preset.
  insert into public.pick_settlement (group_id, user_id, game_id, pick_id, points_delta, outcome, graded_at, graded_preset)
  select
    p.group_id,
    p.user_id,
    g.id,
    p.id,
    gp.points_delta,
    gp.outcome,
    now(),
    eff.preset
  from public.games g
  join public.picks p on p.game_id = g.id
  left join public.group_config cfg on cfg.group_id = p.group_id
  left join public.pick_settlement ps_prior
    on ps_prior.group_id = p.group_id
   and ps_prior.user_id  = p.user_id
   and ps_prior.game_id  = g.id
  left join lateral (
    select gl.spread_team_id, gl.spread_value
    from public.game_lines gl
    where gl.game_id = g.id
      and gl.source  = coalesce(cfg.line_source, 'fanduel')
      and gl.is_closing_line
    limit 1
  ) cl on true
  cross join lateral (
    select coalesce(ps_prior.graded_preset, cfg.grading_preset, 'gamer') as preset
  ) eff
  cross join lateral public.grade_pick(
    (g.final_scores->>'home')::int,
    (g.final_scores->>'away')::int,
    g.home_team_id,
    g.away_team_id,
    p.picked_team_id,
    case when eff.preset = 'house'
         then coalesce(cl.spread_team_id, p.locked_spread_team_id)
         else p.locked_spread_team_id end,
    case when eff.preset = 'house'
         then coalesce(cl.spread_value, p.locked_spread_value)
         else p.locked_spread_value end,
    p.weight::text
  ) as gp
  where g.id = any(p_game_ids)
  on conflict (group_id, user_id, game_id)
  do update set
    pick_id      = excluded.pick_id,
    points_delta = excluded.points_delta,
    outcome      = excluded.outcome,
    graded_at    = excluded.graded_at,
    graded_preset = excluded.graded_preset;

  -- (2) Upsert "missed" penalties for users who did NOT make a pick.
  -- Line is irrelevant for missed picks; graded_preset is set for consistency.
  insert into public.pick_settlement (group_id, user_id, game_id, pick_id, points_delta, outcome, graded_at, graded_preset)
  select
    gm.group_id,
    u.id,
    g.id,
    null,
    public.resolve_missed_penalty_for_game(g.id),
    'missed'::public.pick_outcome,
    now(),
    coalesce(ps_prior.graded_preset, cfg.grading_preset, 'gamer')
  from public.games g
  cross join public.group_memberships gm
  join public.users u on u.id = gm.user_id and u.role = 'player'
  left join public.group_config cfg on cfg.group_id = gm.group_id
  left join public.pick_settlement ps_prior
    on ps_prior.group_id = gm.group_id
   and ps_prior.user_id  = u.id
   and ps_prior.game_id  = g.id
  where g.id = any(p_game_ids)
    and not exists (
      select 1
      from public.picks p
      where p.group_id = gm.group_id
        and p.game_id = g.id
        and p.user_id = u.id
    )
  on conflict (group_id, user_id, game_id)
  do update set
    -- Only update if the existing settlement is also for a missed pick.
    -- This prevents overwriting a real pick that was graded out of order.
    pick_id       = excluded.pick_id,
    points_delta  = excluded.points_delta,
    outcome       = excluded.outcome,
    graded_at     = excluded.graded_at,
    graded_preset = excluded.graded_preset
  where pick_settlement.pick_id is null;
end;
$$;
