-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: functions/auth/group_active_season_settled.sql
-- group_active_season_settled: true when the group has at least one settled pick
-- in the active (max-year) season. Used to enforce the ADR-0007 grading-preset
-- season freeze: the preset may only change while a group has no settled games in
-- the active season. Shared by update_group_config (the write guard) and the group
-- page load (to disable the preset selector in the UI).
--
-- Active season = max(seasons.year); there is no is_active flag
-- (see supabase/src/views/current_season_year.sql).
create or replace function public.group_active_season_settled(p_group_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.pick_settlement ps
    join public.games   g on g.id = ps.game_id
    join public.weeks   w on w.id = g.week_id
    join public.seasons s on s.id = w.season_id
    where ps.group_id = p_group_id
      and s.year = (select max(year) from public.seasons)
  );
$$;

revoke execute on function public.group_active_season_settled(uuid) from public, anon;

-- file: functions/groups/update_group_config.sql
-- update_group_config: commissioner edits per-group league rules (issue #154).
--
-- Two dials, both on group_config:
--   * grading_preset ('house' | 'gamer') — fairness. Frozen per season (ADR-0007):
--     changeable only while the active season has no settled games for this group.
--   * scoring_rules.drop_worst_week (boolean) — forgiveness. Freely editable.
--
-- Runs as SECURITY DEFINER so it can bypass the no-client-update RLS policy on
-- group_config (upd_group_config_no_client); the is_commissioner check is the
-- trust boundary. Nullable params mean "leave unchanged"; the UI sends the full
-- desired state of both fields.
--
-- Error codes:
--   P0001  not authenticated
--   P0020  caller is not a commissioner of the group
--   P0030  grading preset is frozen (active season already has settled games)
create or replace function public.update_group_config(
  p_group_id uuid,
  p_grading_preset text default null,
  p_drop_worst_week boolean default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_caller uuid;
begin
  v_caller := auth.uid();
  if v_caller is null then
    raise exception 'not authenticated' using errcode = 'P0001';
  end if;

  if not public.is_commissioner(p_group_id) then
    raise exception 'caller is not a commissioner of this group' using errcode = 'P0020';
  end if;

  -- ADR-0007: grading_preset is frozen once the active season has settled games,
  -- but only block a *real* change. A no-op re-submit of the same preset is always
  -- allowed (the UI sends both fields every save).
  if p_grading_preset is not null
     and p_grading_preset is distinct from
         (select grading_preset from public.group_config where group_id = p_group_id)
     and public.group_active_season_settled(p_group_id) then
    raise exception 'grading preset cannot change after the season has started'
      using errcode = 'P0030';
  end if;

  update public.group_config
  set grading_preset = coalesce(p_grading_preset, grading_preset),
      scoring_rules  = case
                         when p_drop_worst_week is not null
                           then scoring_rules || jsonb_build_object('drop_worst_week', p_drop_worst_week)
                         else scoring_rules
                       end,
      updated_at     = now()
  where group_id = p_group_id;
end;
$$;

revoke execute on function public.update_group_config(uuid, text, boolean) from public, anon;

-- file: grants/group_grants.sql
-- groups / group_memberships: authenticated access is gated by RLS.
-- Strip default public/anon ACLs first so anon has no Data API access.
revoke all on public.groups from public, anon;
revoke all on public.group_memberships from public, anon;

grant select on public.groups to authenticated;
-- SELECT only: all membership writes go through SECURITY DEFINER RPCs / service role.
-- Direct client INSERT is blocked by the no-client-write policy (25_policies_groups.sql).
grant select on public.group_memberships to authenticated;

grant execute on function public.is_member(uuid) to authenticated, service_role;

-- create_group is the only insert path into groups (RLS blocks direct client
-- inserts). It is SECURITY DEFINER and enforces the create-gate internally.
grant execute on function public.create_group(text) to authenticated, service_role;

-- Commissioner management RPCs (ADR-0006, dec. 4 + 5): SECURITY DEFINER, caller-trust
-- verified internally; no direct client writes to groups.name or group_memberships.role.
grant execute on function public.rename_group(uuid, text)  to authenticated, service_role;
grant execute on function public.remove_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.promote_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.leave_group(uuid)         to authenticated, service_role;
grant execute on function public.mint_invite(uuid, integer, timestamptz) to authenticated, service_role;

-- update_group_config (issue #154): commissioner edits per-group league rules
-- (grading_preset, scoring_rules.drop_worst_week). SECURITY DEFINER; commissioner
-- check + ADR-0007 season-freeze enforced internally. No direct client writes to
-- group_config (upd_group_config_no_client policy stays intact). group_active_season_settled
-- is the shared freeze helper, also called by the group page load to lock the UI selector.
grant execute on function public.update_group_config(uuid, text, boolean) to authenticated, service_role;
grant execute on function public.group_active_season_settled(uuid)        to authenticated, service_role;

-- group_config / group_week_overrides: authenticated read gated by RLS.
-- Client writes are blocked by policy; all writes go through service_role.
revoke all on public.group_config from public, anon;
revoke all on public.group_week_overrides from public, anon;

grant select on public.group_config to authenticated;
grant select on public.group_week_overrides to authenticated;

-- group_invites: commissioners manage invites, gated by RLS; no anon access.
revoke all on public.group_invites from public, anon;

grant select, insert, update on public.group_invites to authenticated;

grant execute on function public.is_commissioner(uuid) to authenticated, service_role;
grant execute on function public.redeem_invite(text) to authenticated, service_role;
-- preview_invite: read-only display state for /join/[code]; SECURITY DEFINER so
-- invitees can preview an invite the commissioner-only RLS would otherwise hide.
grant execute on function public.preview_invite(text) to authenticated, service_role;

-- comments / reactions: members read+write their group's rows, gated by RLS.
-- Strip default anon/public ACLs first (defense in depth alongside RLS).
revoke all on public.comments  from public, anon;
revoke all on public.reactions from public, anon;

grant select, insert, delete on public.comments  to authenticated;
grant select, insert, delete on public.reactions to authenticated;
