-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0215_comments.sql
create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  game_id uuid not null references public.games(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  constraint comments_body_not_blank check (length(btrim(body)) > 0)
);

create index if not exists idx_comments_group_game
  on public.comments (group_id, game_id, created_at);

-- file: schemas/0216_reactions.sql
create table if not exists public.reactions (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  game_id uuid not null references public.games(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  constraint reactions_emoji_not_blank check (length(btrim(emoji)) > 0),
  -- one reaction per emoji per user per game per group
  constraint reactions_unique_user_game_emoji unique (group_id, user_id, game_id, emoji)
);

create index if not exists idx_reactions_group_game
  on public.reactions (group_id, game_id);

-- file: policies/10_rls_enable.sql
-- Enable RLS everywhere (deny by default)
alter table if exists public.picks       enable row level security;
alter table if exists public.pick_settlement enable row level security;
alter table if exists public.games       enable row level security;
alter table if exists public.game_lines  enable row level security;
alter table if exists public.results     enable row level security;
alter table if exists public.totals      enable row level security;
alter table if exists public.users       enable row level security;
alter table if exists public.settings    enable row level security;
alter table if exists public.audit_log   enable row level security;
alter table if exists public.weeks       enable row level security;
alter table if exists public.seasons     enable row level security;
alter table if exists public.teams       enable row level security;
alter table if exists public.groups      enable row level security;
alter table if exists public.group_memberships enable row level security;
alter table if exists public.group_config enable row level security;
alter table if exists public.group_week_overrides enable row level security;
alter table if exists public.comments  enable row level security;
alter table if exists public.reactions enable row level security;

-- file: policies/41_policies_comments_reactions.sql
-- Comments: members may post anytime; reads are gated to post-kickoff to avoid
-- revealing pick context before the game locks (mirrors the picks read gate in
-- 40_policies_picks.sql).

drop policy if exists sel_comments_member_post_kickoff on public.comments;
create policy sel_comments_member_post_kickoff
  on public.comments for select
  to authenticated
  using (
    public.is_member(group_id)
    and public.game_has_started(game_id)
  );

drop policy if exists ins_comments_own_member on public.comments;
create policy ins_comments_own_member
  on public.comments for insert
  to authenticated
  with check (
    public.is_member(group_id)
    and user_id = (select auth.uid())
  );

drop policy if exists del_comments_own on public.comments;
create policy del_comments_own
  on public.comments for delete
  to authenticated
  using (
    public.is_member(group_id)
    and user_id = (select auth.uid())
  );

-- Reactions: same post-kickoff read gate; toggle (insert + delete) allowed for members.

drop policy if exists sel_reactions_member_post_kickoff on public.reactions;
create policy sel_reactions_member_post_kickoff
  on public.reactions for select
  to authenticated
  using (
    public.is_member(group_id)
    and public.game_has_started(game_id)
  );

drop policy if exists ins_reactions_own_member on public.reactions;
create policy ins_reactions_own_member
  on public.reactions for insert
  to authenticated
  with check (
    public.is_member(group_id)
    and user_id = (select auth.uid())
  );

drop policy if exists del_reactions_own on public.reactions;
create policy del_reactions_own
  on public.reactions for delete
  to authenticated
  using (
    public.is_member(group_id)
    and user_id = (select auth.uid())
  );

-- file: grants/zz_group_grants.sql
-- groups / group_memberships: authenticated access is gated by RLS.
-- Strip default public/anon ACLs first so anon has no Data API access.
revoke all on public.groups from public, anon;
revoke all on public.group_memberships from public, anon;

grant select on public.groups to authenticated;
grant select, insert on public.group_memberships to authenticated;

grant execute on function public.is_member(uuid) to authenticated, service_role;

-- group_config / group_week_overrides: authenticated read gated by RLS.
-- Client writes are blocked by policy; all writes go through service_role.
revoke all on public.group_config from public, anon;
revoke all on public.group_week_overrides from public, anon;

grant select on public.group_config to authenticated;
grant select on public.group_week_overrides to authenticated;

-- comments / reactions: members read+write their group's rows, gated by RLS.
-- Strip default anon/public ACLs first (defense in depth alongside RLS).
revoke all on public.comments  from public, anon;
revoke all on public.reactions from public, anon;

grant select, insert, delete on public.comments  to authenticated;
grant select, insert, delete on public.reactions to authenticated;
