-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: views/group_pick_cover.sql
-- Per-pick against-the-spread cover margin for the weekly-hardware awards (issue #387).
-- One row per settled real pick (pick_id not null) in a scoring round, at the
-- (group_id, game_id, user_id) grain -- the same grain as group_pick_consensus.
--
-- cover_margin: how much the PICKED team covered the locked spread by, from that team's
-- perspective. > 0 the pick covered (a win), = 0 push, < 0 the pick did not cover (a
-- loss). Its sign therefore always agrees with the authoritative ps.outcome carried
-- alongside it. The "Bad Beat of the Week" award ranks losses by this value: the loss
-- with the greatest (closest-to-zero) cover_margin came nearest to covering.
--
-- Line used = the LOCKED line at pick time (picks.locked_spread_team_id / _value, both
-- NOT NULL since 0204_require_locks), NOT the closing line -- grading settled the pick on
-- the locked line, so the cover margin must use the same line to agree with ps.outcome.
--
-- The ATS margin formula is INLINED here rather than calling public.ats_margin_at_lock,
-- even though that function is the canonical definition (grade_pick uses it, ADR-0007).
-- Reason: the ADR-0012 from-empty drift guard (verify-src-reproduces-migrations.ts)
-- applies supabase/src/** in generator phase order -- views emit BEFORE functions, so
-- referencing ats_margin_at_lock makes the view fail to create from empty ("function does
-- not exist"). The real migration chain is unaffected (the function pre-exists from the
-- baseline). Same deliberate duplication as league_ats_base: if ats_margin_at_lock /
-- grade_pick ever changes (ADR-0007), update this expression to match.
--
-- Matviews don't support RLS; all reads are service-role-only (ADR-0013).
-- Non-scoring rounds excluded per ADR-0016 (WHERE w.is_scoring).
-- group_id leads all indexes per ADR-0002.
--
-- Materialized (ADR-0013): refreshed by public.refresh_leaderboard_stats() at the end of
-- a grading run; the unique index below lets that refresh run CONCURRENTLY.

drop materialized view if exists public.group_pick_cover;

create materialized view public.group_pick_cover as
select
  ps.group_id,
  ps.game_id,
  ps.user_id,
  u.display_name,
  s.year as season_year,
  w.week_number,
  ps.outcome,
  -- Picked-team cover margin at the locked line. Home-relative ATS margin first (mirrors
  -- public.ats_margin_at_lock / grade_pick, ADR-0007 -- see header on why this is inlined),
  -- then flip the sign for a pick on the away team so it reads from the picked team's side.
  (
    case
      when p.picked_team_id = g.home_team_id then 1
      else -1
    end
  ) * (
    ((g.final_scores ->> 'home')::int - (g.final_scores ->> 'away')::int)
      + case
          when p.locked_spread_team_id = g.home_team_id then -abs(p.locked_spread_value)
          when p.locked_spread_team_id = g.away_team_id then abs(p.locked_spread_value)
          else 0
        end
  ) as cover_margin
from public.pick_settlement ps
join public.picks p on p.id = ps.pick_id
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
where w.is_scoring
  and ps.pick_id is not null
  and (g.final_scores ->> 'home') is not null
  and (g.final_scores ->> 'away') is not null;

-- Unique natural key for REFRESH ... CONCURRENTLY (ADR-0013).
-- group_id leads to serve the (group_id, season_year) read filter (ADR-0002).
create unique index if not exists uq_group_pick_cover
  on public.group_pick_cover (group_id, user_id, game_id);

-- Secondary index for the weekly-award season read.
create index if not exists idx_group_pick_cover_group_season
  on public.group_pick_cover (group_id, season_year);

revoke all on public.group_pick_cover from public, anon, authenticated;
grant select on public.group_pick_cover to service_role;

-- file: functions/stats/refresh_leaderboard_stats.sql
-- Refresh the materialized leaderboard/stats views after a grading run (issue #191).
--
-- SECURITY DEFINER so it executes as the matview owner (postgres) -- REFRESH MATERIALIZED
-- VIEW requires ownership, and the calling service_role is not the owner. search_path is
-- pinned empty with every object schema-qualified.
--
-- CONCURRENTLY keeps each view readable by in-flight requests during the refresh and is
-- transaction-safe inside this function (unlike CREATE INDEX CONCURRENTLY, REFRESH ...
-- CONCURRENTLY does not self-manage transactions); it requires the unique index each
-- matview declares in supabase/src/views/.
--
-- Called by the server grading helpers (src/lib/server/grading.ts) after grade_game /
-- grade_week / grade_season succeed. A refresh failure is logged there but does NOT fail
-- the grade: the settlement write already committed and a stale matview self-heals on the
-- next grade. EXECUTE is granted to service_role by grants/admin_grants.sql (blanket
-- grant on all functions); the closed-by-default ACL guard strips only the PUBLIC grant.
create or replace function public.refresh_leaderboard_stats()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  refresh materialized view concurrently public.leaderboard_season_totals;
  refresh materialized view concurrently public.stats_season_trend;
  refresh materialized view concurrently public.stats_accuracy_by_team;
  refresh materialized view concurrently public.stats_accuracy_by_weight;
  refresh materialized view concurrently public.stats_head_to_head;
  refresh materialized view concurrently public.stats_head_to_head_alltime;
  refresh materialized view concurrently public.stats_alltime_totals;
  refresh materialized view concurrently public.stats_accuracy_by_team_alltime;
  refresh materialized view concurrently public.stats_accuracy_by_weight_alltime;
  refresh materialized view concurrently public.group_pick_consensus;
  -- Per-pick cover margin for the weekly-hardware "Bad Beat of the Week" award (#387).
  -- Same pick_settlement rows every other per-user stat is driven by, so this is its point.
  refresh materialized view concurrently public.group_pick_cover;
  refresh materialized view concurrently public.stats_accuracy_by_line_side;
  refresh materialized view concurrently public.stats_pick_streaks;
  -- Per-user situational ATS base (#502): pick-grain classification (primetime / home-away /
  -- spread bucket / divisional) the "Your edge" panel reads via stats_situational_splits. Driven
  -- by the same pick_settlement rows every other per-user stat is, so this is its refresh point.
  refresh materialized view concurrently public.stats_situational_base;
  -- Two-sided per-user team book (#564): backed + faded ATS records per team, season + all-time.
  -- Driven by the same pick_settlement rows every other per-user stat is, so this is its refresh
  -- point. Backed rows duplicate stats_accuracy_by_team's numbers; the fade side is net-new.
  refresh materialized view concurrently public.stats_team_book;
  refresh materialized view concurrently public.stats_team_book_alltime;
  -- League-wide team ATS facts (#406). Group-independent and driven by games/game_lines
  -- rather than pick_settlement, but the same grading run that settles picks is also when
  -- games go final + closing lines are captured, so this is the correct invalidation point.
  refresh materialized view concurrently public.league_ats_base;
end;
$$;

comment on function public.refresh_leaderboard_stats() is
  'Refreshes the 17 leaderboard/stats materialized views CONCURRENTLY (issues #191/#280/#294/#296/#317/#387/#406/#502/#564). '
  'Called after each grading run by src/lib/server/grading.ts.';
