-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;

-- retired sources
-- retired: functions/groups/set_competition_start.sql
drop function if exists public.set_competition_start(uuid, timestamptz);

-- retired: functions/groups/competition_start_frozen.sql
drop function if exists public.competition_start_frozen(uuid);

-- signature-adjustment drops
-- drop for signature change: functions/groups/create_group.sql
drop function if exists public.create_group(text, timestamptz);

-- file: functions/groups/create_group.sql
-- create_group: gated, atomic group creation (ADR-0006, decision 3).
--
-- The whole function runs in a single transaction, so a failure at any step
-- (gate rejection, constraint violation) leaves no orphan group, config, or
-- membership. SECURITY DEFINER lets it write groups / group_config /
-- group_memberships even though those tables block direct client writes; the
-- trust check is the gate below, keyed on the caller's auth.uid().
--
-- Competition start (ADR-0039, superseding ADR-0037 ruling 5): a new league always begins
-- at now(). Joining is the only participation boundary, so there is no start-week argument
-- to carry — groups.competition_starts_at keeps its `not null default now()` and the
-- creator's own membership joined_at defaults to the same instant, which makes
-- greatest(competition_starts_at, joined_at) = joined_at for every member. Games that
-- kicked off before a member joined never count against them; everything from their join
-- forward does, immediately.
--
-- Error codes (surfaced to the caller as PostgrestError.code):
--   P0001  not authenticated
--   P0010  group name is required
--   P0011  group name too long
--   P0012  group creation not enabled for this account (gated mode)
create or replace function public.create_group(p_name text)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id  uuid;
  v_name     text;
  v_mode     text;
  v_capable  boolean;
  v_group_id uuid;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'not authenticated' using errcode = 'P0001';
  end if;

  -- Validate name: non-empty, length-bounded (mirrors groups_name_max_len).
  v_name := btrim(coalesce(p_name, ''));
  if length(v_name) = 0 then
    raise exception 'group name is required' using errcode = 'P0010';
  end if;
  if length(v_name) > 60 then
    raise exception 'group name too long' using errcode = 'P0011';
  end if;

  -- Gate: global mode, then per-user capability when gated.
  select group_creation_mode into v_mode
  from public.settings
  where id = true
  limit 1;
  v_mode := coalesce(v_mode, 'gated');

  if v_mode <> 'open' then
    select can_create_group into v_capable
    from public.users
    where id = v_user_id;

    if not coalesce(v_capable, false) then
      raise exception 'group creation is not enabled for this account'
        using errcode = 'P0012';
    end if;
  end if;

  -- Atomic create: group, then its seeded config, then the creator as commissioner.
  -- competition_starts_at is left to its column default (now()), which is the only start a
  -- league can have — no already-played game is ever eligible for a brand-new league.
  insert into public.groups (name)
  values (v_name)
  returning id into v_group_id;

  -- Seed group_config from global settings, reusing the shape established by
  -- 0213_seed_original_group_config.sql so every group starts consistently.
  insert into public.group_config (group_id, line_source, scoring_rules)
  values (
    v_group_id,
    'fanduel',
    jsonb_build_object(
      'missed_pick_penalty',
      coalesce((select missed_pick_penalty from public.settings where id = true limit 1), -1)
    )
  );

  insert into public.group_memberships (group_id, user_id, role, status)
  values (v_group_id, v_user_id, 'commissioner', 'active');

  return v_group_id;
end;
$$;

revoke execute on function public.create_group(text) from public, anon;

-- file: grants/group_grants.sql
-- groups / group_memberships: authenticated access is gated by RLS.
-- Strip default public/anon ACLs first so anon has no Data API access.
revoke all on public.groups from public, anon;
revoke all on public.group_memberships from public, anon;

grant select on public.groups to authenticated;
-- SELECT only: all membership writes go through SECURITY DEFINER RPCs / service role.
-- Direct client INSERT is blocked by the no-client-write policy (25_policies_groups.sql).
grant select on public.group_memberships to authenticated;

grant execute on function public.is_member(uuid) to authenticated, service_role;

-- create_group is the only insert path into groups (RLS blocks direct client
-- inserts). It is SECURITY DEFINER and enforces the create-gate internally. One argument
-- only: a new league always starts at now() (ADR-0039), so there is no start-week to pass.
grant execute on function public.create_group(text) to authenticated, service_role;

-- Commissioner management RPCs (ADR-0006, dec. 4 + 5): SECURITY DEFINER, caller-trust
-- verified internally; no direct client writes to groups.name or group_memberships.role.
grant execute on function public.rename_group(uuid, text)  to authenticated, service_role;
grant execute on function public.remove_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.promote_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.leave_group(uuid)         to authenticated, service_role;
grant execute on function public.mint_invite(uuid, integer, timestamptz) to authenticated, service_role;

-- update_group_config (issue #154): commissioner edits per-group league rules
-- (grading_preset, scoring_rules.drop_worst_week / drop_worst_week_start_year,
-- ADR-0018). SECURITY DEFINER; commissioner check + ADR-0007 season-freeze
-- enforced internally. No direct client writes to group_config
-- (upd_group_config_no_client policy stays intact). group_active_season_settled
-- is the shared freeze helper, also called by the group page load to lock the UI selector.
grant execute on function public.update_group_config(uuid, text, boolean, int) to authenticated, service_role;
grant execute on function public.group_active_season_settled(uuid)        to authenticated, service_role;

-- group_config / group_week_overrides: authenticated read gated by RLS.
-- Client writes are blocked by policy; all writes go through service_role.
revoke all on public.group_config from public, anon;
revoke all on public.group_week_overrides from public, anon;

grant select on public.group_config to authenticated;
grant select on public.group_week_overrides to authenticated;

-- group_invites: commissioners manage invites, gated by RLS; no anon access.
revoke all on public.group_invites from public, anon;

grant select, insert, update on public.group_invites to authenticated;

grant execute on function public.is_commissioner(uuid) to authenticated, service_role;
grant execute on function public.redeem_invite(text) to authenticated, service_role;
-- preview_invite: read-only display state for /join/[code]; SECURITY DEFINER so
-- invitees can preview an invite the commissioner-only RLS would otherwise hide.
grant execute on function public.preview_invite(text) to authenticated, service_role;

-- comments / reactions: members read+write their group's rows, gated by RLS.
-- Strip default anon/public ACLs first (defense in depth alongside RLS).
revoke all on public.comments  from public, anon;
revoke all on public.reactions from public, anon;

grant select, insert, delete on public.comments  to authenticated;
grant select, insert, delete on public.reactions to authenticated;

-- ai_recaps: members read their group's rows; no client writes (service role only).
-- ADR-0008 (AI output is group-scoped, writes via service role batch lane).
revoke all on public.ai_recaps from public, anon;
grant select on public.ai_recaps to authenticated;

-- season_wrapped: members read their group's rows; no client writes (service role only).
-- ADR-0008 (AI output is group-scoped, writes via service role batch lane).
revoke all on public.season_wrapped from public, anon;
grant select on public.season_wrapped to authenticated;

-- ai_badge_flavors: members read their group's rows; no client writes (service role only).
-- ADR-0008 (AI output is group-scoped, writes via service role batch lane).
revoke all on public.ai_badge_flavors from public, anon;
grant select on public.ai_badge_flavors to authenticated;

-- update_group_recap_settings (issue #301): commissioner sets AI recap tone (spice)
-- and enable/disable. SECURITY DEFINER; commissioner check enforced internally.
-- No direct client writes to group_config (upd_group_config_no_client stays intact).
grant execute on function public.update_group_recap_settings(uuid, text, boolean) to authenticated, service_role;

-- update_recap_opt_out (issue #301): any member toggles their own AI recap opt-out.
-- SECURITY DEFINER (bypasses the group_memberships with_check role = 'member' guard
-- so commissioners can also opt out). user_id = auth.uid() is the trust boundary.
grant execute on function public.update_recap_opt_out(uuid, boolean) to authenticated, service_role;

-- recap_seen (issue #302): the player writes their own seen-marker directly on
-- flash dismiss, gated by RLS (51_policies_recap_seen.sql) rather than a
-- SECURITY DEFINER RPC — mirrors push_subscriptions' self-service grant shape.
revoke all on public.recap_seen from public, anon;
grant select, insert, update on public.recap_seen to authenticated;

-- wrapped_seen (issue #548): same self-service shape as recap_seen, for the
-- once-per-season Wrapped flash seen-marker.
revoke all on public.wrapped_seen from public, anon;
grant select, insert, update on public.wrapped_seen to authenticated;
