-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0000_function_acl_guard.sql
-- Function ACL guard for the closed-by-default baseline (paired with 0001_role_baseline).
--
-- Lives in schemas/ (not functions/) and sorts FIRST so the event trigger that invokes it
-- -- created in 0001_role_baseline.sql, still in the schemas phase -- is active before the
-- functions phase creates any application function. That ordering is what lets the
-- from-empty history squash (ADR-0012) end up closed: every app function is created after
-- this guard exists, so each one is stripped of PUBLIC execute as it is created.
--
-- Why a trigger instead of default privileges: PostgreSQL's built-in default grants
-- EXECUTE on every new function to PUBLIC, and in this Supabase setup that built-in grant
-- cannot be subtracted via `alter default privileges ... revoke execute on functions from
-- public` (verified empirically -- an owner-only function default collapses back to the
-- built-in and re-grants PUBLIC). Revoking PUBLIC per-creation is the reliable mechanism.
--
-- SECURITY DEFINER (owned by postgres) so it can always revoke; search_path is pinned
-- empty with catalog objects schema-qualified. The trigger's WHEN clause (in 0001)
-- restricts firing to function-creation events, so the REVOKE below never re-enters it.
-- Only the implicit PUBLIC grant is removed; explicit authenticated/service_role grants
-- a function's own file adds afterward survive. Backstopped by the pgTAP authz matrix
-- (tests/021_function_grant_baseline.sql).
create or replace function public._close_new_fn_acl()
returns event_trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  r record;
begin
  for r in
    select object_identity
    from pg_catalog.pg_event_trigger_ddl_commands()
    where schema_name = 'public'
  loop
    execute pg_catalog.format('revoke execute on function %s from public', r.object_identity);
  end loop;
end
$fn$;

comment on function public._close_new_fn_acl() is
  'Closed-by-default baseline (ADR-0011): invoked by the _close_new_fn_acl event trigger '
  'to strip PUBLIC execute from every new public function, because Supabase will not honor '
  'a default-privilege revoke of the built-in grant. Backstopped by pgTAP tests/021.';

-- file: schemas/0001_role_baseline.sql
-- Closed-by-default role baseline. See ADR-0011 (design) and ADR-0012 (rollout).
--
-- This file is the SINGLE place the `public` schema is closed by default. It lives in
-- schemas/ with a low numeric prefix so the generator emits it early -- before any
-- function, table, policy, or grant file. Every other grant file (player_grants,
-- admin_grants, zz_*) and every function's own grant runs in a LATER generator phase and
-- selectively RE-OPENS specific objects to specific roles, so nothing here can clobber an
-- intended grant and no `zz_` ordering hack is needed.
--
-- TABLES are closed by default privileges. A postgres-created table in `public` is born
-- owner+service_role only (the built-in table default is owner-only) -- verified
-- empirically. The `alter default privileges ... revoke all on tables from anon,
-- authenticated` keeps the postgres table default explicitly closed to the two client
-- roles; each table's grant file re-opens exactly what it needs.
--
-- FUNCTIONS cannot be closed by default privileges here (the built-in PUBLIC execute grant
-- cannot be subtracted -- see 0000_function_acl_guard.sql). So function closure is done two
-- ways: (1) the `_close_new_fn_acl` event trigger activated below strips PUBLIC execute
-- from every NEW function (future migrations and the from-empty squash); and (2) the
-- one-time `revoke execute on all functions ... from public` at the bottom closes functions
-- that ALREADY exist when this baseline first runs (the trigger only fires on creation).
-- Both revoke only the implicit PUBLIC grant; explicit grants survive. The pgTAP authz
-- matrix (tests/021) fails CI if any `public` function is ever PUBLIC-executable.
--
-- ENUM/type USAGE is deliberately left alone: it was empirically verified inert at runtime
-- in this schema (column reads/writes, casts, and enum-arg function calls all succeed with
-- USAGE stripped from both PUBLIC and the role), authenticated/anon have no CREATE on
-- `public` to exploit it at DDL time, and (lacking a `REVOKE ... ON ALL TYPES` form)
-- revoking it would break the squash for no security gain.

-- Schema resolution: the three app roles may resolve names in `public` (USAGE only, never
-- CREATE). service_role's table/function access comes from admin_grants.sql.
grant usage on schema public to anon, authenticated, service_role;
revoke create on schema public from public, anon, authenticated;

-- Tables postgres creates from here on are born closed to the client roles.
alter default privileges for role postgres in schema public
  revoke all on tables from anon, authenticated;

-- Activate the function ACL guard from 0000_function_acl_guard.sql. WHEN restricts firing
-- to function-creation events so the guard's own REVOKE never re-enters it. drop-if-exists
-- keeps the statement idempotent across resets.
drop event trigger if exists _close_new_fn_acl;
create event trigger _close_new_fn_acl
  on ddl_command_end
  when tag in ('CREATE FUNCTION')
  execute function public._close_new_fn_acl();

-- One-time closure of objects that already exist when this first runs (no-ops from empty;
-- also closes _close_new_fn_acl itself, created before its trigger). Explicit role grants
-- from the re-open files survive -- only implicit PUBLIC / auto-anon access is cut.
revoke execute on all functions in schema public from public;
revoke all on all tables in schema public from public, anon;

-- file: functions/_private/game_has_started.sql
-- Helper: has the game started?
create or replace function public.game_has_started(p_game_id uuid)
returns boolean
language sql
stable
as $$
  select (now() >= g.commence_time) from public.games g where g.id = p_game_id
$$;

-- Reachable by `authenticated` via the picks / comments / reactions RLS policies and
-- unlock_pick_all_groups (SECURITY INVOKER); the caller needs EXECUTE. The closed-by-
-- default baseline (ADR-0011) revokes PUBLIC, so this grant is the sole path.
grant execute on function public.game_has_started(uuid)
  to authenticated, service_role;

-- file: functions/_private/get_final_week_unlimited_allin.sql
-- Returns the final_week_unlimited_allin gameplay flag.
-- SECURITY DEFINER so lock_pick (SECURITY INVOKER) can read settings
-- without granting authenticated users broad access to the settings table.
create or replace function public._get_final_week_unlimited_allin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce(
    (select s.final_week_unlimited_allin from public.settings s where s.id = true),
    true
  );
$$;

-- Reachable by `authenticated` through lock_pick / lock_pick_all_groups (SECURITY
-- INVOKER), so the caller needs EXECUTE even though this is SECURITY DEFINER. The
-- closed-by-default baseline (ADR-0011) revokes PUBLIC, so this grant is the sole path.
grant execute on function public._get_final_week_unlimited_allin()
  to authenticated, service_role;

-- file: functions/auth/is_admin.sql
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'admin'
  );
$$;

-- Reachable by `authenticated` via RLS policies on settings / audit_log / cron_run_log;
-- the caller needs EXECUTE even though only admins pass the check inside. The closed-by-
-- default baseline (ADR-0011) revokes PUBLIC, so this grant is the sole path.
grant execute on function public.is_admin() to authenticated, service_role;

-- file: grants/player_grants.sql
-- =========================
-- PLAYER (authenticated, non-admin)
-- =========================

-- Basic resolution (also granted by the closed-by-default baseline; restated here so
-- this file reads on its own).
grant usage on schema public to authenticated;

-- NOTE: function access starts closed in schemas/0001_role_baseline.sql, which revokes
-- EXECUTE from PUBLIC (the implicit grant authenticated actually rode) and sets the
-- born-closed default for future functions. There is intentionally no blanket
-- `revoke execute ... from authenticated` here: it never closed the real door (PUBLIC
-- did), and -- because this file is emitted in the grants phase, after the functions
-- phase -- it would strip the explicit per-function grants made in the function source
-- files (the closure helpers, get-only RPCs, etc.). Each function re-opens itself.

-- Enums used by player RPCs
grant usage on type public.weight_enum to authenticated;
grant usage on type public.side_enum  to authenticated;

-- Defense in depth: strip Supabase's default anon/PUBLIC ACL on every table that has
-- no anon RLS policy. Supabase auto-grants ALL on new public tables to anon/PUBLIC;
-- RLS already blocks rows, but revoking the grant closes Data API reachability too
-- (the same revoke-before-grant pattern already applied to cron_run_log /
-- push_subscriptions / notification_log below and the group-owned tables). Runs before
-- the explicit `authenticated` grants below, which survive (revoke targets only
-- anon/PUBLIC); service_role keeps access via admin_grants.sql.
revoke all on
  public.games, public.game_lines, public.results, public.totals,
  public.users, public.weeks, public.seasons, public.teams,
  public.picks, public.pick_settlement, public.settings, public.audit_log
from public, anon;

-- Base table privileges (RLS still enforces row/column rules)
grant select on public.games,
               public.game_lines,
               public.results,
               public.totals,
               public.users,
               public.weeks,
               public.seasons,
               public.teams
to authenticated;

-- Picks CRUD the player needs; RLS gates who/when
grant select, insert, update on public.picks to authenticated;
grant select on public.pick_settlement to authenticated;

-- Settings & audit:
-- Grant SELECT so admins (who are also 'authenticated') can read via RLS (is_admin()).
-- Do NOT grant write widely; writes happen via SECURITY DEFINER admin RPCs.
grant select on public.settings, public.audit_log to authenticated;

-- cron_run_log: admin-only reads via RLS (is_admin()); writes come from service role.
-- Supabase's default ACL auto-grants ALL on new public tables to anon/authenticated,
-- so strip anon (and PUBLIC) first -- defense in depth alongside RLS, mirroring the
-- revoke/grant pattern on public.picks_status_view_user. authenticated keeps SELECT,
-- gated to admins by the admin_sel_cron_run_log policy.
revoke all on public.cron_run_log from public, anon;
grant select on public.cron_run_log to authenticated;

-- push_subscriptions: owners manage their own rows; RLS gates which rows.
-- Strip the default anon/PUBLIC ACL first (defense in depth alongside RLS).
revoke all on public.push_subscriptions from public, anon;
grant select, insert, update, delete on public.push_subscriptions to authenticated;

-- notification_log: owners read their own rows via RLS; writes come from service role.
revoke all on public.notification_log from public, anon;
grant select on public.notification_log to authenticated;

-- Player-facing RPCs whose source files do not append their own grant. The baseline
-- revokes EXECUTE from PUBLIC, so these explicit grants are the sole path for
-- authenticated. lock_pick/unlock_pick/is_member live here (rather than self-granting in
-- their function files) by long-standing convention; keep them co-located.
grant execute on function public.lock_pick(uuid, public.side_enum, public.weight_enum, text)
  to authenticated, service_role;
grant execute on function public.unlock_pick(uuid)
  to authenticated, service_role;
grant execute on function public.is_member(uuid)
  to authenticated, service_role;

-- NOTE: The remaining RPCs follow the convention of appending their own EXECUTE
-- grants in their own source files:
--   - public get-only RPCs (e.g., get_active_week_games): GRANT to anon, authenticated
--   - admin RPCs: handled via service_role or guarded is_admin() (see admin_grants.sql)
