-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: indexes/idx_group_memberships_group_role_joined.sql
-- Keyset-pagination index for the group members list (issue #152, ADR-0002 query
-- discipline: group-owned reads lead with a group_id-prefixed index). Matches the
-- group_id equality filter plus the exact ordering used by public.group_members_page:
-- role, joined_at, user_id (all ascending), with user_id the unique tie-breaker that
-- makes the keyset cursor total. The existing idx_group_memberships_user_group
-- (user_id, group_id) serves per-user lookups but is NOT group_id-leading, so it
-- cannot serve a group-scoped, ordered member page. EXPLAIN: Index Scan, no Sort.
create index if not exists idx_group_memberships_group_role_joined
  on public.group_memberships (group_id, role, joined_at, user_id);

-- file: views/leaderboard_season_totals.sql
-- One row per user per (group, season) with totals + ranks.
-- Drop-worst-week (ADR-0005): when a group enables
-- group_config.scoring_rules.drop_worst_week, a player's single lowest-scoring
-- week is omitted from total_points once they have 2+ settled weeks. The drop
-- forgives points only -- the W/L/push record and tie-breakers still count the
-- dropped week.
-- Materialized (issue #191): season standings are recomputed only at the end of a
-- grading run via public.refresh_leaderboard_stats(), not on every page load. The
-- query body below is unchanged from the prior regular view.
-- DROP MATERIALIZED VIEW (not DROP VIEW): once #191 converted this to a matview, any
-- later re-emission of this file (e.g. issue #152's keyset index below) runs against a
-- DB where it is already a matview, and `drop view` errors on a matview. IF EXISTS
-- keeps the from-empty baseline a clean no-op.
drop materialized view if exists public.leaderboard_season_totals;

create materialized view public.leaderboard_season_totals as
with season_rows as (
select
ps.user_id,
u.display_name,
u.avatar_key,
s.year as season_year,
w.id as week_id,
ps.points_delta,
ps.outcome,
ps.group_id
from public.pick_settlement ps
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
)
-- Decision-level season aggregates: raw points and the W/L/push record.
-- Record counts intentionally include every week, even one later dropped
-- (ADR-0005: drop-worst-week forgives points, not record).
, totals as (
select
user_id,
display_name,
avatar_key,
season_year,
group_id,
sum(points_delta)::int as raw_total,
count(*)::int as decisions,
count(*) filter (where outcome = 'win')::int as wins,
count(*) filter (where outcome = 'loss')::int as losses,
count(*) filter (where outcome = 'push')::int as pushes,
count(*) filter (where outcome = 'missed')::int as missed
from season_rows
group by user_id, display_name, avatar_key, season_year, group_id
)
-- Week-level points per player, used to find the single lowest week.
, week_points as (
select
user_id,
season_year,
group_id,
week_id,
sum(points_delta)::int as wk_points
from season_rows
group by user_id, season_year, group_id, week_id
)
-- Per player: count of settled weeks and the lowest week's points.
, week_summary as (
select
user_id,
season_year,
group_id,
count(*)::int as weeks_played,
min(wk_points)::int as lowest_week_points
from week_points
group by user_id, season_year, group_id
)
-- Resolved drop-worst-week flag per group (default false when no config row).
, group_drop as (
select
g.id as group_id,
coalesce((gc.scoring_rules ->> 'drop_worst_week')::boolean, false) as drop_worst_week
from public.groups g
left join public.group_config gc on gc.group_id = g.id
)
, adjusted as (
select
t.user_id,
t.display_name,
t.avatar_key,
t.season_year,
t.group_id,
t.decisions,
t.wins,
t.losses,
t.pushes,
t.missed,
-- Drop the single lowest week's points only when the group enables it AND the
-- player has 2+ settled weeks (ADR-0005). Otherwise the raw total stands.
case
when gd.drop_worst_week and ws.weeks_played >= 2
then t.raw_total - ws.lowest_week_points
else t.raw_total
end::int as total_points
from totals t
join week_summary ws
on ws.user_id = t.user_id
and ws.season_year = t.season_year
and ws.group_id = t.group_id
join group_drop gd on gd.group_id = t.group_id
)
select
a.user_id,
a.display_name,
a.season_year,
a.total_points,
a.decisions,
a.wins,
a.losses,
a.pushes,
a.missed,
dense_rank() over (
partition by a.group_id, a.season_year
order by a.total_points desc, a.wins desc, a.pushes desc
) as rank,
a.group_id,
a.avatar_key
from adjusted a;

-- Unique natural key. Required for REFRESH MATERIALIZED VIEW CONCURRENTLY and also
-- serves the (group_id, season_year) read filter in getSeasonLeaderboard.
create unique index if not exists uq_leaderboard_season_totals
  on public.leaderboard_season_totals (group_id, user_id, season_year);

-- Keyset-pagination index (issue #152, ADR-0002 query discipline). Matches the
-- (group_id, season_year) equality filter plus the exact display ordering used by
-- public.leaderboard_season_page: total_points/wins/pushes descending, with user_id
-- as the unique descending tie-breaker so the keyset cursor is total. Column order
-- and direction mirror that ORDER BY so the keyset row-value comparison and the page
-- limit are both served by a single index range scan (EXPLAIN: Index Scan, no Sort).
create index if not exists idx_leaderboard_season_totals_keyset
  on public.leaderboard_season_totals
  (group_id, season_year, total_points desc, wins desc, pushes desc, user_id desc);

-- Materialized views are NOT covered by the schema-wide `grant select on all tables`
-- (that grant excludes matviews), so service_role is granted explicitly. MVs cannot
-- carry RLS; every read goes through the service-role client, which filters by group_id.
revoke all on public.leaderboard_season_totals from public, anon, authenticated;
grant select on public.leaderboard_season_totals to service_role;

-- file: functions/groups/group_members_page.sql
-- group_members_page: one bounded, keyset-paginated page of a group's members joined
-- to their user profile (issue #152). Returns rows in display order -- role, then
-- joined_at, then user_id -- all ascending, with user_id the unique tie-breaker so
-- the cursor is a total order and pages are stable under inserts. Served by
-- idx_group_memberships_group_role_joined.
--
-- Keyset cursor: pass the last row of the previous page as
-- (p_after_role, p_after_joined_at, p_after_user_id); all NULL for the first page.
-- The row-value comparison `(...) > (...)` works because the ORDER BY is ascending on
-- every cursor column. Enum role uses its declared order (commissioner before member).
--
-- SECURITY INVOKER, service_role-only -- the group page load reads members via the
-- service-role client and passes the caller's own group_id (the trust boundary,
-- ADR-0002). Not granted to authenticated; service_role EXECUTE comes from the
-- blanket admin grant. No status filter: this mirrors the previous inline query so
-- existing single-group output is unchanged.
create or replace function public.group_members_page(
  p_group_id uuid,
  p_limit int default 50,
  p_after_role public.group_membership_role default null,
  p_after_joined_at timestamptz default null,
  p_after_user_id uuid default null
)
returns table (
  group_id uuid,
  user_id uuid,
  role public.group_membership_role,
  joined_at timestamptz,
  display_name text,
  avatar_key text
)
language sql
stable
as $$
  select
    m.group_id,
    m.user_id,
    m.role,
    m.joined_at,
    u.display_name,
    u.avatar_key
  from public.group_memberships m
  join public.users u on u.id = m.user_id
  where m.group_id = p_group_id
    and (
      p_after_user_id is null
      or (m.role, m.joined_at, m.user_id)
         > (p_after_role, p_after_joined_at, p_after_user_id)
    )
  order by m.role, m.joined_at, m.user_id
  limit least(greatest(coalesce(p_limit, 50), 1), 200);
$$;

comment on function public.group_members_page(uuid, int, public.group_membership_role, timestamptz, uuid) is
  'Keyset-paginated page of a group''s members + profile (issue #152). service_role-only; '
  'the server passes the caller''s own group_id as the trust boundary (ADR-0002).';

-- file: functions/stats/group_season_years.sql
-- group_season_years: the distinct season years a group has standings for, newest
-- first (issue #152). Backs getAvailableSeasons, which previously loaded every
-- leaderboard_season_totals row for the group (members x seasons) just to derive the
-- distinct year list -- an unbounded read as groups grow. Pushing the DISTINCT into
-- SQL bounds the result to the (small) number of seasons.
--
-- SECURITY INVOKER, service_role-only -- same trust model as leaderboard_season_page:
-- the source matview is service_role-only (#191) and the server passes the caller's
-- own group_id. service_role EXECUTE comes from the blanket admin grant.
create or replace function public.group_season_years(p_group_id uuid)
returns setof int
language sql
stable
as $$
  select distinct season_year
  from public.leaderboard_season_totals
  where group_id = p_group_id
  order by season_year desc;
$$;

comment on function public.group_season_years(uuid) is
  'Distinct season years a group has standings for, newest first (issue #152). '
  'service_role-only; bounds the season-dropdown read.';

-- file: functions/stats/leaderboard_season_page.sql
-- leaderboard_season_page: one bounded, keyset-paginated page of a group's season
-- standings (issue #152). Reads the leaderboard_season_totals materialized view
-- (#191) and returns rows in display order -- total_points/wins/pushes descending,
-- with user_id as the unique descending tie-breaker so the cursor is a total order
-- and pages are stable under inserts. Served by idx_leaderboard_season_totals_keyset.
--
-- Keyset cursor: pass the last row of the previous page as
-- (p_after_total_points, p_after_wins, p_after_pushes, p_after_user_id). All four are
-- NULL for the first page. The row-value comparison `(...) < (...)` works because the
-- ORDER BY is descending on every cursor column, so "after the cursor" == "tuple is
-- lexicographically less than the cursor tuple".
--
-- SECURITY INVOKER by design. The source matview is granted to service_role ONLY
-- (#191) -- it holds every group's rows and carries no RLS -- so this function is
-- reachable only by the service-role server client, which is the group_id trust
-- boundary (it passes the caller's own group from the session). It is intentionally
-- NOT granted to authenticated: that would let any signed-in user read other groups'
-- standings by passing an arbitrary p_group_id, violating ADR-0002 cross-group denial.
-- service_role EXECUTE comes from the blanket grant in grants/admin_grants.sql; the
-- closed-by-default ACL guard strips the implicit PUBLIC grant.
create or replace function public.leaderboard_season_page(
  p_group_id uuid,
  p_season_year int,
  p_limit int default 50,
  p_after_total_points int default null,
  p_after_wins int default null,
  p_after_pushes int default null,
  p_after_user_id uuid default null
)
returns setof public.leaderboard_season_totals
language sql
stable
as $$
  select *
  from public.leaderboard_season_totals
  where group_id = p_group_id
    and season_year = p_season_year
    and (
      p_after_user_id is null
      or (total_points, wins, pushes, user_id)
         < (p_after_total_points, p_after_wins, p_after_pushes, p_after_user_id)
    )
  order by total_points desc, wins desc, pushes desc, user_id desc
  limit least(greatest(coalesce(p_limit, 50), 1), 200);
$$;

comment on function public.leaderboard_season_page(uuid, int, int, int, int, int, uuid) is
  'Keyset-paginated page of a group''s season standings (issue #152). service_role-only; '
  'the server passes the caller''s own group_id as the trust boundary (ADR-0002).';
