-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0200_03_teams.sql
-- TEAMS
create table if not exists public.teams (
  id integer generated by default as identity primary key,
  league text not null default 'NFL',
  external_key text unique, -- e.g., 'PHI'
  name text not null,
  short_name text not null,
  division text,   -- 'East' | 'North' | 'South' | 'West' (NFL only; null for other leagues)
  conference text  -- 'AFC' | 'NFC'                        (NFL only; null for other leagues)
);

-- Additive for existing DBs (#425, League tab v2): the generator re-emits this whole file
-- into the migration, and the idempotent table definition above no-ops on the already-present
-- teams table, so the new columns must be added explicitly to reach prod. Values are seeded
-- for the 32 NFL teams by 0229_seed_team_divisions.sql; a divisional matchup
-- (league_ats_divisional) is defined as same conference AND same division.
alter table public.teams add column if not exists division text;
alter table public.teams add column if not exists conference text;

-- file: schemas/0229_seed_team_divisions.sql
-- Seed division + conference for the 32 NFL teams (#425, League tab v2 epic).
--
-- Idempotent UPDATE keyed by external_key: safe to re-run (the generator re-emits a file's
-- full content whenever it changes) and safe to apply from empty -- with no team rows it
-- updates 0 rows, which keeps the ADR-0012 from-empty reproduce guard green. `league = 'NFL'`
-- scopes the seed so any non-NFL team keeps null division/conference (matching the epic's
-- non-goal). Runs after 0200_03_teams.sql (alphabetically later in schemas/), so the columns
-- it sets already exist. Consumed by league_ats_divisional -- a divisional matchup is same
-- conference AND same division -- and available to future League tab UI.
update public.teams t
set division = v.division,
    conference = v.conference
from (values
  ('BUF', 'East', 'AFC'),
  ('MIA', 'East', 'AFC'),
  ('NE', 'East', 'AFC'),
  ('NYJ', 'East', 'AFC'),
  ('BAL', 'North', 'AFC'),
  ('CIN', 'North', 'AFC'),
  ('CLE', 'North', 'AFC'),
  ('PIT', 'North', 'AFC'),
  ('HOU', 'South', 'AFC'),
  ('IND', 'South', 'AFC'),
  ('JAX', 'South', 'AFC'),
  ('TEN', 'South', 'AFC'),
  ('DEN', 'West', 'AFC'),
  ('KC', 'West', 'AFC'),
  ('LV', 'West', 'AFC'),
  ('LAC', 'West', 'AFC'),
  ('DAL', 'East', 'NFC'),
  ('NYG', 'East', 'NFC'),
  ('PHI', 'East', 'NFC'),
  ('WAS', 'East', 'NFC'),
  ('CHI', 'North', 'NFC'),
  ('DET', 'North', 'NFC'),
  ('GB', 'North', 'NFC'),
  ('MIN', 'North', 'NFC'),
  ('ATL', 'South', 'NFC'),
  ('CAR', 'South', 'NFC'),
  ('NO', 'South', 'NFC'),
  ('TB', 'South', 'NFC'),
  ('ARI', 'West', 'NFC'),
  ('LAR', 'West', 'NFC'),
  ('SF', 'West', 'NFC'),
  ('SEA', 'West', 'NFC')
) as v(external_key, division, conference)
where t.external_key = v.external_key
  and t.league = 'NFL';

-- file: views/league_ats_base.sql
-- League-wide, spreads-only NFL team ATS facts at the atomic (game, team-perspective)
-- grain: exactly two rows per qualifying game (one for the home team, one for the away
-- team). Every /league aggregate view and the pick-card ATS nugget (issue #406) derive
-- from THIS matview, so the tab and the nugget can never compute cover math two different
-- ways. League-wide and identical for every user: no group_id, no per-user data.
--
-- Line used = the game's closing line where one exists (is_closing_line, written once at
-- first grade by _capture_closing_line), falling back to the current active line
-- (is_active_line). Historical 2022-24 imports were settled directly and never went
-- through the grading path, so they carry only a single active-line snapshot and no
-- closing flag -- the fallback is what lets those seasons appear at all. 'fanduel' (the
-- default line_source used by grading's coalesce(cfg.line_source,'fanduel')) is preferred
-- when a game has lines from more than one book, so the whole surface reads one book.
--
-- Cover math: `margin` is home-relative (>0 home covered, <0 away covered, =0 push), so
-- each perspective row flips the sign. is_favorite is read off the sign of the closing
-- spread (NULL for a pick'em, spread_value = 0). Only is_scoring weeks (ADR-0016) with
-- BOTH final scores and a usable line are included; games missing a score or a line are
-- dropped (the "~17% missing scores" in older imports render as thinner samples, surfaced
-- via the n= caveat in the UI).
--
-- Widened for the League tab v2 epic (#425) with four reference columns the new aggregate
-- views consume, all at the same (game, team-perspective) grain: spread_value and margin are
-- restated TEAM-RELATIVE (negative spread_value = this team is favored; margin > 0 = this team
-- covered, = 0 push), commence_time carries the kickoff for primetime-slot classification, and
-- opponent_team_id names the other side for divisional matchups. The original home-relative
-- margin still lives in the `scored` CTE below; the per-perspective sign flip happens in the
-- final SELECT alongside ats_result, so the two conventions can never disagree.
--
-- The margin formula is INLINED here rather than calling public.ats_margin_at_lock, even
-- though that function is the canonical definition (grade_pick uses it, ADR-0007). Reason:
-- the ADR-0012 from-empty drift guard (verify-src-reproduces-migrations.ts) applies all of
-- supabase/src/** in generator phase order -- views (this file) emit BEFORE functions, so
-- referencing ats_margin_at_lock makes the view fail to create from empty ("function does
-- not exist"). The real migration chain is unaffected (the function pre-exists from the
-- baseline), but keeping the view self-contained keeps src/** applyable from empty. This is
-- a deliberate, small duplication of the ATS formula: if ats_margin_at_lock/grade_pick ever
-- changes (ADR-0007), update this expression to match.
--
-- Materialized (ADR-0013): refreshed by public.refresh_leaderboard_stats() at the end of a
-- grading run; the unique index below lets that refresh run CONCURRENTLY. Matviews cannot
-- carry RLS, so all reads are service-role-only (the server reads via the service key; the
-- data is league-wide public context with no cross-group/-user dimension to isolate).
-- DROP ... CASCADE (not DROP VIEW): #406 made this a matview and the league_ats_* aggregate
-- views select from it (a hard pg_depend edge), so re-emitting this file drops them too --
-- every migration that re-emits this file must also re-touch each pre-existing dependent so
-- the generator bundles its recreate into the same migration (same rule as
-- league_completed_standings). Dependents as of #425: league_ats_team, league_ats_fav_dog,
-- league_ats_home_away, league_ats_situational (the four recreated unchanged) plus the five
-- #425 aggregates (league_ats_spread_buckets, _quadrants, _primetime, _divisional, _streaks).
-- The five #425 views are new files, so the generator always emits them; the four pre-existing
-- dependents only recreate when their own file hash changes -- which is why each is re-touched.
drop materialized view if exists public.league_ats_base cascade;

create materialized view public.league_ats_base as
with scored as (
  select
    s.year as season_year,
    w.week_number,
    g.id as game_id,
    g.commence_time,
    g.home_team_id,
    g.away_team_id,
    (g.final_scores ->> 'home')::int as home_pts,
    (g.final_scores ->> 'away')::int as away_pts,
    cl.spread_team_id,
    cl.spread_value,
    -- Inlined ATS margin (mirrors public.ats_margin_at_lock / grade_pick, ADR-0007) -- see
    -- the header note on why this is not a function call. Home-relative: apply the spread
    -- against whichever side it favors.
    ((g.final_scores ->> 'home')::int - (g.final_scores ->> 'away')::int)
      + case
          when cl.spread_team_id = g.home_team_id then -abs(cl.spread_value)
          when cl.spread_team_id = g.away_team_id then abs(cl.spread_value)
          else 0
        end as margin
  from public.games g
  join public.weeks w on w.id = g.week_id
  join public.seasons s on s.id = w.season_id
  -- One line per game: closing where present, else the active snapshot; fanduel-first.
  -- CROSS JOIN LATERAL drops games with no usable line, satisfying "no line -> excluded".
  cross join lateral (
    select gl.spread_team_id, gl.spread_value
    from public.game_lines gl
    where gl.game_id = g.id
      and (gl.is_closing_line or gl.is_active_line)
    order by (gl.source = 'fanduel') desc, gl.is_closing_line desc, gl.fetched_at desc
    limit 1
  ) cl
  where w.is_scoring
    and (g.final_scores ->> 'home') is not null
    and (g.final_scores ->> 'away') is not null
)
select
  sc.season_year,
  sc.week_number,
  sc.game_id,
  sc.commence_time,
  persp.team_id,
  persp.opponent_team_id,
  persp.is_home,
  -- Favored per the closing spread: spread_value < 0 favors spread_team_id, so this team
  -- is favored when it IS the spread team on a negative line, or the OTHER team on a
  -- positive line. NULL on a pick'em (spread_value = 0) so it is excluded from fav/dog
  -- splits but still counted in overall and home/away splits.
  case
    when sc.spread_value = 0 then null
    when persp.team_id = sc.spread_team_id then sc.spread_value < 0
    else sc.spread_value > 0
  end as is_favorite,
  -- Team-relative spread (#425): sc.spread_value is stated on sc.spread_team_id, so flip it
  -- for the other side. Negative = this team favored, positive = underdog, 0 = pick'em;
  -- abs() is the line magnitude league_ats_spread_buckets groups by.
  case
    when persp.team_id = sc.spread_team_id then sc.spread_value
    else -sc.spread_value
  end as spread_value,
  -- Team-relative cover margin (#425): sc.margin is home-relative, so the away perspective
  -- flips the sign. > 0 this team covered by that many points, = 0 push, < 0 did not cover
  -- (always agrees with ats_result below).
  case when persp.is_home then sc.margin else -sc.margin end as margin,
  -- Did THIS team cover? margin is home-relative, so the away perspective flips the sign.
  case
    when sc.margin = 0 then 'push'
    when (persp.is_home and sc.margin > 0) or (not persp.is_home and sc.margin < 0) then 'win'
    else 'loss'
  end as ats_result,
  -- Straight-up (moneyline) result for this team. NFL ties count as a push.
  case
    when sc.home_pts = sc.away_pts then 'push'
    when (persp.is_home and sc.home_pts > sc.away_pts)
      or (not persp.is_home and sc.away_pts > sc.home_pts) then 'win'
    else 'loss'
  end as su_result
from scored sc
cross join lateral (
  values
    (sc.home_team_id, true, sc.away_team_id),
    (sc.away_team_id, false, sc.home_team_id)
) as persp(team_id, is_home, opponent_team_id);

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the (season_year, team_id)
-- read filters used by the /league aggregates and the per-game nugget lookup.
create unique index if not exists uq_league_ats_base
  on public.league_ats_base (game_id, team_id);

-- Season/team read filters (the aggregate views group by these; PostgREST filters on them).
create index if not exists ix_league_ats_base_season_team
  on public.league_ats_base (season_year, team_id);

revoke all on public.league_ats_base from public, anon, authenticated;
grant select on public.league_ats_base to service_role;

-- file: views/league_ats_divisional.sql
-- Favorite ATS cover rate split by divisional vs non-divisional matchup for the /league
-- situational-angles module (#425, wave C). One row per (season_year, is_divisional): how
-- often the favorite covers when the two teams share a division vs when they do not.
--
-- A divisional matchup is same conference AND same division (division names like 'East'
-- repeat across conferences, so both must match), read from teams.division / teams.conference
-- (seeded for the 32 NFL teams in 0229_seed_team_divisions.sql) joined via the opponent
-- carried on league_ats_base.opponent_team_id. Games where either side has no
-- division/conference -- e.g. a non-NFL league, per the epic's non-goal -- cannot be
-- classified and are excluded.
--
-- Grain mirrors league_ats_fav_dog: one favorite-perspective row per game (is_favorite =
-- true), so favorite_covers + underdog_covers + pushes = games. is_divisional is symmetric
-- across the two sides, so restricting to the favorite row is exactly one row per game.
--
-- Plain view over the service_role-only league_ats_base matview; matches that grant and
-- carries no RLS. New file for #425.
create or replace view public.league_ats_divisional as
select
  b.season_year,
  (t.conference = o.conference and t.division = o.division) as is_divisional,
  count(*)::int as games,
  count(*) filter (where b.ats_result = 'win')::int as favorite_covers,
  count(*) filter (where b.ats_result = 'loss')::int as underdog_covers,
  count(*) filter (where b.ats_result = 'push')::int as pushes
from public.league_ats_base b
join public.teams t on t.id = b.team_id
join public.teams o on o.id = b.opponent_team_id
where b.is_favorite is true
  and t.division is not null
  and t.conference is not null
  and o.division is not null
  and o.conference is not null
group by b.season_year, (t.conference = o.conference and t.division = o.division);

revoke all on public.league_ats_divisional from public, anon, authenticated;
grant select on public.league_ats_divisional to service_role;

-- file: views/league_ats_fav_dog.sql
-- Favorite vs. underdog ATS cover counts for the /league fav/dog module (issue #406), at
-- (season_year, week_number) grain so the UI can show both a per-week breakdown and a
-- season aggregate (summed in the read model). Restricted to the favorite-perspective row
-- of each game (is_favorite = true), which is exactly one row per game that has a favorite,
-- so favorite_covers + underdog_covers + pushes = games. Pick'em games (spread_value = 0,
-- is_favorite NULL) have no favorite and are excluded. Cover percentages are derived in the
-- read model (favorite_covers / (favorite_covers + underdog_covers), pushes excluded).
--
-- A plain view over the league_ats_base matview (no duplicated aggregation). Service-role
-- only, matching the base grant; carries no RLS. Selecting from a matview is a hard
-- pg_depend dependency, so `drop materialized view league_ats_base cascade` also drops this
-- view -- re-touch this file in every migration that re-emits league_ats_base.sql (same
-- rule as league_completed_standings).
-- Re-touched unchanged for #425 (League tab v2): the definition below is identical to #406,
-- but this file's hash must change so the generator recreates the view after league_ats_base's
-- cascade drop (see the dependents note in league_ats_base.sql).
create or replace view public.league_ats_fav_dog as
select
  b.season_year,
  b.week_number,
  count(*)::int as games,
  count(*) filter (where b.ats_result = 'win')::int as favorite_covers,
  count(*) filter (where b.ats_result = 'loss')::int as underdog_covers,
  count(*) filter (where b.ats_result = 'push')::int as pushes
from public.league_ats_base b
where b.is_favorite = true
group by b.season_year, b.week_number;

revoke all on public.league_ats_fav_dog from public, anon, authenticated;
grant select on public.league_ats_fav_dog to service_role;

-- file: views/league_ats_home_away.sql
-- League-wide home vs. away ATS and straight-up (SU) cover counts for the /league
-- home/away module (issue #406), one row per season_year. Home and away rows are mirror
-- images (each game contributes one of each), so home_games = away_games and home ATS
-- covers are the complement of away ATS covers (pushes aside) -- both sides are surfaced
-- because the module compares them directly. Cover percentages are derived in the read
-- model from these raw counts (covers / (covers + losses), pushes excluded).
--
-- A plain view over the league_ats_base matview (no duplicated aggregation). Service-role
-- only, matching the base grant; carries no RLS. Selecting from a matview is a hard
-- pg_depend dependency, so `drop materialized view league_ats_base cascade` also drops this
-- view -- re-touch this file in every migration that re-emits league_ats_base.sql (same
-- rule as league_completed_standings).
-- Re-touched unchanged for #425 (League tab v2): the definition below is identical to #406,
-- but this file's hash must change so the generator recreates the view after league_ats_base's
-- cascade drop (see the dependents note in league_ats_base.sql).
create or replace view public.league_ats_home_away as
select
  b.season_year,
  count(*) filter (where b.is_home)::int as home_games,
  count(*) filter (where b.is_home and b.ats_result = 'win')::int as home_ats_covers,
  count(*) filter (where b.is_home and b.ats_result = 'loss')::int as home_ats_losses,
  count(*) filter (where b.is_home and b.ats_result = 'push')::int as home_ats_pushes,
  count(*) filter (where b.is_home and b.su_result = 'win')::int as home_su_wins,
  count(*) filter (where b.is_home and b.su_result = 'loss')::int as home_su_losses,
  count(*) filter (where b.is_home and b.su_result = 'push')::int as home_su_pushes,
  count(*) filter (where not b.is_home)::int as away_games,
  count(*) filter (where not b.is_home and b.ats_result = 'win')::int as away_ats_covers,
  count(*) filter (where not b.is_home and b.ats_result = 'loss')::int as away_ats_losses,
  count(*) filter (where not b.is_home and b.ats_result = 'push')::int as away_ats_pushes,
  count(*) filter (where not b.is_home and b.su_result = 'win')::int as away_su_wins,
  count(*) filter (where not b.is_home and b.su_result = 'loss')::int as away_su_losses,
  count(*) filter (where not b.is_home and b.su_result = 'push')::int as away_su_pushes
from public.league_ats_base b
group by b.season_year;

revoke all on public.league_ats_home_away from public, anon, authenticated;
grant select on public.league_ats_home_away to service_role;

-- file: views/league_ats_primetime.sql
-- Favorite ATS cover rate split by kickoff slot for the /league situational-angles module
-- (#425, wave C). One row per (season_year, slot): TNF (Thursday night), SNF (Sunday night),
-- MNF (Monday night), or 'day' (everything else -- Sunday afternoon, international morning,
-- Saturday and holiday day games).
--
-- The slot is classified from commence_time converted to America/New_York, so it is DST-safe
-- across the season (EDT in September, EST by January): the conversion yields the New York
-- wall-clock, and a night game is one whose ET day-of-week is Thu/Sun/Mon AND ET hour >= 18
-- (6pm). Using `at time zone` rather than the raw UTC timestamp is what keeps an 8pm ET
-- kickoff -- stored as the small-hours UTC of the next day -- from being misread as a day
-- game, and keeps the classification stable whether the game is played under EDT or EST.
--
-- Grain mirrors league_ats_fav_dog: one favorite-perspective row per game (is_favorite =
-- true), so favorite_covers + underdog_covers + pushes = games. Pick'em games are excluded
-- (no favorite). favorite_covers = favorite ATS win, underdog_covers = favorite ATS loss.
--
-- Plain view over the service_role-only league_ats_base matview; matches that grant and
-- carries no RLS. New file for #425.
create or replace view public.league_ats_primetime as
with kicked as (
  select
    b.season_year,
    b.ats_result,
    (b.commence_time at time zone 'America/New_York') as et
  from public.league_ats_base b
  where b.is_favorite is true
),
slotted as (
  select
    season_year,
    ats_result,
    case
      when extract(dow from et) = 4 and extract(hour from et) >= 18 then 'TNF'
      when extract(dow from et) = 0 and extract(hour from et) >= 18 then 'SNF'
      when extract(dow from et) = 1 and extract(hour from et) >= 18 then 'MNF'
      else 'day'
    end as slot
  from kicked
)
select
  season_year,
  slot,
  count(*)::int as games,
  count(*) filter (where ats_result = 'win')::int as favorite_covers,
  count(*) filter (where ats_result = 'loss')::int as underdog_covers,
  count(*) filter (where ats_result = 'push')::int as pushes
from slotted
group by season_year, slot;

revoke all on public.league_ats_primetime from public, anon, authenticated;
grant select on public.league_ats_primetime to service_role;

-- file: views/league_ats_quadrants.sql
-- League-wide home/away x favorite/underdog ATS cover rates for the /league market-cuts
-- module (#425, wave B). One row per (season_year, is_home, is_favorite) -- the four
-- quadrants (home favorite, home underdog, away favorite, away underdog) aggregated across
-- ALL teams. This is the league-wide counterpart to the per-team league_ats_situational
-- (same crossing of the two dimensions, summed over teams).
--
-- Grain is the team-perspective row, so each game contributes two rows (one per side); that
-- is intentional -- a quadrant rate like "road underdogs cover X%" counts each qualifying
-- team-game. Pick'em games (is_favorite null) have no favorite/underdog side and are
-- excluded, exactly like league_ats_fav_dog / league_ats_situational. Cover percentages are
-- derived in the read model (ats_wins / (ats_wins + ats_losses), pushes excluded).
--
-- Plain view over the service_role-only league_ats_base matview (no duplicated aggregation);
-- matches that grant and carries no RLS. New file for #425.
create or replace view public.league_ats_quadrants as
select
  b.season_year,
  b.is_home,
  b.is_favorite,
  count(*)::int as games,
  count(*) filter (where b.ats_result = 'win')::int as ats_wins,
  count(*) filter (where b.ats_result = 'loss')::int as ats_losses,
  count(*) filter (where b.ats_result = 'push')::int as ats_pushes
from public.league_ats_base b
where b.is_favorite is not null
group by b.season_year, b.is_home, b.is_favorite;

revoke all on public.league_ats_quadrants from public, anon, authenticated;
grant select on public.league_ats_quadrants to service_role;

-- file: views/league_ats_situational.sql
-- Per-team situational ATS split for the pick-card nugget (issue #406, PR 2): one row per
-- (season_year, team_id, is_home, is_favorite) with that team's ATS record in exactly that
-- situational quadrant (home/away x favorite/underdog). The nugget on GameCard.svelte looks
-- up the single row matching this game -- the team's fixed home/away side crossed with
-- favorite/underdog per the current line -- and renders e.g. "6-2 ATS as home favorite (n=8)".
--
-- Reads the same league_ats_base matview as the /league aggregate views, so no aggregation is
-- duplicated (acceptance criterion: the tab and the nugget read one shared source of truth).
-- Unlike league_ats_team's *marginal* home/away and favorite/underdog splits, this crosses the
-- two dimensions, which is what a quadrant like "home favorite" requires. Pick'em games
-- (is_favorite null) have no favorite/underdog quadrant and are excluded here; the nugget omits
-- them too.
--
-- Plain view over a service_role-only matview: it matches that grant and carries no RLS. A
-- plain view selecting from a matview is a hard pg_depend edge, so `drop materialized view
-- league_ats_base cascade` also drops THIS view -- exactly like league_ats_team /
-- league_ats_fav_dog / league_ats_home_away, this file must be re-touched in any migration that
-- re-emits league_ats_base.sql so the generator bundles the recreate into the same migration.
-- Re-touched unchanged for #425 (League tab v2): the definition below is identical to #406,
-- but this file's hash must change so the generator recreates the view after league_ats_base's
-- cascade drop (see the dependents note in league_ats_base.sql).
create or replace view public.league_ats_situational as
select
  b.season_year,
  b.team_id,
  b.is_home,
  b.is_favorite,
  count(*)::int as games,
  count(*) filter (where b.ats_result = 'win')::int as ats_wins,
  count(*) filter (where b.ats_result = 'loss')::int as ats_losses,
  count(*) filter (where b.ats_result = 'push')::int as ats_pushes
from public.league_ats_base b
where b.is_favorite is not null
group by b.season_year, b.team_id, b.is_home, b.is_favorite;

revoke all on public.league_ats_situational from public, anon, authenticated;
grant select on public.league_ats_situational to service_role;

-- file: views/league_ats_spread_buckets.sql
-- Favorite ATS cover rate split by spread magnitude for the /league market-cuts module
-- (#425, League tab v2 -- wave B). One row per (season_year, spread bucket) answering "how
-- often does the favorite of this line size cover?". Buckets follow the epic, on the absolute
-- team-relative spread abs(spread_value): pick'em (0), 1-3, 3.5-6.5, 7-9.5, 10+.
--
-- Grain: one representative row per game. For games with a favorite that is the favorite's
-- row (is_favorite = true, exactly one per game) -- matching league_ats_fav_dog -- where
-- favorite_covers = favorite ATS win, underdog_covers = favorite ATS loss, pushes = ATS push,
-- so the three sum to games. Pick'em games have no favorite; the single home-perspective row
-- stands in so the pick'em bucket still reports its game count, but favorite_covers /
-- underdog_covers are 0 there (only pushes, i.e. actual ties, are meaningful) -- the UI shows
-- pick'em for completeness with no favorite/underdog cover split.
--
-- Plain view over the service_role-only league_ats_base matview (no duplicated aggregation);
-- matches that grant and carries no RLS. New file for #425, so the generator emits it after
-- league_ats_base (alphabetically later in views/) in the same migration.
create or replace view public.league_ats_spread_buckets as
with per_game as (
  -- One row per game: the favorite's row where a favorite exists; for a pick'em (no favorite)
  -- the single home row represents the game so its bucket still counts.
  select
    b.season_year,
    b.is_favorite,
    b.ats_result,
    case
      when abs(b.spread_value) = 0 then 0
      when abs(b.spread_value) <= 3 then 1
      when abs(b.spread_value) <= 6.5 then 2
      when abs(b.spread_value) <= 9.5 then 3
      else 4
    end as bucket_order
  from public.league_ats_base b
  where b.is_favorite is true
     or (b.is_favorite is null and b.is_home)
)
select
  season_year,
  bucket_order,
  (array['pickem', '1-3', '3.5-6.5', '7-9.5', '10+'])[bucket_order + 1] as bucket,
  count(*)::int as games,
  count(*) filter (where is_favorite and ats_result = 'win')::int as favorite_covers,
  count(*) filter (where is_favorite and ats_result = 'loss')::int as underdog_covers,
  count(*) filter (where ats_result = 'push')::int as pushes
from per_game
group by season_year, bucket_order;

revoke all on public.league_ats_spread_buckets from public, anon, authenticated;
grant select on public.league_ats_spread_buckets to service_role;

-- file: views/league_ats_streaks.sql
-- Per-team current ATS streak + recent form for the /league depth-&-motion module (#425,
-- wave D -- Hot/Cold). One row per (season_year, team_id): the length and direction of the
-- team's current ATS run plus its last-4 ATS record, ordered by week within the season (a
-- team plays at most once per scoring week).
--
-- Streak rules: streak_result is the team's most-recent cover result; streak_length is the
-- number of consecutive most-recent games that share it. A push carries no cover momentum, so
-- it does NOT extend a win/loss run -- a push mid-run caps the streak at the games since it,
-- and when the most-recent game is a push the streak resets to 0 (streak_result = 'push').
-- last4_* is the win/loss/push tally over the four most-recent games (fewer early in a season).
--
-- Plain view over the service_role-only league_ats_base matview (no duplicated aggregation);
-- matches that grant and carries no RLS. New file for #425.
create or replace view public.league_ats_streaks as
with ordered as (
  select
    b.season_year,
    b.team_id,
    b.week_number,
    b.ats_result,
    row_number() over (
      partition by b.season_year, b.team_id
      order by b.week_number desc, b.game_id desc
    ) as rn
  from public.league_ats_base b
),
most_recent as (
  select season_year, team_id, ats_result as last_result
  from ordered
  where rn = 1
),
first_break as (
  -- Position (counting back from the most-recent game) of the first game whose result differs
  -- from the most-recent one; no row means every game so far shares that result.
  select o.season_year, o.team_id, min(o.rn) as break_rn
  from ordered o
  join most_recent m on m.season_year = o.season_year and m.team_id = o.team_id
  where o.ats_result is distinct from m.last_result
  group by o.season_year, o.team_id
),
totals as (
  select season_year, team_id, count(*) as total_games
  from ordered
  group by season_year, team_id
),
last4 as (
  select
    season_year,
    team_id,
    count(*) filter (where ats_result = 'win')::int as last4_wins,
    count(*) filter (where ats_result = 'loss')::int as last4_losses,
    count(*) filter (where ats_result = 'push')::int as last4_pushes
  from ordered
  where rn <= 4
  group by season_year, team_id
)
select
  m.season_year,
  m.team_id,
  t.name as team_name,
  t.short_name as team_short_name,
  m.last_result as streak_result,
  -- Consecutive most-recent games sharing streak_result. break_rn - 1 leading same-result
  -- games (or all of them when nothing differs); a most-recent push has no active run.
  case
    when m.last_result = 'push' then 0
    else coalesce(fb.break_rn - 1, tot.total_games)::int
  end as streak_length,
  l.last4_wins,
  l.last4_losses,
  l.last4_pushes
from most_recent m
join public.teams t on t.id = m.team_id
join totals tot on tot.season_year = m.season_year and tot.team_id = m.team_id
join last4 l on l.season_year = m.season_year and l.team_id = m.team_id
left join first_break fb on fb.season_year = m.season_year and fb.team_id = m.team_id;

revoke all on public.league_ats_streaks from public, anon, authenticated;
grant select on public.league_ats_streaks to service_role;

-- file: views/league_ats_team.sql
-- Per-team, per-season ATS record for the /league per-team table (issue #406): one row
-- per (season_year, team_id) with the overall ATS and straight-up (SU) record plus
-- home/away and favorite/underdog ATS splits. Cover percentages are computed in the read
-- model from these raw counts (wins / (wins + losses), pushes excluded) so the rounding
-- rule lives in one place.
--
-- A plain view over the league_ats_base matview (no aggregation logic is duplicated across
-- the /league surfaces -- they all read base). Reads a service_role-only matview, so it
-- matches that grant and carries no RLS. A plain view selecting from a matview is a hard
-- pg_depend dependency: `drop materialized view league_ats_base cascade` (see that file)
-- also drops THIS view, so this file must be re-touched in every migration that re-emits
-- league_ats_base.sql -- otherwise the CASCADE drop has no recreate to pair with (same
-- rule as league_completed_standings over leaderboard_season_totals).
-- Re-touched unchanged for #425 (League tab v2): the definition below is identical to #406,
-- but this file's hash must change so the generator recreates the view after league_ats_base's
-- cascade drop (see the dependents note in league_ats_base.sql).
create or replace view public.league_ats_team as
select
  b.season_year,
  b.team_id,
  t.name as team_name,
  t.short_name as team_short_name,
  count(*)::int as games,
  count(*) filter (where b.ats_result = 'win')::int as ats_wins,
  count(*) filter (where b.ats_result = 'loss')::int as ats_losses,
  count(*) filter (where b.ats_result = 'push')::int as ats_pushes,
  count(*) filter (where b.su_result = 'win')::int as su_wins,
  count(*) filter (where b.su_result = 'loss')::int as su_losses,
  count(*) filter (where b.su_result = 'push')::int as su_pushes,
  count(*) filter (where b.is_home and b.ats_result = 'win')::int as home_ats_wins,
  count(*) filter (where b.is_home and b.ats_result = 'loss')::int as home_ats_losses,
  count(*) filter (where b.is_home and b.ats_result = 'push')::int as home_ats_pushes,
  count(*) filter (where not b.is_home and b.ats_result = 'win')::int as away_ats_wins,
  count(*) filter (where not b.is_home and b.ats_result = 'loss')::int as away_ats_losses,
  count(*) filter (where not b.is_home and b.ats_result = 'push')::int as away_ats_pushes,
  count(*) filter (where b.is_favorite and b.ats_result = 'win')::int as fav_ats_wins,
  count(*) filter (where b.is_favorite and b.ats_result = 'loss')::int as fav_ats_losses,
  count(*) filter (where b.is_favorite and b.ats_result = 'push')::int as fav_ats_pushes,
  count(*) filter (where b.is_favorite = false and b.ats_result = 'win')::int as dog_ats_wins,
  count(*) filter (where b.is_favorite = false and b.ats_result = 'loss')::int as dog_ats_losses,
  count(*) filter (where b.is_favorite = false and b.ats_result = 'push')::int as dog_ats_pushes
from public.league_ats_base b
join public.teams t on t.id = b.team_id
group by b.season_year, b.team_id, t.name, t.short_name;

revoke all on public.league_ats_team from public, anon, authenticated;
grant select on public.league_ats_team to service_role;
