-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0218_guide_seen_at.sql
alter table public.users add column if not exists guide_seen_at timestamptz;
