-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0206_notification_log.sql
-- ---------------------------------------------------------------------------
-- notification_log
-- Audit trail + dedupe ledger for sent push notifications. Written by the
-- service role only; users may read their own rows via RLS.
--   kind:   'pick_reminder' | 'line_shift' | 'results_recap' | 'ai_recap' | 'test'
--   detail: e.g. { "from": -3, "to": -5.5, "threshold": 2 }
--   group_id: set for group-scoped kinds (e.g. 'ai_recap', dedup per user+group+week)
-- ---------------------------------------------------------------------------
create table if not exists public.notification_log (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.users(id) on delete cascade,
  kind       text not null,
  game_id    uuid references public.games(id) on delete cascade,
  week_id    integer references public.weeks(id) on delete cascade,
  group_id   uuid,
  detail     jsonb,
  created_at timestamptz not null default now()
);

-- Additive column for existing DBs (must run before the group_id index below).
-- No inline FK: public.groups is defined later (0208_groups.sql); the FK
-- constraint is added in 0227_notification_log_group_fk.sql once it exists.
alter table public.notification_log
  add column if not exists group_id uuid;

create index if not exists idx_notification_log_user_kind_game
  on public.notification_log (user_id, kind, game_id);

create index if not exists idx_notification_log_user_kind_group_week
  on public.notification_log (user_id, kind, group_id, week_id);

alter table public.notification_log enable row level security;

-- file: schemas/0207_notification_prefs.sql
-- ---------------------------------------------------------------------------
-- users.notification_prefs
-- Per-user notification settings: a master switch plus per-trigger config.
-- Added as a separate ALTER so the legacy users table source stays untouched.
--   { "enabled": bool,
--     "pick_reminders": bool,
--     "ai_recap": bool,
--     "line_shift": { "enabled": bool, "threshold": number } }
-- ---------------------------------------------------------------------------
alter table public.users
  add column if not exists notification_prefs jsonb not null default
    '{"enabled": false, "pick_reminders": true, "ai_recap": true, "line_shift": {"enabled": true, "threshold": 2}}'::jsonb;

-- The ADD COLUMN above is a no-op once the column already exists (from the
-- original migration, before "ai_recap" existed), so the default must also be
-- set explicitly for it to actually change on already-migrated databases.
alter table public.users
  alter column notification_prefs set default
    '{"enabled": false, "pick_reminders": true, "ai_recap": true, "line_shift": {"enabled": true, "threshold": 2}}'::jsonb;

-- file: schemas/0227_notification_log_group_fk.sql
-- notification_log.group_id FK, added here (not inline in 0206_notification_log.sql)
-- because public.groups does not exist until 0208_groups.sql.
alter table public.notification_log
  drop constraint if exists notification_log_group_id_fkey;

alter table public.notification_log
  add constraint notification_log_group_id_fkey
  foreign key (group_id)
  references public.groups(id)
  on delete cascade;
