-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0209_group_memberships.sql
create table if not exists public.group_memberships (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  role public.group_membership_role not null default 'member',
  status public.group_membership_status not null default 'active',
  joined_at timestamptz not null default now(),
  -- Per-player AI recap opt-out (ADR-0008, dec. 4). Default false = opted-in.
  -- When true the player appears only as neutral facts in generated recaps.
  ai_recap_opt_out boolean not null default false,
  primary key (group_id, user_id)
);

-- Additive column for existing DBs.
alter table public.group_memberships
  add column if not exists ai_recap_opt_out boolean not null default false;
