-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;



-- file: schemas/0235_participation_boundary.sql
-- Participation boundary (ADR-0037, #712/#722): a game counts for a member only if it
-- starts on or after BOTH the league's competition start and that member's join:
--
--   game.commence_time >= greatest(groups.competition_starts_at, group_memberships.joined_at)
--
-- Without it, the missed-pass in public._grade_games_by_ids enumerates every active member
-- with no pick and manufactures a penalty for every pre-participation game: a league created
-- in Week 10 accrues misses for Weeks 1-9, and a member added in Week 4 accrues misses for
-- Weeks 1-3. The latter is a live fairness defect, not a midseason-creation hypothetical.
--
-- '2000-01-01Z' below is the documented INCLUDE-ALL SENTINEL, not a real competition start.
-- It predates every NFL game this app stores, so it makes the groups/joined_at term drop out
-- of the greatest(). Read it only as "this row has no explicit start"; never compare against
-- it as if it were a date a league actually began.

-- ── Sentinel 1: groups.competition_starts_at (ADR-0037 ruling 1 + 3) ──────────────────────
--
-- Added nullable, backfilled, and only THEN given its now() default. A single
-- `add column ... not null default now()` would stamp every EXISTING row with the migration
-- instant, which is the same retroactivity bug in reverse: every already-graded game would
-- fall behind a boundary invented at deploy time. Order matters here.
alter table public.groups
  add column if not exists competition_starts_at timestamptz;

update public.groups
set competition_starts_at = '2000-01-01T00:00:00Z'
where competition_starts_at is null;

-- Ruling 5: a newly created league starts now(), so create_group needs no change to be safe
-- before the start-week picker (ADR-0037 follow-up "Issue C") ships.
alter table public.groups
  alter column competition_starts_at set default now();

alter table public.groups
  alter column competition_starts_at set not null;

-- ── Sentinel 2: legacy group_memberships.joined_at (extends ruling 3) ─────────────────────
--
-- Sentinelling only `groups` is insufficient against real data, so ruling 3 is applied to the
-- second term of the greatest() as well. Production's single league and all six of its
-- memberships carry joined_at = 2026-06-23 -- the instant those rows were created by an
-- earlier backfill, which post-dates the ENTIRE 2025 season they actually played. Left alone,
-- greatest('2000-01-01Z', '2026-06-23') = 2026-06-23 would make all 272 already-settled 2025
-- rows per member retroactively ineligible: precisely the outcome ruling 3 exists to prevent.
--
-- Targeted, not blanket: only a membership already settled for a game that PREDATES its own
-- joined_at is rewritten -- a self-evident contradiction, since you cannot have been graded
-- for a game played before you joined. A genuine late joiner (settled only for games after
-- their join) keeps their real joined_at, so the boundary still binds for them.
--
-- Deliberately NOT restricted to unlocked seasons: a member whose only history is an imported
-- grading_locked season (2022-24, ADR-0024) must be sentinelled too, or the boundary-aware
-- read surfaces of ADR-0037's follow-up would hide that imported history from them.
--
-- Idempotent: after one run the sentinel predates every game, so the predicate matches nothing.
update public.group_memberships gm
set joined_at = '2000-01-01T00:00:00Z'
where exists (
  select 1
  from public.pick_settlement ps
  join public.games g on g.id = ps.game_id
  where ps.group_id = gm.group_id
    and ps.user_id = gm.user_id
    and g.commence_time < gm.joined_at
);

-- file: functions/_private/grade_games_by_ids.sql
-- This is a new internal helper function. Note the leading underscore.
create or replace function public._grade_games_by_ids(p_game_ids uuid[])
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_missing_closing text;
begin
  -- Freeze imported seasons (ADR-0024): never (re)grade a game in a locked season.
  -- Strips locked-season games up front so closing-line capture and BOTH settlement
  -- passes below operate only on gradable games. This is the single choke point --
  -- grade_game / grade_week / grade_season and the grade cron all funnel through here,
  -- as will the #433 reconcile sweep -- so a locked (pre-2025 imported) season is inert
  -- to every grade path and its sheet-sourced settlements can never be re-derived.
  select coalesce(array_agg(g.id), '{}')
    into p_game_ids
  from public.games g
  join public.weeks w on w.id = g.week_id
  join public.seasons s on s.id = w.season_id
  where g.id = any(p_game_ids)
    and not s.grading_locked;

  if array_length(p_game_ids, 1) is null then
    return;
  end if;

  -- Capture the closing line for each game before grading (write-once).
  perform public._capture_closing_line(p_game_ids);

  -- Under House the closing line IS the graded line (ADR-0007), so refuse to grade a
  -- House row without one instead of silently substituting the pick-time line (#735).
  -- Runs AFTER capture above, so it can only fire when no pre-kickoff game_lines row
  -- ever existed to flag -- broken data, not a capture-timing artifact. It is the
  -- reason the House branch below reads cl.spread_* directly: grade_pick's margin
  -- comparisons are all false against a NULL spread, so it would fall through to
  -- 'loss' for EVERY pick on the game rather than failing. This predicate is the exact
  -- negation of that branch's `cl` lateral -- same effective-preset chain, same
  -- line_source, evaluated per pick row -- so the two can never disagree. Games with no
  -- picks are excluded: the missed-penalty pass below never reads a line.
  select string_agg(distinct m.game_id::text, ', ')
    into v_missing_closing
  from (
    select g.id as game_id
    from public.games g
    join public.picks p on p.game_id = g.id
    left join public.group_config cfg on cfg.group_id = p.group_id
    left join public.pick_settlement ps_prior
      on ps_prior.group_id = p.group_id
     and ps_prior.user_id  = p.user_id
     and ps_prior.game_id  = g.id
    left join lateral (
      select ps2.graded_preset
      from public.pick_settlement ps2
      where ps2.group_id = p.group_id
        and ps2.game_id  = g.id
      limit 1
    ) ps_cohort on true
    where g.id = any(p_game_ids)
      and coalesce(ps_prior.graded_preset, ps_cohort.graded_preset, cfg.grading_preset, 'gamer') = 'house'
      and not exists (
        select 1
        from public.game_lines gl
        where gl.game_id = g.id
          and gl.source  = coalesce(cfg.line_source, 'fanduel')
          and gl.is_closing_line
      )
  ) m;

  if v_missing_closing is not null then
    raise exception
      'grade: House preset requires a closing line but none exists for game(s) %; refusing to grade on the pick-time line (ADR-0007, #735)',
      v_missing_closing
      using errcode = 'P0001';
  end if;

  -- (1) Upsert settlements for users who DID make a pick on the given games.
  -- Effective preset = coalesce(this row's own prior, any cohort row already graded for
  -- this game, group config, 'gamer'). Frozen per game, first grade wins (ADR-0007
  -- 2026-07-15 amendment, #657): ps_prior alone only freezes a row that already exists,
  -- so a row born late into an already-graded game (added member, backfilled gap) fell
  -- through to today's group config instead of its game's frozen preset. ps_cohort closes
  -- that gap by checking ANY settlement already graded for this (group, game), not just
  -- this user's own.
  insert into public.pick_settlement (group_id, user_id, game_id, pick_id, points_delta, outcome, graded_at, graded_preset)
  select
    p.group_id,
    p.user_id,
    g.id,
    p.id,
    gp.points_delta,
    gp.outcome,
    now(),
    eff.preset
  from public.games g
  join public.picks p on p.game_id = g.id
  left join public.group_config cfg on cfg.group_id = p.group_id
  left join public.pick_settlement ps_prior
    on ps_prior.group_id = p.group_id
   and ps_prior.user_id  = p.user_id
   and ps_prior.game_id  = g.id
  left join lateral (
    select ps2.graded_preset
    from public.pick_settlement ps2
    where ps2.group_id = p.group_id
      and ps2.game_id  = g.id
    limit 1
  ) ps_cohort on true
  left join lateral (
    select gl.spread_team_id, gl.spread_value
    from public.game_lines gl
    where gl.game_id = g.id
      and gl.source  = coalesce(cfg.line_source, 'fanduel')
      and gl.is_closing_line
    limit 1
  ) cl on true
  cross join lateral (
    select coalesce(ps_prior.graded_preset, ps_cohort.graded_preset, cfg.grading_preset, 'gamer') as preset
  ) eff
  cross join lateral public.grade_pick(
    (g.final_scores->>'home')::int,
    (g.final_scores->>'away')::int,
    g.home_team_id,
    g.away_team_id,
    p.picked_team_id,
    -- House reads the closing line directly -- no coalesce to the pick-time line. The
    -- guard above has already proven cl is present for every House row here, and a
    -- fallback would be exactly the silent degradation #735 was filed for.
    case when eff.preset = 'house'
         then cl.spread_team_id
         else p.locked_spread_team_id end,
    case when eff.preset = 'house'
         then cl.spread_value
         else p.locked_spread_value end,
    p.weight::text
  ) as gp
  where g.id = any(p_game_ids)
  on conflict (group_id, user_id, game_id)
  do update set
    pick_id      = excluded.pick_id,
    points_delta = excluded.points_delta,
    outcome      = excluded.outcome,
    graded_at    = excluded.graded_at,
    graded_preset = excluded.graded_preset;

  -- (2) Upsert "missed" penalties for every ACTIVE league member who did NOT make a pick.
  -- Population is group membership, NOT global users.role (ADR-0024): the missed penalty is
  -- a league-participation rule, so a competing app-admin (users.role='admin') is penalized
  -- exactly like any other member -- the prior u.role='player' filter silently exempted the
  -- admin, which flipped the 2022 champion after the #430 re-grade. 'pending' invites are
  -- excluded. Admin app-access (is_admin(), settings/audit_log RLS) is unaffected by this.
  -- Line is irrelevant for missed picks; graded_preset is set for consistency.
  --
  -- The population is additionally bounded in TIME by the participation boundary (ADR-0037,
  -- #712): a member is penalized only for a game that started on or after
  -- _participation_start(group, member) = greatest(league competition start, their join).
  -- Without it this pass manufactured a miss for every game played before a member joined --
  -- or before the league existed -- on EVERY re-grade, and grade_season reaches the whole
  -- unlocked season. Pass (1) above needs no such gate: a pre-participation game cannot have
  -- a pick to grade.
  --
  -- This gates what gets WRITTEN; it is not a delete. An already-settled row outside the
  -- boundary is left alone by design -- post-fix the only way that arises is remove-then-
  -- rejoin (a fresh membership row with a later joined_at), where ADR-0037 ruling 6
  -- deliberately preserves the member's pre-removal graded history.
  insert into public.pick_settlement (group_id, user_id, game_id, pick_id, points_delta, outcome, graded_at, graded_preset)
  select
    gm.group_id,
    u.id,
    g.id,
    null,
    public.resolve_missed_penalty_for_game(g.id),
    'missed'::public.pick_outcome,
    now(),
    coalesce(ps_prior.graded_preset, ps_cohort.graded_preset, cfg.grading_preset, 'gamer')
  from public.games g
  cross join public.group_memberships gm
  join public.users u on u.id = gm.user_id
  left join public.group_config cfg on cfg.group_id = gm.group_id
  left join public.pick_settlement ps_prior
    on ps_prior.group_id = gm.group_id
   and ps_prior.user_id  = u.id
   and ps_prior.game_id  = g.id
  left join lateral (
    select ps2.graded_preset
    from public.pick_settlement ps2
    where ps2.group_id = gm.group_id
      and ps2.game_id  = g.id
    limit 1
  ) ps_cohort on true
  where g.id = any(p_game_ids)
    and gm.status = 'active'
    and g.commence_time >= public._participation_start(gm.group_id, u.id)
    and not exists (
      select 1
      from public.picks p
      where p.group_id = gm.group_id
        and p.game_id = g.id
        and p.user_id = u.id
    )
  on conflict (group_id, user_id, game_id)
  do update set
    -- Only update if the existing settlement is also for a missed pick.
    -- This prevents overwriting a real pick that was graded out of order.
    pick_id       = excluded.pick_id,
    points_delta  = excluded.points_delta,
    outcome       = excluded.outcome,
    graded_at     = excluded.graded_at,
    graded_preset = excluded.graded_preset
  where pick_settlement.pick_id is null;
end;
$$;

-- file: functions/_private/participation_start.sql
-- _participation_start: the single definition of the ADR-0037 participation boundary.
--
-- Returns the instant from which a (group, member) pair is eligible to be settled. A game
-- counts for that member iff:
--
--   game.commence_time >= public._participation_start(group_id, user_id)
--
-- which is greatest(the league's competition start, that member's join). One function rather
-- than the same greatest(...) join copy-pasted into every caller: the grading choke point
-- (_grade_games_by_ids), the completeness guard (tests/055), and the membership x games read
-- surfaces audited in the follow-up issue all call this, so the rule changes in one place.
--
-- Returns NULL when the pair is not a membership at all (e.g. a removed member). Every
-- comparison against NULL is NULL, so such a row is excluded rather than silently treated as
-- eligible-from-forever -- the conservative direction for a boundary check.
--
-- SECURITY DEFINER on purpose: the boundary is a scoring fact, and a caller reading under RLS
-- must not be able to see a DIFFERENT boundary (or NULL) than grading used. Born closed to
-- anon/authenticated by the _close_new_fn_acl event trigger (schemas/0000_function_acl_guard.sql,
-- ADR-0011); it is an internal helper, never a client RPC.
create or replace function public._participation_start(p_group_id uuid, p_user_id uuid)
returns timestamptz
language sql
stable
security definer
set search_path = public
as $$
  select greatest(g.competition_starts_at, gm.joined_at)
  from public.group_memberships gm
  join public.groups g on g.id = gm.group_id
  where gm.group_id = p_group_id
    and gm.user_id = p_user_id
$$;
