-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0223_weeks_is_scoring.sql
-- Non-scoring rounds (ADR-0016). Single source of truth for whether a round's graded
-- settlements count toward standings/stats. Defaults true so every existing regular week
-- keeps counting; a "practice"/"fun" or preseason round sets it false. Orthogonal to the
-- sign of week_number, which remains only the odds preseason sport-key signal.
alter table public.weeks
  add column if not exists is_scoring boolean not null default true;

-- Close the legacy preseason leak: any pre-existing negative-week (preseason) row predating
-- this flag must not count. New preseason weeks are written is_scoring=false by the schedule
-- sync. Idempotent re-run is harmless.
update public.weeks set is_scoring = false where week_number < 0;

-- file: views/leaderboard_season_totals.sql
-- One row per user per (group, season) with totals + ranks.
-- Drop-worst-week (ADR-0005): when a group enables
-- group_config.scoring_rules.drop_worst_week, a player's single lowest-scoring
-- week is omitted from total_points once they have 2+ settled weeks. The drop
-- forgives points only -- the W/L/push record and tie-breakers still count the
-- dropped week.
-- Materialized (issue #191): season standings are recomputed only at the end of a
-- grading run via public.refresh_leaderboard_stats(), not on every page load. The
-- query body below is unchanged from the prior regular view.
-- DROP MATERIALIZED VIEW (not DROP VIEW): once #191 converted this to a matview, any
-- later re-emission of this file (e.g. issue #152's keyset index below, or #274's
-- is_scoring filter) runs against a DB where it is already a matview, and `drop view`
-- errors on a matview. IF EXISTS keeps the from-empty baseline a clean no-op.
-- CASCADE: leaderboard_season_page() is `returns setof` this matview — a hard type
-- dependency that blocks a plain drop. CASCADE drops that function too; it is recreated
-- by functions/stats/leaderboard_season_page.sql (emitted after views), and the ADR-0011
-- ACL guard + service_role default privileges restore its grant on recreation.
drop materialized view if exists public.leaderboard_season_totals cascade;

create materialized view public.leaderboard_season_totals as
with season_rows as (
select
ps.user_id,
u.display_name,
u.avatar_key,
s.year as season_year,
w.id as week_id,
ps.points_delta,
ps.outcome,
ps.group_id
from public.pick_settlement ps
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
-- Non-scoring rounds (ADR-0016) never count toward standings.
where w.is_scoring
)
-- Decision-level season aggregates: raw points and the W/L/push record.
-- Record counts intentionally include every week, even one later dropped
-- (ADR-0005: drop-worst-week forgives points, not record).
, totals as (
select
user_id,
display_name,
avatar_key,
season_year,
group_id,
sum(points_delta)::int as raw_total,
count(*)::int as decisions,
count(*) filter (where outcome = 'win')::int as wins,
count(*) filter (where outcome = 'loss')::int as losses,
count(*) filter (where outcome = 'push')::int as pushes,
count(*) filter (where outcome = 'missed')::int as missed
from season_rows
group by user_id, display_name, avatar_key, season_year, group_id
)
-- Week-level points per player, used to find the single lowest week.
, week_points as (
select
user_id,
season_year,
group_id,
week_id,
sum(points_delta)::int as wk_points
from season_rows
group by user_id, season_year, group_id, week_id
)
-- Per player: count of settled weeks and the lowest week's points.
, week_summary as (
select
user_id,
season_year,
group_id,
count(*)::int as weeks_played,
min(wk_points)::int as lowest_week_points
from week_points
group by user_id, season_year, group_id
)
-- Resolved drop-worst-week flag per group (default false when no config row).
, group_drop as (
select
g.id as group_id,
coalesce((gc.scoring_rules ->> 'drop_worst_week')::boolean, false) as drop_worst_week
from public.groups g
left join public.group_config gc on gc.group_id = g.id
)
, adjusted as (
select
t.user_id,
t.display_name,
t.avatar_key,
t.season_year,
t.group_id,
t.decisions,
t.wins,
t.losses,
t.pushes,
t.missed,
-- Drop the single lowest week's points only when the group enables it AND the
-- player has 2+ settled weeks (ADR-0005). Otherwise the raw total stands.
case
when gd.drop_worst_week and ws.weeks_played >= 2
then t.raw_total - ws.lowest_week_points
else t.raw_total
end::int as total_points
from totals t
join week_summary ws
on ws.user_id = t.user_id
and ws.season_year = t.season_year
and ws.group_id = t.group_id
join group_drop gd on gd.group_id = t.group_id
)
select
a.user_id,
a.display_name,
a.season_year,
a.total_points,
a.decisions,
a.wins,
a.losses,
a.pushes,
a.missed,
dense_rank() over (
partition by a.group_id, a.season_year
order by a.total_points desc, a.wins desc, a.pushes desc
) as rank,
a.group_id,
a.avatar_key
from adjusted a;

-- Unique natural key. Required for REFRESH MATERIALIZED VIEW CONCURRENTLY and also
-- serves the (group_id, season_year) read filter in getSeasonLeaderboard.
create unique index if not exists uq_leaderboard_season_totals
  on public.leaderboard_season_totals (group_id, user_id, season_year);

-- Keyset-pagination index (issue #152, ADR-0002 query discipline). Matches the
-- (group_id, season_year) equality filter plus the exact display ordering used by
-- public.leaderboard_season_page: total_points/wins/pushes descending, with user_id
-- as the unique descending tie-breaker so the keyset cursor is total. Column order
-- and direction mirror that ORDER BY so the keyset row-value comparison and the page
-- limit are both served by a single index range scan (EXPLAIN: Index Scan, no Sort).
create index if not exists idx_leaderboard_season_totals_keyset
  on public.leaderboard_season_totals
  (group_id, season_year, total_points desc, wins desc, pushes desc, user_id desc);

-- Materialized views are NOT covered by the schema-wide `grant select on all tables`
-- (that grant excludes matviews), so service_role is granted explicitly. MVs cannot
-- carry RLS; every read goes through the service-role client, which filters by group_id.
revoke all on public.leaderboard_season_totals from public, anon, authenticated;
grant select on public.leaderboard_season_totals to service_role;

-- file: views/stats_accuracy_by_team_alltime.sql
-- Materialized (issue #191): refreshed by public.refresh_leaderboard_stats() at the end
-- of a grading run. Matviews don't support security_invoker; all reads are service-role.
-- DROP MATERIALIZED VIEW (not DROP VIEW): #191 made this a matview, so re-emission of this
-- file runs against an existing matview, and `drop view` errors on a matview.
drop materialized view if exists public.stats_accuracy_by_team_alltime;

create materialized view public.stats_accuracy_by_team_alltime as
select
  ps.user_id,
  u.display_name,
  p.picked_team_id as team_id,
  t.name as team_name,
  t.short_name as team_short_name,
  count(*)::int as decisions,
  count(*) filter (where ps.outcome = 'win')::int as wins,
  count(*) filter (where ps.outcome = 'loss')::int as losses,
  count(*) filter (where ps.outcome = 'push')::int as pushes,
  sum(ps.points_delta)::int as points,
  round(
    count(*) filter (where ps.outcome = 'win')::numeric
      / nullif(count(*) filter (where ps.outcome in ('win', 'loss')), 0),
    4
  ) as accuracy,
  ps.group_id
from public.pick_settlement ps
join public.picks p on p.id = ps.pick_id
join public.users u on u.id = ps.user_id
join public.teams t on t.id = p.picked_team_id
-- Join through to weeks only to exclude non-scoring rounds (ADR-0016); 1:1, so otherwise
-- unchanged.
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
where w.is_scoring
group by ps.user_id, u.display_name, p.picked_team_id, t.name, t.short_name, ps.group_id;

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the group_id read filter.
create unique index if not exists uq_stats_accuracy_by_team_alltime
  on public.stats_accuracy_by_team_alltime (group_id, user_id, team_id);

revoke all on public.stats_accuracy_by_team_alltime from public, anon, authenticated;
grant select on public.stats_accuracy_by_team_alltime to service_role;

-- file: views/stats_accuracy_by_team.sql
-- Materialized (issue #191): refreshed by public.refresh_leaderboard_stats() at the end
-- of a grading run. Matviews don't support security_invoker; all reads are service-role.
-- DROP MATERIALIZED VIEW (not DROP VIEW): #191 made this a matview, so re-emission of this
-- file runs against an existing matview, and `drop view` errors on a matview.
drop materialized view if exists public.stats_accuracy_by_team;

create materialized view public.stats_accuracy_by_team as
select
  ps.user_id,
  u.display_name,
  s.year as season_year,
  p.picked_team_id as team_id,
  t.name as team_name,
  t.short_name as team_short_name,
  count(*)::int as decisions,
  count(*) filter (where ps.outcome = 'win')::int as wins,
  count(*) filter (where ps.outcome = 'loss')::int as losses,
  count(*) filter (where ps.outcome = 'push')::int as pushes,
  sum(ps.points_delta)::int as points,
  round(
    count(*) filter (where ps.outcome = 'win')::numeric
      / nullif(count(*) filter (where ps.outcome in ('win', 'loss')), 0),
    4
  ) as accuracy,
  ps.group_id
from public.pick_settlement ps
join public.picks p on p.id = ps.pick_id
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
join public.teams t on t.id = p.picked_team_id
-- Non-scoring rounds (ADR-0016) never count toward stats.
where w.is_scoring
group by ps.user_id, u.display_name, s.year, p.picked_team_id, t.name, t.short_name, ps.group_id;

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the (group_id,
-- season_year) read filter in getStatsForSeason.
create unique index if not exists uq_stats_accuracy_by_team
  on public.stats_accuracy_by_team (group_id, user_id, season_year, team_id);

revoke all on public.stats_accuracy_by_team from public, anon, authenticated;
grant select on public.stats_accuracy_by_team to service_role;

-- file: views/stats_accuracy_by_weight_alltime.sql
-- Materialized (issue #191): refreshed by public.refresh_leaderboard_stats() at the end
-- of a grading run. Matviews don't support security_invoker; all reads are service-role.
-- DROP MATERIALIZED VIEW (not DROP VIEW): #191 made this a matview, so re-emission of this
-- file runs against an existing matview, and `drop view` errors on a matview.
drop materialized view if exists public.stats_accuracy_by_weight_alltime;

create materialized view public.stats_accuracy_by_weight_alltime as
select
  ps.user_id,
  u.display_name,
  p.weight,
  count(*)::int as decisions,
  count(*) filter (where ps.outcome = 'win')::int as wins,
  count(*) filter (where ps.outcome = 'loss')::int as losses,
  count(*) filter (where ps.outcome = 'push')::int as pushes,
  sum(ps.points_delta)::int as points,
  round(
    count(*) filter (where ps.outcome = 'win')::numeric
      / nullif(count(*) filter (where ps.outcome in ('win', 'loss')), 0),
    4
  ) as accuracy,
  ps.group_id
from public.pick_settlement ps
join public.picks p on p.id = ps.pick_id
join public.users u on u.id = ps.user_id
-- Join through to weeks only to exclude non-scoring rounds (ADR-0016); 1:1, so otherwise
-- unchanged.
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
where w.is_scoring
group by ps.user_id, u.display_name, p.weight, ps.group_id;

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the group_id read filter.
create unique index if not exists uq_stats_accuracy_by_weight_alltime
  on public.stats_accuracy_by_weight_alltime (group_id, user_id, weight);

revoke all on public.stats_accuracy_by_weight_alltime from public, anon, authenticated;
grant select on public.stats_accuracy_by_weight_alltime to service_role;

-- file: views/stats_accuracy_by_weight.sql
-- Materialized (issue #191): refreshed by public.refresh_leaderboard_stats() at the end
-- of a grading run. Matviews don't support security_invoker; all reads are service-role.
-- DROP MATERIALIZED VIEW (not DROP VIEW): #191 made this a matview, so re-emission of this
-- file runs against an existing matview, and `drop view` errors on a matview.
drop materialized view if exists public.stats_accuracy_by_weight;

create materialized view public.stats_accuracy_by_weight as
select
  ps.user_id,
  u.display_name,
  s.year as season_year,
  p.weight,
  count(*)::int as decisions,
  count(*) filter (where ps.outcome = 'win')::int as wins,
  count(*) filter (where ps.outcome = 'loss')::int as losses,
  count(*) filter (where ps.outcome = 'push')::int as pushes,
  sum(ps.points_delta)::int as points,
  round(
    count(*) filter (where ps.outcome = 'win')::numeric
      / nullif(count(*) filter (where ps.outcome in ('win', 'loss')), 0),
    4
  ) as accuracy,
  ps.group_id
from public.pick_settlement ps
join public.picks p on p.id = ps.pick_id
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users u on u.id = ps.user_id
-- Non-scoring rounds (ADR-0016) never count toward stats.
where w.is_scoring
group by ps.user_id, u.display_name, s.year, p.weight, ps.group_id;

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the (group_id,
-- season_year) read filter in getStatsForSeason.
create unique index if not exists uq_stats_accuracy_by_weight
  on public.stats_accuracy_by_weight (group_id, user_id, season_year, weight);

revoke all on public.stats_accuracy_by_weight from public, anon, authenticated;
grant select on public.stats_accuracy_by_weight to service_role;

-- file: views/stats_alltime_totals.sql
-- Materialized (issue #191): refreshed by public.refresh_leaderboard_stats() at the end
-- of a grading run. Matviews don't support security_invoker; all reads are service-role.
-- DROP MATERIALIZED VIEW (not DROP VIEW): #191 made this a matview, so re-emission of this
-- file runs against an existing matview, and `drop view` errors on a matview.
drop materialized view if exists public.stats_alltime_totals;

create materialized view public.stats_alltime_totals as
select
  ps.user_id,
  u.display_name,
  sum(ps.points_delta)::int as total_points,
  count(*)::int as decisions,
  count(*) filter (where ps.outcome = 'win')::int as wins,
  count(*) filter (where ps.outcome = 'loss')::int as losses,
  count(*) filter (where ps.outcome = 'push')::int as pushes,
  count(*) filter (where ps.outcome = 'missed')::int as missed,
  ps.group_id
from public.pick_settlement ps
join public.users u on u.id = ps.user_id
-- Join through to weeks only to exclude non-scoring rounds (ADR-0016); 1:1, so the
-- all-time totals are otherwise unchanged.
join public.games g on g.id = ps.game_id
join public.weeks w on w.id = g.week_id
where w.is_scoring
group by ps.user_id, u.display_name, ps.group_id;

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the group_id read filter.
create unique index if not exists uq_stats_alltime_totals
  on public.stats_alltime_totals (group_id, user_id);

revoke all on public.stats_alltime_totals from public, anon, authenticated;
grant select on public.stats_alltime_totals to service_role;

-- file: views/stats_head_to_head.sql
-- One directional row per player pair per (group, season), comparing shared-game points.
-- Materialized (issue #191): refreshed by public.refresh_leaderboard_stats() at the end
-- of a grading run. Matviews don't support security_invoker; all reads are service-role.
-- DROP MATERIALIZED VIEW (not DROP VIEW): #191 made this a matview, so re-emission of this
-- file runs against an existing matview, and `drop view` errors on a matview.
drop materialized view if exists public.stats_head_to_head;

create materialized view public.stats_head_to_head as
select
  left_ps.user_id,
  left_user.display_name,
  right_ps.user_id as opponent_user_id,
  right_user.display_name as opponent_display_name,
  s.year as season_year,
  count(*)::int as games_compared,
  count(*) filter (where left_ps.points_delta > right_ps.points_delta)::int as wins,
  count(*) filter (where left_ps.points_delta < right_ps.points_delta)::int as losses,
  count(*) filter (where left_ps.points_delta = right_ps.points_delta)::int as pushes,
  sum(left_ps.points_delta)::int as points,
  sum(right_ps.points_delta)::int as opponent_points,
  left_ps.group_id
from public.pick_settlement left_ps
join public.pick_settlement right_ps
  on right_ps.game_id = left_ps.game_id
 and right_ps.group_id = left_ps.group_id
 and right_ps.user_id > left_ps.user_id
join public.games g on g.id = left_ps.game_id
join public.weeks w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
join public.users left_user on left_user.id = left_ps.user_id
join public.users right_user on right_user.id = right_ps.user_id
-- Non-scoring rounds (ADR-0016) never count. The pair shares one game, so filtering the
-- left settlement's week excludes both sides.
where w.is_scoring
group by
  left_ps.user_id,
  left_user.display_name,
  right_ps.user_id,
  right_user.display_name,
  s.year,
  left_ps.group_id;

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the (group_id,
-- season_year) read filter in getStatsForSeason.
create unique index if not exists uq_stats_head_to_head
  on public.stats_head_to_head (group_id, user_id, opponent_user_id, season_year);

revoke all on public.stats_head_to_head from public, anon, authenticated;
grant select on public.stats_head_to_head to service_role;

-- file: views/stats_season_trend.sql
-- Weekly and cumulative season scoring per group, shaped for WeeklyCumulativeEntry.
-- Materialized (issue #191): refreshed by public.refresh_leaderboard_stats() at the end
-- of a grading run. Matviews don't support security_invoker; all reads are service-role.
-- DROP MATERIALIZED VIEW (not DROP VIEW): #191 made this a matview, so re-emission of this
-- file runs against an existing matview, and `drop view` errors on a matview.
drop materialized view if exists public.stats_season_trend;

create materialized view public.stats_season_trend as
with week_rows as (
  select
    ps.user_id,
    u.display_name,
    s.year as season_year,
    w.week_number,
    sum(ps.points_delta)::int as week_points,
    count(*) filter (where ps.outcome = 'win')::int as week_wins,
    count(*) filter (where ps.outcome = 'loss')::int as week_losses,
    count(*) filter (where ps.outcome = 'push')::int as week_pushes,
    count(*) filter (where ps.outcome = 'missed')::int as week_missed,
    ps.group_id
  from public.pick_settlement ps
  join public.games g on g.id = ps.game_id
  join public.weeks w on w.id = g.week_id
  join public.seasons s on s.id = w.season_id
  join public.users u on u.id = ps.user_id
  -- Non-scoring rounds (ADR-0016) never count toward the trend.
  where w.is_scoring
  group by ps.user_id, u.display_name, s.year, w.week_number, ps.group_id
), cumulative as (
  select
    user_id,
    display_name,
    season_year,
    week_number,
    week_points,
    week_wins,
    week_losses,
    week_pushes,
    week_missed,
    sum(week_points) over (
      partition by group_id, user_id, season_year
      order by week_number
      rows between unbounded preceding and current row
    )::int as cumulative_points,
    group_id
  from week_rows
)
select
  cumulative.user_id,
  cumulative.display_name,
  cumulative.season_year,
  cumulative.week_number,
  cumulative.week_points,
  cumulative.week_wins,
  cumulative.week_losses,
  cumulative.week_pushes,
  cumulative.week_missed,
  cumulative.cumulative_points,
  sum(cumulative.week_points) over (
    partition by cumulative.group_id, cumulative.user_id, cumulative.season_year
  )::int as season_total,
  dense_rank() over (
    partition by cumulative.group_id, cumulative.season_year, cumulative.week_number
    order by cumulative.cumulative_points desc
  ) as cumulative_rank_this_week,
  cumulative.group_id
from cumulative;

-- Unique natural key for REFRESH ... CONCURRENTLY; also serves the (group_id,
-- season_year) read filter in getWeeklyCumulative.
create unique index if not exists uq_stats_season_trend
  on public.stats_season_trend (group_id, user_id, season_year, week_number);

revoke all on public.stats_season_trend from public, anon, authenticated;
grant select on public.stats_season_trend to service_role;

-- file: functions/stats/leaderboard_season_page.sql
-- leaderboard_season_page: one bounded, keyset-paginated page of a group's season
-- standings (issue #152). Reads the leaderboard_season_totals materialized view
-- (#191) and returns rows in display order -- total_points/wins/pushes descending,
-- with user_id as the unique descending tie-breaker so the cursor is a total order
-- and pages are stable under inserts. Served by idx_leaderboard_season_totals_keyset.
--
-- Keyset cursor: pass the last row of the previous page as
-- (p_after_total_points, p_after_wins, p_after_pushes, p_after_user_id). All four are
-- NULL for the first page. The row-value comparison `(...) < (...)` works because the
-- ORDER BY is descending on every cursor column, so "after the cursor" == "tuple is
-- lexicographically less than the cursor tuple".
--
-- SECURITY INVOKER by design. The source matview is granted to service_role ONLY
-- (#191) -- it holds every group's rows and carries no RLS -- so this function is
-- reachable only by the service-role server client, which is the group_id trust
-- boundary (it passes the caller's own group from the session). It is intentionally
-- NOT granted to authenticated: that would let any signed-in user read other groups'
-- standings by passing an arbitrary p_group_id, violating ADR-0002 cross-group denial.
-- service_role EXECUTE comes from the blanket grant in grants/admin_grants.sql; the
-- closed-by-default ACL guard strips the implicit PUBLIC grant.
--
-- Re-emitted with #274: this function `returns setof` leaderboard_season_totals, so any
-- re-emission of that matview must CASCADE-drop this function (see the view source) and
-- recreate it here afterward. The ACL guard + default privileges re-close/grant on recreate.
create or replace function public.leaderboard_season_page(
  p_group_id uuid,
  p_season_year int,
  p_limit int default 50,
  p_after_total_points int default null,
  p_after_wins int default null,
  p_after_pushes int default null,
  p_after_user_id uuid default null
)
returns setof public.leaderboard_season_totals
language sql
stable
as $$
  select *
  from public.leaderboard_season_totals
  where group_id = p_group_id
    and season_year = p_season_year
    and (
      p_after_user_id is null
      or (total_points, wins, pushes, user_id)
         < (p_after_total_points, p_after_wins, p_after_pushes, p_after_user_id)
    )
  order by total_points desc, wins desc, pushes desc, user_id desc
  limit least(greatest(coalesce(p_limit, 50), 1), 200);
$$;

comment on function public.leaderboard_season_page(uuid, int, int, int, int, int, uuid) is
  'Keyset-paginated page of a group''s season standings (issue #152). service_role-only; '
  'the server passes the caller''s own group_id as the trust boundary (ADR-0002).';
