-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0211_group_config.sql
-- GROUP_CONFIG: one row per group, holds group-owned gameplay settings.
-- Operational settings (odds-quota caps, penalties) remain on the global settings table.
create table if not exists public.group_config (
  group_id    uuid primary key references public.groups(id) on delete cascade,
  -- Which odds source this group uses for its active line
  line_source text not null default 'fanduel',
  -- Flexible JSONB bag for gameplay rule knobs (drop-worst-week, multipliers, etc.)
  -- Future rule features (issue #107) write their settings here.
  scoring_rules jsonb not null default '{}',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- file: schemas/0212_group_week_overrides.sql
-- GROUP_WEEK_OVERRIDES: per-week rule overrides for a group, keyed (group_id, week_id).
-- Never added as columns on the global weeks table (ADR-0002).
create table if not exists public.group_week_overrides (
  group_id   uuid    not null references public.groups(id) on delete cascade,
  week_id    integer not null references public.weeks(id) on delete cascade,
  -- Special-week rule overrides (e.g. double-points week, locked weights)
  overrides  jsonb   not null default '{}',
  created_at timestamptz not null default now(),
  primary key (group_id, week_id)
);

-- file: policies/10_rls_enable.sql
-- Enable RLS everywhere (deny by default)
alter table if exists public.picks       enable row level security;
alter table if exists public.pick_settlement enable row level security;
alter table if exists public.games       enable row level security;
alter table if exists public.game_lines  enable row level security;
alter table if exists public.results     enable row level security;
alter table if exists public.totals      enable row level security;
alter table if exists public.users       enable row level security;
alter table if exists public.settings    enable row level security;
alter table if exists public.audit_log   enable row level security;
alter table if exists public.weeks       enable row level security;
alter table if exists public.seasons     enable row level security;
alter table if exists public.teams       enable row level security;
alter table if exists public.groups      enable row level security;
alter table if exists public.group_memberships enable row level security;
alter table if exists public.group_config enable row level security;
alter table if exists public.group_week_overrides enable row level security;

-- file: policies/26_policies_group_config.sql
-- group_config: members read their own group's config; no client writes.
drop policy if exists sel_group_config_member on public.group_config;
create policy sel_group_config_member
  on public.group_config for select
  to authenticated
  using (public.is_member(group_id));

drop policy if exists ins_group_config_no_client on public.group_config;
create policy ins_group_config_no_client
  on public.group_config for insert
  to authenticated
  with check (false);

drop policy if exists upd_group_config_no_client on public.group_config;
create policy upd_group_config_no_client
  on public.group_config for update
  to authenticated
  using (false)
  with check (false);

-- group_week_overrides: members read their own group's overrides; no client writes.
drop policy if exists sel_group_week_overrides_member on public.group_week_overrides;
create policy sel_group_week_overrides_member
  on public.group_week_overrides for select
  to authenticated
  using (public.is_member(group_id));

drop policy if exists ins_group_week_overrides_no_client on public.group_week_overrides;
create policy ins_group_week_overrides_no_client
  on public.group_week_overrides for insert
  to authenticated
  with check (false);

drop policy if exists upd_group_week_overrides_no_client on public.group_week_overrides;
create policy upd_group_week_overrides_no_client
  on public.group_week_overrides for update
  to authenticated
  using (false)
  with check (false);

-- file: grants/zz_group_grants.sql
-- groups / group_memberships: authenticated access is gated by RLS.
-- Strip default public/anon ACLs first so anon has no Data API access.
revoke all on public.groups from public, anon;
revoke all on public.group_memberships from public, anon;

grant select on public.groups to authenticated;
grant select, insert on public.group_memberships to authenticated;

grant execute on function public.is_member(uuid) to authenticated, service_role;

-- group_config / group_week_overrides: authenticated read gated by RLS.
-- Client writes are blocked by policy; all writes go through service_role.
revoke all on public.group_config from public, anon;
revoke all on public.group_week_overrides from public, anon;

grant select on public.group_config to authenticated;
grant select on public.group_week_overrides to authenticated;
