-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0232_player_ratings.sql
-- ---------------------------------------------------------------------------
-- player_ratings
-- Cross-season "who knows ball" credibility rating read model (issue #361, ADR-0032).
-- ONE row per (group_id, user_id) carrying a rating on the 1500-centered ELO scale.
--
-- This is a persisted READ MODEL, never a source of truth. It is rebuilt from scratch out of
-- public.pick_settlement by a pure TypeScript fold ($lib/server/rating) in the same post-grade
-- step that refreshes the stats matviews, mirroring ADR-0013's recompute / self-heal contract
-- (ADR-0032 §8). It can always be regenerated from pick_settlement; a rebuild failure is logged,
-- not thrown, and self-heals on the next grade. The fairness-critical MATH lives in TS (pure,
-- unit-tested, never AI-decided); this table only stores its output.
--
-- Access: service-role ONLY. Reads go through the service-role stats composer, filtered by
-- group_id (the ADR-0013 read-model pattern) — no client ever selects this table directly. RLS is
-- enabled with NO policy (deny-all to anon/authenticated), and player_ratings_grants.sql strips the
-- default anon/PUBLIC ACL Supabase auto-grants on new tables. That is a STRICTER posture than the
-- stats matviews (which cannot carry RLS at all) while honoring ADR-0032 §8's service-role-only
-- intent; there is deliberately no permissive policy because there is no client access path.
-- ---------------------------------------------------------------------------
create table if not exists public.player_ratings (
  group_id     uuid not null,
  user_id      uuid not null,
  -- Credibility rating on the 1500 scale; NULL while the player is Unrated (below the ~20
  -- settled-decision qualification gate, ADR-0032 §5). A NULL rating IS the Unrated state.
  rating       int,
  -- Settled career spread decisions counted into the rating (missed excluded, ADR-0032 §3).
  decisions    int not null default 0,
  -- Settled decisions still needed to qualify; 0 once rated. Drives the "N to go" progress hint.
  decisions_to_qualify int not null default 0,
  -- Movement during the current (latest) season after its soft reset — the "this season" arrow.
  -- NULL while Unrated.
  season_delta int,
  -- Stamp of the rebuild that wrote this row; the rebuild prunes rows older than its own run.
  computed_at  timestamptz not null default now(),
  constraint player_ratings_pkey primary key (group_id, user_id)
);

-- RLS as defense in depth (repo convention for every public table). service_role bypasses RLS;
-- with no permissive policy, anon/authenticated see zero rows even if a grant ever leaked. The
-- (group_id, user_id) primary key already serves the group_id-scoped read (leading column), so
-- no secondary index is needed.
alter table public.player_ratings enable row level security;

-- file: views/player_rating_inputs.sql
-- Flat, service-role-only input feed for the cross-season credibility rating fold (#361, ADR-0032).
--
-- One row per SETTLED SPREAD DECISION that counts toward the rating: a real pick (pick_id not null)
-- in a scoring round (ADR-0016) that settled win / loss / push. `missed` is excluded (ADR-0032 §3:
-- an absence the standings already punish, not a bad read), and non-scoring rounds are excluded.
-- The pure TS fold ($lib/server/rating) reads this, orders each player's rows by
-- (season_year, commence_time, game_id), folds, and rebuilds public.player_ratings.
--
-- NOT materialized: it is read only during the post-grade rebuild (a few times a week) and off
-- every hot path, so re-running the join each rebuild is cheap and avoids another matview to
-- refresh. Service-role-only, like the stats matviews (ADR-0013) — reads scope by group_id. No
-- security_invoker: no client ever selects it (only the service role, which bypasses RLS).
create or replace view public.player_rating_inputs as
select
  ps.group_id,
  ps.user_id,
  s.year         as season_year,
  g.commence_time,
  g.id           as game_id,
  p.weight,
  ps.outcome
from public.pick_settlement ps
join public.picks   p on p.id = ps.pick_id
join public.games   g on g.id = ps.game_id
join public.weeks   w on w.id = g.week_id
join public.seasons s on s.id = w.season_id
where ps.pick_id is not null
  and ps.outcome in ('win', 'loss', 'push')
  and w.is_scoring;

-- Service-role only (matview-style read model, ADR-0013): strip the default anon/PUBLIC ACL
-- Supabase auto-grants on new views, then grant SELECT to service_role.
revoke all on public.player_rating_inputs from public, anon, authenticated;
grant select on public.player_rating_inputs to service_role;

-- file: grants/player_ratings_grants.sql
-- player_ratings (#361, ADR-0032): service-role-only cross-season credibility read model.
--
-- Rebuilt from a pure TS fold after each grade (ADR-0013 recompute contract). NO client access:
-- the schema enables RLS with no policy, and here we strip the default anon/PUBLIC/authenticated
-- ACL that Supabase auto-grants on new public tables (the same revoke-before-grant defense the
-- base tables use in player_grants.sql, but without any follow-on authenticated grant — reads run
-- exclusively through the service-role stats composer, filtered by group_id). service_role keeps
-- full access via admin_grants.sql, whose blanket "on all tables" grant runs earlier in the grants
-- phase and is not touched by this revoke.
revoke all on public.player_ratings from public, anon, authenticated;
