-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: functions/groups/leave_group.sql
-- leave_group: the calling user leaves the given group (ADR-0006, dec. 5).
--
-- Last-commissioner guard: if the caller is a commissioner and they are the
-- ONLY commissioner of the group, leaving is blocked. Another member must be
-- promoted to commissioner first (transfer-required, not block-only).
--
-- Error codes:
--   P0001  not authenticated
--   P0021  caller is not a member of this group
--   P0022  cannot leave as the last commissioner (promote another first)
create or replace function public.leave_group(p_group_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_caller_id          uuid;
  v_caller_role        public.group_membership_role;
  v_commissioner_count integer;
begin
  v_caller_id := auth.uid();

  if v_caller_id is null then
    raise exception 'not authenticated' using errcode = 'P0001';
  end if;

  -- Caller must be a member.
  select role into v_caller_role
  from public.group_memberships
  where group_id = p_group_id and user_id = v_caller_id;

  if not found then
    raise exception 'caller is not a member of this group' using errcode = 'P0021';
  end if;

  -- Last-commissioner guard.
  if v_caller_role = 'commissioner' then
    select count(*) into v_commissioner_count
    from public.group_memberships
    where group_id = p_group_id and role = 'commissioner';

    if v_commissioner_count <= 1 then
      raise exception 'cannot leave as the last commissioner; promote another member first'
        using errcode = 'P0022';
    end if;
  end if;

  delete from public.group_memberships
  where group_id = p_group_id and user_id = v_caller_id;
end;
$$;

revoke execute on function public.leave_group(uuid) from public, anon;

-- file: functions/groups/mint_invite.sql
-- mint_invite: commissioner creates an invite for their group (ADR-0006, dec. 2 + 4).
--
-- Generates a random URL-safe code, inserts the invite row, and returns the code.
-- max_uses = NULL means unlimited uses; expires_at = NULL means no expiry.
--
-- Error codes:
--   P0001  not authenticated
--   P0020  caller is not a commissioner of the group
create or replace function public.mint_invite(
  p_group_id  uuid,
  p_max_uses  integer  default null,
  p_expires_at timestamptz default null
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_caller_id uuid;
  v_code      text;
begin
  v_caller_id := auth.uid();

  if v_caller_id is null then
    raise exception 'not authenticated' using errcode = 'P0001';
  end if;

  if not public.is_commissioner(p_group_id) then
    raise exception 'caller is not a commissioner of this group' using errcode = 'P0020';
  end if;

  -- Generate a compact URL-safe token (~16 bytes of entropy).
  v_code := replace(replace(encode(gen_random_bytes(12), 'base64'), '+', '-'), '/', '_');
  -- Strip any trailing padding characters.
  v_code := rtrim(v_code, '=');

  insert into public.group_invites (group_id, created_by, code, max_uses, expires_at)
  values (p_group_id, v_caller_id, v_code, p_max_uses, p_expires_at);

  return v_code;
end;
$$;

revoke execute on function public.mint_invite(uuid, integer, timestamptz) from public, anon;

-- file: functions/groups/promote_member.sql
-- promote_member: commissioner promotes a plain member to commissioner (ADR-0006, dec. 4 + 5).
--
-- A group may have multiple commissioners. Promoting a member is the only way
-- to satisfy the last-commissioner guard before a commissioner leaves or is removed.
--
-- Error codes:
--   P0001  not authenticated
--   P0020  caller is not a commissioner of the group
--   P0021  target user is not a member of this group
--   P0024  target user is already a commissioner
create or replace function public.promote_member(p_group_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_caller_id   uuid;
  v_target_role public.group_membership_role;
begin
  v_caller_id := auth.uid();

  if v_caller_id is null then
    raise exception 'not authenticated' using errcode = 'P0001';
  end if;

  -- Caller must be a commissioner of this group.
  if not public.is_commissioner(p_group_id) then
    raise exception 'caller is not a commissioner of this group' using errcode = 'P0020';
  end if;

  -- Target must be a member.
  select role into v_target_role
  from public.group_memberships
  where group_id = p_group_id and user_id = p_user_id;

  if not found then
    raise exception 'target user is not a member of this group' using errcode = 'P0021';
  end if;

  if v_target_role = 'commissioner' then
    raise exception 'target user is already a commissioner' using errcode = 'P0024';
  end if;

  update public.group_memberships
  set role = 'commissioner'
  where group_id = p_group_id and user_id = p_user_id;
end;
$$;

revoke execute on function public.promote_member(uuid, uuid) from public, anon;

-- file: functions/groups/remove_member.sql
-- remove_member: commissioner removes another member from their group (ADR-0006, dec. 4 + 5).
--
-- Last-commissioner guard: if the target member is a commissioner AND they are
-- the ONLY commissioner, the removal is blocked — another commissioner must be
-- promoted first.
--
-- Error codes:
--   P0001  not authenticated
--   P0020  caller is not a commissioner of the group
--   P0021  target user is not a member of this group
--   P0022  cannot remove the last commissioner (promote another first)
--   P0023  cannot remove yourself via this call (use leave_group)
create or replace function public.remove_member(p_group_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_caller_id     uuid;
  v_target_role   public.group_membership_role;
  v_commissioner_count integer;
begin
  v_caller_id := auth.uid();

  if v_caller_id is null then
    raise exception 'not authenticated' using errcode = 'P0001';
  end if;

  -- Caller must not be removing themselves via this call.
  if v_caller_id = p_user_id then
    raise exception 'cannot remove yourself; use leave_group instead' using errcode = 'P0023';
  end if;

  -- Caller must be a commissioner of this group.
  if not public.is_commissioner(p_group_id) then
    raise exception 'caller is not a commissioner of this group' using errcode = 'P0020';
  end if;

  -- Target must be a member.
  select role into v_target_role
  from public.group_memberships
  where group_id = p_group_id and user_id = p_user_id;

  if not found then
    raise exception 'target user is not a member of this group' using errcode = 'P0021';
  end if;

  -- Last-commissioner guard: if target is a commissioner, ensure another exists.
  if v_target_role = 'commissioner' then
    select count(*) into v_commissioner_count
    from public.group_memberships
    where group_id = p_group_id and role = 'commissioner';

    if v_commissioner_count <= 1 then
      raise exception 'cannot remove the last commissioner; promote another member first'
        using errcode = 'P0022';
    end if;
  end if;

  delete from public.group_memberships
  where group_id = p_group_id and user_id = p_user_id;
end;
$$;

revoke execute on function public.remove_member(uuid, uuid) from public, anon;

-- file: functions/groups/rename_group.sql
-- rename_group: commissioner renames their group (ADR-0006, dec. 4).
--
-- Enforces the same name constraints as create_group. Runs as SECURITY DEFINER so
-- it can bypass the no-client-update RLS policy on groups; the commissioner check
-- is the trust boundary.
--
-- Error codes:
--   P0001  not authenticated
--   P0010  group name is required
--   P0011  group name too long
--   P0020  caller is not a commissioner of the group
create or replace function public.rename_group(p_group_id uuid, p_name text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_caller_id uuid;
  v_name      text;
begin
  v_caller_id := auth.uid();

  if v_caller_id is null then
    raise exception 'not authenticated' using errcode = 'P0001';
  end if;

  -- Validate name (mirrors create_group + 0221_groups_name_length.sql constraint).
  v_name := btrim(coalesce(p_name, ''));
  if length(v_name) = 0 then
    raise exception 'group name is required' using errcode = 'P0010';
  end if;
  if length(v_name) > 60 then
    raise exception 'group name too long' using errcode = 'P0011';
  end if;

  -- Caller must be a commissioner of this group.
  if not public.is_commissioner(p_group_id) then
    raise exception 'caller is not a commissioner of this group' using errcode = 'P0020';
  end if;

  update public.groups
  set name = v_name
  where id = p_group_id;
end;
$$;

revoke execute on function public.rename_group(uuid, text) from public, anon;

-- file: grants/zz_group_grants.sql
-- groups / group_memberships: authenticated access is gated by RLS.
-- Strip default public/anon ACLs first so anon has no Data API access.
revoke all on public.groups from public, anon;
revoke all on public.group_memberships from public, anon;

grant select on public.groups to authenticated;
grant select, insert on public.group_memberships to authenticated;

grant execute on function public.is_member(uuid) to authenticated, service_role;

-- create_group is the only insert path into groups (RLS blocks direct client
-- inserts). It is SECURITY DEFINER and enforces the create-gate internally.
grant execute on function public.create_group(text) to authenticated, service_role;

-- Commissioner management RPCs (ADR-0006, dec. 4 + 5): SECURITY DEFINER, caller-trust
-- verified internally; no direct client writes to groups.name or group_memberships.role.
grant execute on function public.rename_group(uuid, text)  to authenticated, service_role;
grant execute on function public.remove_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.promote_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.leave_group(uuid)         to authenticated, service_role;
grant execute on function public.mint_invite(uuid, integer, timestamptz) to authenticated, service_role;

-- group_config / group_week_overrides: authenticated read gated by RLS.
-- Client writes are blocked by policy; all writes go through service_role.
revoke all on public.group_config from public, anon;
revoke all on public.group_week_overrides from public, anon;

grant select on public.group_config to authenticated;
grant select on public.group_week_overrides to authenticated;

-- group_invites: commissioners manage invites, gated by RLS; no anon access.
revoke all on public.group_invites from public, anon;

grant select, insert, update on public.group_invites to authenticated;

grant execute on function public.is_commissioner(uuid) to authenticated, service_role;
grant execute on function public.redeem_invite(text) to authenticated, service_role;

-- comments / reactions: members read+write their group's rows, gated by RLS.
-- Strip default anon/public ACLs first (defense in depth alongside RLS).
revoke all on public.comments  from public, anon;
revoke all on public.reactions from public, anon;

grant select, insert, delete on public.comments  to authenticated;
grant select, insert, delete on public.reactions to authenticated;
