-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0222_users_display_name_length.sql
-- Cap display_name at 40 trimmed characters.
-- Defense in depth: the auth triggers (handle_new_auth_user, handle_updated_auth_user)
-- clamp via left(btrim(...), 40) before writing, so any future write path inherits the
-- constraint at the data layer.
alter table public.users
  drop constraint if exists users_display_name_max_len;
alter table public.users
  add constraint users_display_name_max_len check (length(btrim(display_name)) <= 40);

-- file: functions/auth/handle_new_auth_user.sql
-- Function: insert a row into public.users when a new auth.users row is created
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_display_name text;
begin
  -- Choose a safe, non-null display_name:
  --   1) raw_user_meta_data.display_name
  --   2) raw_user_meta_data.full_name
  --   3) email local-part
  --   4) fallback based on uuid
  v_display_name := left(btrim(coalesce(
    (new.raw_user_meta_data ->> 'display_name'),
    (new.raw_user_meta_data ->> 'full_name'),
    split_part(new.email, '@', 1),
    'user-' || left(new.id::text, 8)
  )), 40);

  insert into public.users (id, display_name, role)
  values (new.id, v_display_name, 'player')
  on conflict (id) do nothing;

  return new;
end;
$$;

-- Fire AFTER INSERT on auth.users to mirror into public.users
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- file: functions/auth/handle_updated_auth_user.sql
-- Function: keep public.users.display_name in sync if auth metadata later changes
create or replace function public.handle_updated_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_display_name text;
begin
  -- Only bother if display_name/full_name changed or was added
  if (coalesce(new.raw_user_meta_data ->> 'display_name','') is distinct from coalesce(old.raw_user_meta_data ->> 'display_name',''))
     or (coalesce(new.raw_user_meta_data ->> 'full_name','')   is distinct from coalesce(old.raw_user_meta_data ->> 'full_name',''))
  then
    v_display_name := left(btrim(coalesce(
      (new.raw_user_meta_data ->> 'display_name'),
      (new.raw_user_meta_data ->> 'full_name'),
      split_part(new.email, '@', 1),
      'user-' || left(new.id::text, 8)
    )), 40);

    update public.users
       set display_name = v_display_name
     where id = new.id;
  end if;

  return new;
end;
$$;

-- Keep display_name synced on later auth-metadata changes
drop trigger if exists on_auth_user_updated on auth.users;
create trigger on_auth_user_updated
after update on auth.users
for each row execute function public.handle_updated_auth_user();

-- file: functions/groups/redeem_invite.sql
create or replace function public.redeem_invite(p_code text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid;
  v_invite  public.group_invites%rowtype;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'not authenticated' using errcode = 'P0001';
  end if;

  -- Lock the invite row to prevent concurrent over-limit redemption.
  select * into v_invite
  from public.group_invites
  where code = p_code
  for update;

  if not found then
    raise exception 'invite not found' using errcode = 'P0002';
  end if;

  if v_invite.revoked_at is not null then
    raise exception 'invite revoked' using errcode = 'P0003';
  end if;

  if v_invite.expires_at is not null and v_invite.expires_at < now() then
    raise exception 'invite expired' using errcode = 'P0004';
  end if;

  if v_invite.max_uses is not null and v_invite.used_count >= v_invite.max_uses then
    raise exception 'invite exhausted' using errcode = 'P0005';
  end if;

  -- No-op if the caller is already a member of this group.
  if exists (
    select 1 from public.group_memberships
    where group_id = v_invite.group_id and user_id = v_user_id
  ) then
    return;
  end if;

  -- Soft cap: groups are limited to 50 members.
  if (select count(*) from public.group_memberships where group_id = v_invite.group_id) >= 50 then
    raise exception 'group is full' using errcode = 'P0006';
  end if;

  -- Atomically add membership and increment usage counter.
  insert into public.group_memberships (group_id, user_id, role)
  values (v_invite.group_id, v_user_id, 'member');

  update public.group_invites
  set used_count = used_count + 1
  where id = v_invite.id;
end;
$$;

revoke execute on function public.redeem_invite(text) from public, anon;
