-- generated by supabase/scripts/generate-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: schemas/0215_schedule_game_id.sql
-- Add ESPN event id as an observability/re-sync attribute (not an identity key).
alter table public.games
  add column if not exists schedule_game_id text;

-- Defensively remove any duplicate matchups before adding the constraint.
-- In practice the Odds API enforces uniqueness, but the migration must be safe.
with ranked as (
  select id,
         row_number() over (
           partition by week_id, home_team_id, away_team_id
           order by
             (external_game_id is null)::int, -- keep rows that already have an Odds id
             id asc
         ) as rn
  from public.games
)
delete from public.games g
using ranked r
where g.id = r.id
  and r.rn > 1;

-- The durable identity of a game is its matchup within a week.
-- Provider ids (external_game_id, schedule_game_id) are attributes, not the key.
alter table public.games
  add constraint uq_games_matchup unique (week_id, home_team_id, away_team_id);

-- file: functions/games/attach_line_to_matchup.sql
-- Odds sync helper: finds a game by the unordered team pair within a week,
-- attaches external_game_id if currently NULL, and returns the game's uuid.
-- Returns NULL when no matching matchup exists — caller should skip and report.
-- Never flips home/away; the schedule source is canonical for home/away.
create or replace function public.attach_line_to_matchup(
  p_week_id          int,
  p_home_team_id     int,
  p_away_team_id     int,
  p_external_game_id text
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  -- Match on the unordered team pair so a home/away disagreement between
  -- providers does not create a duplicate or silently miss the game.
  select id into v_id
  from public.games
  where week_id = p_week_id
    and (
      (home_team_id = p_home_team_id and away_team_id = p_away_team_id)
      or
      (home_team_id = p_away_team_id and away_team_id = p_home_team_id)
    )
  limit 1;

  if v_id is null then
    return null;
  end if;

  -- Set external_game_id only when not yet claimed; never overwrite.
  update public.games
  set external_game_id = p_external_game_id
  where id = v_id
    and external_game_id is null;

  return v_id;
end
$$;

grant execute on function public.attach_line_to_matchup(int,int,int,text)
  to authenticated, service_role;

-- file: functions/games/upsert_game_by_matchup.sql
-- Schedule sync writer: creates or updates a game row by the matchup key
-- (week_id, home_team_id, away_team_id).  Provider ids are attributes.
-- Returns the game's uuid — same id for the life of the matchup.
create or replace function public.upsert_game_by_matchup(
  p_week_id          int,
  p_home_team_id     int,
  p_away_team_id     int,
  p_commence         timestamptz,
  p_schedule_game_id text,
  p_status           text default 'scheduled'
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  insert into public.games (
    week_id, home_team_id, away_team_id, commence_time, schedule_game_id, status
  )
  values (
    p_week_id, p_home_team_id, p_away_team_id,
    p_commence, p_schedule_game_id,
    coalesce(p_status, 'scheduled')
  )
  on conflict on constraint uq_games_matchup
  do update set
    commence_time    = excluded.commence_time,
    schedule_game_id = excluded.schedule_game_id,
    -- Only advance status; never overwrite a terminal state from schedule sync.
    status           = case
                         when public.games.status in ('final', 'cancelled') then public.games.status
                         else excluded.status
                       end
  returning id into v_id;

  return v_id;
end
$$;

grant execute on function public.upsert_game_by_matchup(int,int,int,timestamptz,text,text)
  to authenticated, service_role;
