// Public demo-season snapshot types (#460, ADR-0026).
//
// The shape of the committed fixture served by the unauthenticated `/demo` route group. The
// snapshot is a generated build artifact — regenerated by `pnpm demo:snapshot` through the
// real grading → awards → Wrapped → recap pipeline — so these types describe exactly what the
// demo pages render, and the CI drift-guard fails if a demo surface references a field absent
// here. Lives under `$lib/types` (not `$lib/server`) so the demo components and the drift-guard
// unit test can import it client-side; only types cross the boundary and they are erased.
import type { PickGame } from '$lib/types/games';
import type { TeamSide, WeightCode } from '$lib/types/domain';
import type {
  LeaderboardCachePayload,
  AllTimeLeaderboardPayload,
  StatsCachePayload,
  LeagueCachePayload
} from '$lib/query/types';
import type { LeagueHonors, BadgeAward } from '$lib/types/honors';
import type { GroupMember } from '$lib/types/group';
import type { GroupPickEntry } from '$lib/types/picks';
import type { LiveScoreEntry } from '$lib/live/types';
import type { WeeklyLiveStanding } from '$lib/types/leaderboard';
import type { SeasonWrappedRow } from '$lib/types/server/seasonWrapped';
import type { RecapRow } from '$lib/server/db/queries/recaps';
import type { SeasonWeeklyAwards } from '$lib/types/server/weeklyAwards';

/**
 * How a demo live-week game reads on the frozen picks screen. The demo bakes a mid-game
 * Sunday (#585): `in_progress` games carry a live score + clock, `final_unofficial` is final
 * on the feed but not yet graded (the state that yields to grading on the real surfaces), and
 * `open` marks a game that hasn't kicked off (the "still to pick" affordance).
 */
export type DemoGameStatus = 'open' | 'in_progress' | 'final_unofficial';

/** The persona's frozen pick on one live-week game (null = no pick made). */
export type DemoPersonaPick = {
  side: TeamSide;
  weight: WeightCode;
  /** True once kickoff has passed for this game in the frozen snapshot. */
  locked: boolean;
};

/**
 * One game on the frozen live-week picks screen: the slate row, the persona's pick, the frozen
 * live/unofficial score, and the revealed group picks. The live score is the stand-in the demo
 * serves in place of `/api/live-scores` — the unauthenticated demo has no ESPN feed (#585) — and
 * the group picks drive the per-member cover dots the same way the real `RevealedGroupPicks` does.
 */
export type DemoLiveGame = PickGame & {
  status: DemoGameStatus;
  personaPick: DemoPersonaPick | null;
  /** Frozen live score for the sweat board; null on a not-started (`open`) game. */
  liveScore: LiveScoreEntry | null;
  /** Revealed member picks on this game (post-kickoff), for the group-cover dots. */
  groupPicks: GroupPickEntry[];
};

/**
 * The frozen mid-game "live" week powering the demo picks screen (the product's verb) and the
 * Weekly-tab provisional board (#585). Everything is a curated build artifact — there is no live
 * feed behind the public demo, so the scores and standings are baked at generation time.
 */
export type DemoLiveWeek = {
  weekNumber: number;
  games: DemoLiveGame[];
  /**
   * Provisional live weekly standings for the whole group, pre-assembled through the real
   * `assembleWeeklyLiveStandings` (#584) so the demo Weekly board reuses the shipped component.
   */
  standings: WeeklyLiveStanding[];
};

/** The designated "you" persona the visitor inhabits. */
export type DemoPersona = {
  userId: string;
  displayName: string;
  avatarKey: string | null;
};

/** Provenance of the frozen AI prose in this snapshot. */
export type DemoAiProse = 'live' | 'fallback';

/** Non-rendered metadata describing how/when the snapshot was generated. */
export type DemoSnapshotMeta = {
  generatedAt: string;
  groupId: string;
  groupName: string;
  completedSeasonYear: number;
  liveSeasonYear: number;
  liveWeekNumber: number;
  /** Whether the Wrapped/recap prose came from a real LLM call or the deterministic fallback. */
  aiProse: DemoAiProse;
};

/**
 * The complete committed demo snapshot. Every field is a frozen payload shaped exactly like
 * the real read paths produce, so the demo pages reuse the real presentational components.
 */
export type DemoSnapshot = {
  meta: DemoSnapshotMeta;
  persona: DemoPersona;
  liveWeek: DemoLiveWeek;
  /** Season standings, identical shape to `/api/leaderboard`. */
  leaderboard: LeaderboardCachePayload;
  /** Career standings, identical shape to `/api/leaderboard/alltime`. */
  allTime: AllTimeLeaderboardPayload;
  /** League honors + identity badges + member roster (for avatar lookup). */
  honors: {
    honors: LeagueHonors;
    badges: BadgeAward[];
    members: GroupMember[];
  };
  /** The frozen Season Wrapped for the persona (player) and the league. */
  wrapped: {
    player: SeasonWrappedRow | null;
    league: SeasonWrappedRow | null;
  };
  /** Recent weekly AI recaps for the completed season, newest first. */
  recaps: RecapRow[];
  /**
   * Every fully-graded scoring week's hardware plus the season shelf, identical shape to
   * `getSeasonWeeklyAwards` (#669) — powers `WeeklyHardware` on the Week tab/recap and
   * `SeasonShelf` on the recap.
   */
  weeklyAwards: SeasonWeeklyAwards;
  /** The completed season's Stats payload, identical shape to `/api/stats` (#669). Aspirational
   *  by design (ADR-0026 default): the demo Stats tab shows the persona as champion. */
  stats: StatsCachePayload;
  /** The live season's League/Market ATS payload, identical shape to `/api/league` (#669).
   *  Group-independent, so it matches the live picks week rather than the completed season. */
  market: LeagueCachePayload;
};
