name: PGTap Tests
on:
  pull_request:
    branches: [master]
    paths:
      - 'supabase/**'
      - '.github/workflows/ci-pgtap.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pgTap:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NODE_ENV: test
      SUPABASE_CLI_VERSION: 2.107.0
    steps:
      - uses: actions/checkout@v7
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v2
        with:
          version: ${{ env.SUPABASE_CLI_VERSION }}
      - name: Supabase Start
        run: supabase start
      - name: Run Tests
        run: supabase test db
