# .github/workflows/supabase-dry-run.yml
name: Supabase Dry Run Migrations

on:
  pull_request:
    branches: [master, develop]
    paths:
      - 'supabase/**'
      - '.github/workflows/migrate-dry-run.yml'

jobs:
  supabase-dry-run:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.base_ref == 'master' && 'Production' || 'Development' }}
    env:  
      SUPABASE_CLI_VERSION: 2.53.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
            version: ${{ env.SUPABASE_CLI_VERSION }}

      - name: Dry run migrations
        env:
          # The secret is automatically selected from the job's environment
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          echo ${{ github.base_ref}}
          echo "Dry running migrations against ${{ github.base_ref == 'master' && 'Production' || 'Development' }} environment..."
          supabase db push --db-url "$SUPABASE_DB_URL" --dry-run --yes
