-- generated by scripts/gen-func-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;


-- file: indexes/ux_active_line_per_game.sql
create unique index if not exists ux_active_line_per_game
on public.game_lines (game_id)
where is_active_line = true;

-- file: views/picks_status_view_admin.sql
create or replace view public.picks_status_view_admin
with (security_invoker = on) as
select
  p.game_id,
  g.week_id,
  p.user_id,
  u.display_name as user_display_name,
  p.weight,
  (case
     when p.picked_team_id = g.home_team_id then 'home'
     when p.picked_team_id = g.away_team_id then 'away'
   end)::public.side_enum as picked_side,
  p.picked_team_id,
  t.short_name as picked_team_short,
  p.locked_spread_value as locked_spread_value,
  p.locked_spread_team_id as locked_spread_team_id,
  p.locked_at,
  g.commence_time,
  (g.commence_time <= now()) as game_started
from public.picks p
join public.users u  on u.id = p.user_id
join public.games g  on g.id = p.game_id
join public.teams t  on t.id = p.picked_team_id;

revoke all on public.picks_status_view_admin from public;
grant select on public.picks_status_view_admin to service_role;

-- file: views/picks_status_view_user.sql
create or replace view public.picks_status_view_user
with (security_invoker = on) as
select
  p.game_id,
  g.week_id,
  p.user_id,
  p.weight,
  (case
     when p.picked_team_id = g.home_team_id then 'home'
     when p.picked_team_id = g.away_team_id then 'away'
   end)::public.side_enum as picked_side,
  p.picked_team_id,
  t.short_name as picked_team_short,
  p.locked_spread_value as locked_spread_value,
  p.locked_spread_team_id,
  p.locked_at,
  g.commence_time,
  (g.commence_time <= now()) as game_started
from public.picks p
join public.games g on g.id = p.game_id
join public.teams t on t.id = p.picked_team_id;

revoke all on public.picks_status_view_user from public;
grant select on public.picks_status_view_user to authenticated;

-- file: views/ui_games.sql
create or replace view public.ui_games as
select
  g.id                      as id,
  g.week_id,
  g.commence_time           as kickoff,
  th.short_name             as home,
  ta.short_name             as away,
  case
    when gln.home_spread < 0 then 'home'
    when gln.home_spread > 0 then 'away'
    else null
  end                       as spread_side,     -- 'home' | 'away' | null
  abs(gln.home_spread)::numeric as spread_points
from public.games g
join public.game_lines_normalized gln on gln.game_id = g.id
join public.teams th on th.id = g.home_team_id
join public.teams ta on ta.id = g.away_team_id;
