-- generated by scripts/gen-func-migration.ts
set check_function_bodies = off;
set client_min_messages = warning;

-- file: functions/_private/audit_log_action.sql
create or replace function public.audit_log_action(
  p_actor  uuid,
  p_action text,
  p_details jsonb
)
returns void
language sql
security definer
set search_path = public, pg_temp
as $$
  insert into public.audit_log (actor, action, details)
  values (p_actor, p_action, p_details);
$$;

revoke all on function public.audit_log_action(uuid, text, jsonb) from public;
grant execute on function public.audit_log_action(uuid, text, jsonb)
  to authenticated, service_role;

-- file: functions/picks/unlock_pick.sql
create or replace function public.unlock_pick(
  p_game_id uuid
)
returns table (
  ok boolean,
  user_id uuid,
  game_id uuid,
  unlocked_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid  uuid := auth.uid();
  v_game public.games%rowtype;
  v_row  public.picks%rowtype;
  v_now  timestamptz := now();
begin
  if v_uid is null then
    raise exception 'unauthorized' using errcode = 'P0001';
  end if;

  -- Serialize against concurrent lock/unlock attempts for the same game
  select * into v_game
  from public.games
  where id = p_game_id
  for update;
  if not found then
    raise exception 'game not found' using errcode = 'P0001';
  end if;

  -- Hybrid guard: status OR scheduled kickoff time
  if game_has_started(p_game_id) or v_now >= v_game.commence_time then
    raise exception 'Edits are not allowed after kickoff' using errcode = 'P0001';
  end if;

  -- Delete the pick (if present)
  with del as (
    delete from public.picks p
    where p.user_id = v_uid
      and p.game_id = p_game_id
    returning *
  )
  select * into v_row from del;

  if found then
    -- Log a successful unlock with the last-frozen line snapshot for traceability
    perform public.audit_log_action(
      v_uid,
      'unlock_pick',
      jsonb_build_object(
        'game_id', p_game_id,
        'picked_team_id', v_row.picked_team_id,
        'weight', v_row.weight,
        'final_locked_at', v_row.final_locked_at,
        'final_locked_line_id', v_row.final_locked_line_id,
        'final_locked_spread_team_id', v_row.final_locked_spread_team_id,
        'final_locked_spread_value', v_row.final_locked_spread_value
      )
    );

    return query select true, v_row.user_id, v_row.game_id, v_now;
  else
    -- Nothing to delete; still record the intent (helps debug queued/offline retries)
    perform public.audit_log_action(
      v_uid,
      'unlock_pick_noop',
      jsonb_build_object('game_id', p_game_id)
    );

    return query select false, v_uid, p_game_id, v_now;
  end if;
end
$$;

revoke all on function public.unlock_pick(uuid) from public;
grant execute on function public.unlock_pick(uuid) to authenticated, service_role;

-- file: policies/30_policies_users.sql
-- Users: everyone can read; each user may update their own display_name

drop policy if exists sel_users on public.users;
create policy sel_users
  on public.users for select
  to authenticated
  using (true);

drop policy if exists upd_users_self on public.users;
create policy upd_users_self
  on public.users for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists ins_audit_by_actor on public.audit_log;
create policy ins_audit_by_actor
on public.audit_log
for insert
to authenticated
with check (actor = auth.uid());
